### ISSUE TITLE
Just-in-time (JIT) debugging instead of this dialog box.

### ISSUE THREAD

**Issue by sutex** [cmdrmcdonald/EliteDangerousDataProvider#1]
After running the login.exe  entering email and getting the CODE. clicking continue. Exception happened, log below

Just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot perform runtime binding on a null reference
   at CallSite.Target(Closure , CallSite , Object , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at EliteDangerousCompanionAppService.CompanionAppService.StoredShipsFromProfile(Object json) in C:\Users\jgm.BEXHILL\Source\Repos\EliteDangerousDataProvider\EliteDangerousCompanionAppService\CompanionAppService.cs:line 408
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at EliteDangerousCompanionAppService.CompanionAppService.CommanderFromProfile(Object json) in C:\Users\jgm.BEXHILL\Source\Repos\EliteDangerousDataProvider\EliteDangerousCompanionAppService\CompanionAppService.cs:line 289
   at EliteDangerousCompanionAppService.CompanionAppService.CommanderFromProfile(String data) in C:\Users\jgm.BEXHILL\Source\Repos\EliteDangerousDataProvider\EliteDangerousCompanionAppService\CompanionAppService.cs:line 257
   at EliteDangerousCompanionAppService.CompanionAppService.Profile() in C:\Users\jgm.BEXHILL\Source\Repos\EliteDangerousDataProvider\EliteDangerousCompanionAppService\CompanionAppService.cs:line 220
   at EliteDangerousDataProvider.Stage2.confirmButton_Click(Object sender, EventArgs e) in C:\Users\jgm.BEXHILL\Source\Repos\EliteDangerousDataProvider\Login\Stage2.cs:line 26
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Login
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/Login.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.93.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
EliteDangerousCompanionAppService
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/EliteDangerousCompanionAppService.DLL
----------------------------------------
EliteDangerousDataDefinitions
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/EliteDangerousDataDefinitions.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.2.19309
    CodeBase: file:///D:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/Newtonsoft.Json.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by cmdrmcdonald** [comment]
Should be fixed, please re-download and try it again.

**Comment by sutex** [comment]
When I run the Login.exe , in showed ..Thank you Commander Sutex ...
I started the Game 64 bit ED have Horizon too , but started the main game ED , then alt tab back to the ' Recheck' click it , and nothing happened , still sits there.. :) , mmm . late here 1:30am , will get back too it . leave it with you until tommorrow

**Comment by cmdrmcdonald** [comment]
If you open taskmanager what does is the full name of the elite process?

**Comment by sutex** [comment]
EliteDangerous64.exe 
C:\Program Files (x86)\Frontier\EDLaunch\Products\elite-dangerous-64\EliteDangerous64.exe

**Comment by cmdrmcdonald** [comment]
I'll alter the code so that you can add a path manually if the process isn't found for any reason.

In the meantime as a workaround you can create a file

    %APPDATA%\EDDI\productpath

with the content 

    C:\Program Files (x86)\Frontier\EDLaunch\Products\elite-dangerous-64\Logs

and this should allow you to use the plugin.

**Comment by sutex** [comment]
Interface has worked,  was able too setC:\Program Files (x86)\Frontier\EDLaunch\Products\elite-dangerous-64\ .... vap needs beta va :)
