### ISSUE TITLE
Cargo Stolen flag doesn't appear to be working

### ISSUE THREAD

**Issue by Darkcyde13** [cmdrmcdonald/EliteDangerousDataProvider#101]
While experimenting with my updated Commodity Sale Check script for awp3rator in issue #100, I deliberately picked up a stolen canister of Algae to see how the script would respond to stolen cargo.

The 1 tonne of Algae is all I am carrying, and I have gone to Wood Port in the Indrachit system as this is an outpost with a Black Market not far from where I'm based.  On landing, the Algae is not considered as stolen and the 'Reminder' part at the end of the script does not get said.

After a bit more experimentation, I think I've found that the cargo.stolen flag is not working, at least not in this situation.  I've reset the script back to the default to make sure it's not anything I'd been doing, but it still doesn't work.  I've also restarted EDDI, just in case.

I've also moved the `{set carryingstolencargo to true}` to outside of the `{if cargo.stolen:` statement, and still the 'Reminder' doesn't work.  I'm really not sure if I'm doing something wrong here or not.

Algae is neither bought nor sold at this station normally, could it be something to do with this?  Although I would have thought that the cargo.stolen should be set regardless of if it's sold at the current station or not.

Just as an experiment, I tried this code:-

```
{set testing to true}
{if testing:
   Testing works
|else:
   Testing failed
}
```

This says 'Testing failed' every time. However, I'm not sure if this is how a Boolean should be handled.

**Comment by cmdrmcdonald** [comment]
The issue here is that Cottle does not understand the boolean type so 'set testing to true' won't have the desired effect.  I've added 'true' and 'false' variables to cottle to allow this to work a while back, and it should be available in the next release.

**Comment by Darkcyde13** [comment]
Ah ok, that makes sense.  Although, looking through the Cottle help, part 2.3 says right at the beginning that it does have a Boolean value type. [http://r3c.github.io/cottle/#toc-2.3]([http://r3c.github.io/cottle/#toc-2.3])  Or am I misunderstanding something here?

**Comment by cmdrmcdonald** [comment]
Although it supports them it doesn't allow you to set them.  Further down in the docs you linked it says:

"There is no way to write a constant boolean value in a template ; you can write your own functions if you really need this feature, but numeric values 0 and 1 are equivalent except in very special cases."

**Comment by Darkcyde13** [comment]
Ahhh, I missed that. Thanks for the info.  I'm looking forward to all the new features you're adding to the next version. EDDI gets better and better, and I can't imagine playing ED without it now! :)
