### ISSUE TITLE
TTS Broken

### ISSUE THREAD

**Issue by BlazerJake** [cmdrmcdonald/EliteDangerousDataProvider#102]
Whether i'm using the VA plugin or the standalone executable anytime it tries to use TTS either through testing or practical use nothing is said and the CPU usage on the executable or VA (whichever is the one being used) goes way up and goes up further each time it tries to use TTS. I've uninstalled and reinstalled several times deleting %APPDATA%\EDDI each time.

**Comment by BlazerJake** [comment]
Any help would be great. I can't figure this out and I would love to try out EDDI. It looks like an awesome piece of software. Seriously, kudos to the developer!

**Comment by Darkcyde13** [comment]
What TTS engine are you using?  I use IVONA with no problems, and I've also tried the default Windows 10 TTS engine without any trouble too.  If you've not tried already, use the Windows Default and see what happens.

**Comment by BlazerJake** [comment]
I've tried both the windows default and Ivona and they both work when i'm not using EDDI, but with both the standalone and plugin versions of EDDI they don't work.

**Comment by Darkcyde13** [comment]
Hmm.  Well, I'm no expert, just a user, I'm sure CMDR McDonald can provide better support.  Although, it sounds to me like your TTS voices may not be installed/working properly?  Have you tried reinstalling IVONA?

I believe that EDDI uses .NET you could try reinstalling and/or up dating that to the latest version.

Also check out the troubleshooting here: https://github.com/cmdrmcdonald/EliteDangerousDataProvider/blob/master/TROUBLESHOOTING.md

There are extra log files that can be sent to the developer (cmdrmcdonald) but only do these if he requests you to do so.

However, all this could be rubbish as I don't really know how EDDI is written.  Sorry, I'm just guessing, but it can't hurt to try them.

**Comment by BlazerJake** [comment]
Again, the TTS voices work fine when i'm not using EDDI & this issue includes the default voices.

**Comment by cmdrmcdonald** [comment]
This sounds like the media feature pack in your Windows installation is corrupt.  Please could you try reinstalling it (search for 'media feature pack' along with your version of Windows to find it).

If that doesn't solve the issue then please enable verbose logging in EDDI, recreate the issue, then upload the logs.  Enabling verbose logging and uploading the logs are options available on the first tab when EDDI opens.

**Comment by BlazerJake** [comment]
I have the US version of windows 10 the media feature pack doesn't apply to my version as those features are built in to the OS

**Comment by BlazerJake** [comment]
I finally figured it out! Apparently Window's "Speech Properties" voice activation was enabled as well as "Review documents and mail to improve accuracy". I guess this was causing some conflict with EDDI. The plugin works great now and I look forward to using it extensively! I'll leave this open for a bit so I know you've seen it.

**Comment by Darkcyde13** [comment]
Ahh so I was kinda along the right lines saying it was something to do with the voices rather than EDDI.  I had a look at those setting on my PC and I don't have them enabled, so that's why I've not come across this problem.
