### ISSUE TITLE
VA ((EDDI: commander variables)) issues with two variables

### ISSUE THREAD

**Issue by FireSammy** [cmdrmcdonald/EliteDangerousDataProvider#106]
for example: "Commander home system: {TXT:Home system} Star System" -results always correctly, but the "Commander home station: {TXT:Home station}" -results lately and every time with "Not set" 

Additionally, the {DEC:Insurance}% will result correctly into the VA log list, when logging in first time and triggered by the ((EDDI commander continued)) "10:38:06 - Current EDDI ship insurance excess percentage is set to: 3.75%"

After that when testing the variables again with the ((EDDI: commander variables)) results look like this:
12:03:53 - Home station: Not set
12:03:53 - Insurance: Not set%

**Comment by cmdrmcdonald** [comment]
Please could you provide a copy of your %APPDATA%\EDDI\eddi.json file?

**Comment by FireSammy** [comment]
Sorry my noobness, but could you give me more detailed info how to do that? This thing won't accept json -files and not WinRAR...

winzip is not freeware, so gonna add it into the dropbox, and add the link here: https://www.dropbox.com/s/o54af0q1hsw1l95/eddi.json%20FireSammy.7z?dl=0

**Comment by cmdrmcdonald** [comment]
Your home station is set to 'Howe' but that doesn't exist, which is why the home station isn't being set.  If you change your home station to 'Howe Platform' it should work.

**Comment by FireSammy** [comment]
I tried that already, but i will change it again to see if works now. Just a sec.... Opening EDDI and make change, close it and logging into the game from the desktop

First time check'd:
11:58:47 - Commander home station: Howe Platform
11:58:41 - Current EDDI ship insurance excess percentage is set to: 3.75%
11:58:33 - Plugin command : '((EDDI commander continued))' 
All variables spot on correctly, OK

Second check: 
12:00:31 - Home station: Howe Platform
12:00:31 - Insurance: Not set%
12:00:22 - Recognized : 'test commander variables' (Confidence 89)
All other variables correct, but the insurance fails.

I guess there was a typo, or something with that home station, but at least it's now correct, thank you very mucho. Write '[Blue] Insurance: {DEC:Insurance}%' to log, -but donno what is wrong with this then?

**Comment by cmdrmcdonald** [comment]
Insurance is a known issue that will be fixed in the next release.
