### ISSUE TITLE
Feature Request: Parse MissionFailed event

### ISSUE THREAD

**Issue by omega9380** [cmdrmcdonald/EliteDangerousDataProvider#107]
Probably already on the list, but wanted to suggest it anyway.  Could you set up an event to parse the MissionFailed journal event?  I use EDDI and VA to track how many missions I currently have while I am mission grinding for Fed rank.  I use a variable called MissionCount to track the number, increasing with the MissionAccepted event, and decreasing with the MissionCompleted event.  I realized when I failed a mission that the MissionFailed event is not parsed by EDDI, so I can't decrease my count automatically and have to manually update the variable.  Just curious when you were gonna throw that one out there.  Thanks!!

**Comment by cmdrmcdonald** [comment]
Available in 2.2.0
