### ISSUE TITLE
EDDI config tool v1.1.0

### ISSUE THREAD

**Issue by jpotelle** [cmdrmcdonald/EliteDangerousDataProvider#11]
The EDDI configuration tool is not saving (or perhaps not loading) the optional home Station field. The home System field works OK.

**Comment by jpotelle** [comment]
OK, just checked %appdata%\EDDI\eddi.json.  Config is saving the station I enter upon closing. But upon running Config again, Station is not loaded. So "null" is saved when closing (if no edits are made).

**Comment by cmdrmcdonald** [comment]
Thanks for reporting this issue.  This has been fixed and will be available in the next release.
