### ISSUE TITLE
Issue adding Elite Dangerous companion app data - had to reinstall after computer lockup

### ISSUE THREAD

**Issue by Amocki** [cmdrmcdonald/EliteDangerousDataProvider#110]
My computer locked up and I didn't hear EDDI talking while I jumped systems or landing on a planet.  I uninstalled it, and then reinstalled it.  But now it is show the error below. 

Great app by the way!  I really like that it will tell me about the system as I jump in, not to mention what I can sell and such at the stations.  :-D 

![eddi issue](https://cloud.githubusercontent.com/assets/25403925/22397602/12976120-e543-11e6-87c7-5cbc319a77c9.png)

**Comment by omega9380** [comment]
Try this:

Close EDDI.  Go to C:\Users\{your username}\AppData\Roaming\EDDI.  Delete the "credentials.json" file.  Reopen EDD and go to the Companion App tab.  Sign in again.

Hope that helps!!

**Comment by cmdrmcdonald** [comment]
You might also need to remove the %APPDATA%\EDDI\ships.json file

**Comment by Amocki** [comment]
Thanks!  I ended up just deleting the whole appdata\eddi folder, because it
gave me the same error just removing the one file.

Thanks for the help!
