### ISSUE TITLE
Shipyard variables Stored ships not set and Stored ships n model not updating correctly

### ISSUE THREAD

**Issue by mikelimtw** [cmdrmcdonald/EliteDangerousDataProvider#111]
Hi CmdrMcDonald,

Before I begin, I would like to thank you for all the time and hard work you've put into EDDI so all the rest of us can enjoy a truly immersive experience!

I have found two issues regarding shipyard variables after using the ((EDDI ship swapped)) event:

Issue #1: {INT:Stored ships} is currently NOT SET.

I have 2 ships in storage. I tried looking at {TXT:Stored ship n=1,2 model} and they are populated, so EDDI seems to know that I have 2 ships in storage. I have also checked the Shipyard tab in EDDI configuration and all 3 of my ships are listed.

Issue #2: {TXT:Stored ship n model} is not updating correctly.

I am using VoiceAttack to say {TXT:Stored ship n=1,2 model) after the ((EDDI ship swapped)) event to debug. What I found is if I swap from my Cobra into my Viper the variables for n=1,2 shows my Viper and Sidewinder as stored, and not my Cobra and Sidewinder. If I swap back to my Cobra the two ships showing as stored show up as my Cobra and my Sidewinder as opposed to my Viper and Sidewinder. 

I have included both my EDDI.log and Ships.json files. Any help you can provide on this would be much appreciated. Thank you!

[EDDI.zip](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/files/737342/EDDI.zip)

EDIT #1:
I just checked with ED Market Connector and it is not showing the correct ship I am in unless I do an update. I guess this won't be updated until my next ship swap or docking event.

**Comment by cmdrmcdonald** [comment]
{INT:Stored ships} will be set in the next release, although it will be known as {INT:Stored ship entries} to be consistent with other similar values.

The companion API can be a little slow, so obtaining up-to-date information on current ship Vs. shipyard ships can be tricky.  I've tweaked the existing code to attempt to handle this situation a bit better where it does have the information that it needs (e.g. swapping ships rather than purchasing a new ship).

**Comment by mikelimtw** [comment]
I checked using ED Connector and the update there is also lagged.  I see your note #111 and I agree that would probably be the only way to permanently resolve this issue. Anyway, thanks for your work on this amazing plug-in!

**Comment by cmdrmcdonald** [comment]
This is fixed in release 2.2.0.
