### ISSUE TITLE
Insurance variable not set

### ISSUE THREAD

**Issue by mikelimtw** [cmdrmcdonald/EliteDangerousDataProvider#112]
I have been using the pre-flight check script included in EDDI and have wondered why it very often gives me a warning about my insurance excess. I got rid of that message and decided to write my own insurance check routine and found that {DEC:Insurance} comes up as 'Not Set' in VoiceAttack.

**Comment by cmdrmcdonald** [comment]
This will be fixed in the next release.

**Comment by mikelimtw** [comment]
Great, thanks! I've got a workaround for this as I created a VA script to check all the storage slots and do a count. It's working fine so I may not change it, I just thought I'd let you know about this.

**Comment by cmdrmcdonald** [comment]
This is fixed in release 2.2.0.
