### ISSUE TITLE
Feature Request: Track ship fuel and shields percentages

### ISSUE THREAD

**Issue by mikelimtw** [cmdrmcdonald/EliteDangerousDataProvider#114]
Hi CmdrMcDonald,

I'm not sure this can be done since I can't find these events in the documentation provided by Frontier. What I'd like is more granularity regarding the percentage of fuel left and also shields. Elite is obviously keeping track of this information, but I don't know if you can get at it.

The shields is the more important of the two as I want to write an automated routine to manage power during combat and I'd want to put power to shields before they go down, not after. I look forward to your view on this. Thanks!

**Comment by cmdrmcdonald** [comment]
This information is not available in the journal so it isn't something that EDDI can provide.

**Comment by mikelimtw** [comment]
That's what I thought. Thanks for looking into this.
