### ISSUE TITLE
Ship variable issue.

### ISSUE THREAD

**Issue by MazuuMa** [cmdrmcdonald/EliteDangerousDataProvider#115]
First off i wanted to say thanks for this amazing piece of software.. it helps greatly to increase immersion for elite:dangerous.

On to the issue at hand... i was trying to mess around with different reactions from VA for different ships using the {TXT:Ship Name} variable. This seems to work for the most part. However, i have two anaconda's who i've given different names in EDDI. the "oldest" anaconda (ExploraConda) loses the variable value on ship switch... 

If i log into the game and ask EDDI to get the ship name it gives me the correct value. If i then switch to my combat anaconda and request the name it too gives me te correct value (AnaCombat). However, if i then switch back again to anaconda one and request the ship name it comes back as "Not Set".

If i log out of the game again and log back in into my explorer anaconda the name is "back". If i log back in into my combat anaconda and switch ships the value is again "Not Set". 
I think it might have something to do with both ships being anaconda's.. but this is just speculation on my part.

Regards,

Mazuu

**Comment by cmdrmcdonald** [comment]
This should be fixed in 2.1.1-b4.  If you aren't testing the betas then I expect the full release of 2.1.1 in the next few days.

**Comment by cmdrmcdonald** [comment]
This is fixed in release 2.2.0.
