### ISSUE TITLE
Documention: Variables {TXT:Ship value} and {TXT:Credits} mislabeled in help file

### ISSUE THREAD

**Issue by mikelimtw** [cmdrmcdonald/EliteDangerousDataProvider#117]
Hi CmdrMcDonald,

I found that the above two spoken text variables are incorrectly labeled in your documentation. As labeled they are NOT SET. The correct variable names should be {TXT:Ship value (spoken)} and {TXT:Credits (spoken)}. These are the only two I am currently using where I discovered the discrepancy, but there may be others.

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this; it will be fixed in the next release.
