### ISSUE TITLE
Discounted module & ship prices in coriolis export

### ISSUE THREAD

**Issue by jvml** [cmdrmcdonald/EliteDangerousDataProvider#118]
Would love to see the real purchase prices of all modules and ships in the coriolis export along with their real discount percentages.

**Comment by cmdrmcdonald** [comment]
Module prices are sent to coriolis, the more difficult item will be for coriolis to show them in a sensible and persistent manner.

**Comment by cmdrmcdonald** [comment]
Coriolis issue.
