### ISSUE TITLE
Error Loading Profile

### ISSUE THREAD

**Issue by straywt** [cmdrmcdonald/EliteDangerousDataProvider#12]
When I try to load the profile into Voice Attack if gives me an Instance Validation Errror: 'ConditionElseIf' is not a valid value for ActionTypeEnum. The occurs in XML document (398, 12) and multiple other places in the VAP file.

![image](https://cloud.githubusercontent.com/assets/18653717/14775257/a5e0c518-0a8b-11e6-9d2c-a2865649de1e.png)

**Comment by cmdrmcdonald** [comment]
You need to use the latest beta version of VoiceAttack, currently 1.5.8.16.

**Comment by straywt** [comment]
Oh, sorry. I guess have latest release, not Beta. Thought I checked the version, probably didn't read all the digits. Sorry.

Thanks for your response and the app.

-Thomas

Sent from my mobile phone.


On Apr 25, 2016, at 6:05 AM, cmdrmcdonald <notifications@github.com> wrote:

You need to use the latest beta version of VoiceAttack, currently 1.5.8.16.
