### ISSUE TITLE
EDDI high CPU when configuring, frequent hangups. 

### ISSUE THREAD

**Issue by StraythePath** [cmdrmcdonald/EliteDangerousDataProvider#123]
Tried to install EDDI three or four times the last several days. CPU usage goes straight to about 80%, at the configuration menu, trying to test the TTS results in hanging and 100% usage, but no audio. Persists for a few seconds and then stops. 

Went through the step by step, changed the TTS voice to see if that'd change anything, no dice. Closing out of the configuration leaves EDDI running(as expected), but continues the 80% CPU usage, with the only thing logged into via the configuration being the companion menu. 

Running voice attack after, with EDDI still installed produces no audio from voice attack when issuing commands.

**Comment by cmdrmcdonald** [comment]
Can you check Window's "Speech Properties" to ensure that voice activation is disabled, and that "Review documents and mail to improve accuracy" is unchecked?

**Comment by StraythePath** [comment]
Enable Voice Activation is unchecked, as is Review Documents and mails to improve accuracy.

**Comment by StraythePath** [comment]
Done and done. I'll also post a couple observations I made during in case they're any help.

Upon first starting EDDI(which required a new install), CPU usage hovered around 30%. It stood this way until I closed the configuration menu, at which point it jumped to 60-70% and remained there until I ended the process. I closed it through task manager, renamed the log to preserve it and then started EDDI again. 

Once again CPU usage hovered around 30%. To test, I went over to the TTS tab and hit test voice. As usual, no voice played and CPU usage from EDDI immediately started spiking. I let that run several seconds and then sent that log.

**Comment by cmdrmcdonald** [comment]
I've taken a look at the logs but there's nothing in there that suggests a problem with EDDI.  In the past when this has been reported it has been down to the Windows speech recognition settings so I can only suggest that you try tweaking them and seeing if you can find something that works for you.  Sorry I can't be more help at the moment.

**Comment by StraythePath** [comment]
No worries. As it happens now, when I start EDDI it just goes straight to being an active process without actually bringing up the configuration window; yet voice attack doesn't say EDDI's active or anything(and still gives no response to commands). 
Odd, but these things happen~ Thanks for the assistance anyway.

**Comment by cmdrmcdonald** [comment]
In this situation your best bet is to stop EDDI, remove the %APPDATA%\EDDI directory and start it up again.

**Comment by Tkael** [comment]
If this issue is resolved, please mark it as "closed". Thanks!
