### ISSUE TITLE
Companion App Connection

### ISSUE THREAD

**Issue by mia389** [cmdrmcdonald/EliteDangerousDataProvider#124]
I just recently installed EDDI. Great program! Today I went to play Elite and EDDI was having problems connecting to Companion APP. I took a picture below of the error it gave me. I tried multiple times to login. Do the key code it ask me for the one that Steam gives me? I have two. One for horizons and one for elite. I tried both but neither worked. I dont remember which I used when I first set it up.

I also tried the beta version with same issue.

https://gyazo.com/a37ee5a5cd36dda8c46aab1658009702

You can change to solved. I seen in my junk mail it sent me a code. I am now logged in again.

**Comment by cmdrmcdonald** [comment]
This should be a code emailed to you by Frontier when you enter your password.

If you aren't having any luck with it please shut down EDDI, remove %APPDATA%\EDDI\credentials.json and try again
