### ISSUE TITLE
Feature Request: Parse GalNet News

### ISSUE THREAD

**Issue by mikelimtw** [cmdrmcdonald/EliteDangerousDataProvider#125]
I know this functionality is made available by other add-ons such as VAExtensions + Galnewsreader and the ED Toolbox plugin, but the former doesn't seem to work - or at least I can't get it to work with the most current 2.0 version of VAExtensions and I don't use ED Toolbox.

Would it be possible to make more robust GalNet news parsing and make it part of EDDI natively? I'd like to see the following features:

* Specify by voice how many headlines you'd like to hear... "Give me the last # headlines"
* Specify which article you want to have read back to you "Read article #"
* Provide weekly summary as posted by Frontier including PowerPlay updates.

You can use the Galnewsreader thread found here: [https://forums.frontier.co.uk/showthread.php/67293-Galnews-feed-gt-TTS](url) as a reference for some functionality.

It would be nice to have this news read out to you, instead of having to hop out of the game, or open up a web page to read this stuff while you're flying around. Thanks!

**Comment by cmdrmcdonald** [comment]
EDDI already has a galnet reader that reports news as it is posted.  It doesn't store it at the moment, but there are plans to add more persistent state to EDDI at which point the more complex features would become possible.

**Comment by mikelimtw** [comment]
I'm looking forward to this, thanks!

**Comment by cmdrmcdonald** [comment]
The Galnet reader has been enhanced in EDDI 2.3 (currently in beta).
