### ISSUE TITLE
System Visited Count 

### ISSUE THREAD

**Issue by delta2-7** [cmdrmcdonald/EliteDangerousDataProvider#126]
Hi Loving EDDI  in conjunction with VA a great addition and full credit to your dedication in making it more..  that said I appear to be in a catch 22 I cannot get any system bar one to accurately tell me how many times I have visited a system when exiting a jump.  Even after multi jumps it still remains "this is your first time visiting this system" even tho I have been here dozens of times.  In conjunction with that I am informed a systems uninhabited when I am delivering missions to that system.

I do use ED Market connector and EDDiscovery Vr5.3.4.0 for keeping track of data in conjunction with Cmdrs Log Vr2.1d so I know the data is being added . 

I appreciate your very busy, I'm sorry if this has been addressed in the past, I tried searching for the answer under issues but could find nothing (prob my comp skills at fault), thanks in advance.

**Comment by cmdrmcdonald** [comment]
It sounds as though your %APPDATA%\EDDI\eddi.sqlite database has become corrupt.  First things first: shut down EDDI and remove this file, then restart EDDI.

This will lose your visit information, but I suspect that you're keeping it in EDSM.  If this is the case then you can restore your visit details on the EDSM tab of EDDI, after which it should start to record your visits correctly again.  Let me know if this works for you.

**Comment by delta2-7** [comment]
Thanks, I believe that has resolved it.
