### ISSUE TITLE
The shipyard tab is now empty after updating to 2.2.0

### ISSUE THREAD

**Issue by larrybann** [cmdrmcdonald/EliteDangerousDataProvider#127]
I was previously on 2.1.0 and upgraded today to 2.1.0  After getting a new ship I wanted to name it but noticed all my ships were no longer listed in shipyard.  I tried uninstalling (including deleting the %APPDATA%/EDDI folder)/reinstalling but issue persists.  Everything else works fine.   I can still travel to systems and hear it call out which system I am heading to.

**Comment by delta2-7** [comment]
Hi Larry this happened before to me, simply relog into Companion App and reenter the code given and you will find it back as it was (least it was for me the 2nd time round after rewriting all 15 names again).  Hope that helps.

**Comment by larrybann** [comment]
Yes, that fixed it!
