### ISSUE TITLE
EDDI 1.1.0 - log watcher

### ISSUE THREAD

**Issue by jpotelle** [cmdrmcdonald/EliteDangerousDataProvider#13]
The log watcher plugin function seems to be unstable. At least, it seems so, since every time I jump to another star system the EDDI event loop stops. I setup a "reboot" command just to restart everything up. I'm using VA v1.5.8.16 prerelease. Or maybe it's VA that's not stable... :)

**Comment by cmdrmcdonald** [comment]
The event loop will stop if you edit the VoiceAttack profile.  If you restart VoiceAttack and don't touch it afterwards does the event loop continue when you change star system?

**Comment by jpotelle** [comment]
Yep, that was it. Works OK if I don't edit anything.  But I do A LOT of editing lately. e.g. integrating EDDI into my profile along with HCS voice packs. Is there a way to avoid restarting VA all the time?

**Comment by cmdrmcdonald** [comment]
You can quickly switch to a different profile and then back, which will restart the event loop.

I've been talking to VA support about this issue as I think it's a bug, but haven't had much luck over the past few months.  I'll keep pushing to see if they will fix this.

**Comment by jpotelle** [comment]
Switching profiles didn't work for me (I've tried this before). VA 1.5.8.16; no luck. VA 1.5.8.18 prerelease I just got yesterday - still no luck.  But I can live with shutting down and restarting VA - I've done 95% of my profile editing...
