### ISSUE TITLE
Companion App - WHERE?

### ISSUE THREAD

**Issue by Slider16** [cmdrmcdonald/EliteDangerousDataProvider#130]
Really loving EDDI. Keep up the good work.  Can you tell me where to find the official "Companion App" to use with your program?  I have been looking and looking.  I cannot find it anywhere.

Also, the email and password that it wants, is that something I will setup through the companion app?   That will be something separate from my Frontier credentials, correct?   It is not clear which creds are needed here, and I'm not about to enter my Frontier creds.

Thanks

**Comment by cmdrmcdonald** [comment]
The companion app is a Frontier API.  To access the data you need to use your Frontier username and password so that it can obtain the required information.
