### ISSUE TITLE
ApproachSettlement event?

### ISSUE THREAD

**Issue by Tkael** [cmdrmcdonald/EliteDangerousDataProvider#133]
Added to the player journal, but not yet added to EDDI?
Thanks!

**Comment by cmdrmcdonald** [comment]
This has been added to the next release of EDDI however be aware that FD's implementation of this is currently somewhat buggy, in that when approaching a planet in supercruise it will often trigger one of these events for each settlement on the planet.  I've raised a bug with FD regarding this behaviour but in the meantime you might have multiple triggers of this event when still some distance from any one settlement.

**Comment by cmdrmcdonald** [comment]
This has been incorporated in to EDDI 2.3 (currently in beta).
