### ISSUE TITLE
Bounty awarded journal change?

### ISSUE THREAD

**Issue by Tkael** [cmdrmcdonald/EliteDangerousDataProvider#134]
According to the documentation, the Bounty Awarded event is supposed to return the name of the pilot I destroyed under {event.target}. I've noticed that {event.target} in the bounty awarded script is giving me the name of my target's ship rather than the name of my opponent. 

Doing some further investigating, the NPC name does not appear to be made available (any longer?) via the journal... the target ship is reported instead. Here's a snip from my last play session:
`{ "timestamp":"2017-02-18T04:38:54Z", "event":"Bounty", "Rewards":[ { "Faction":"Federation", "Reward":272227 }, { "Faction":"Sutekh Law Party", "Reward":153630 } ], "Target":"anaconda", "TotalReward":425857, "VictimFaction":"Sutekh First" }`

Comparing to the player journal manual, the example FDev gives lists a ship under the target rather than a name:
`{ "timestamp":"2016-06-10T14:32:03Z", "event":"Bounty", "Rewards": [ {"Faction":"Federation", "Reward":1000 }, {"Faction":"Nuenets Corp.", "Reward": 10280} ],"Target":"Skimmer", "TotalReward":11280, "VictimFaction":"MMU" }`

I'm searching the journal thread on the FDev forums, but I haven't found any definitive comments on this. I'm sure that you have already been following the forum thread closely... do you know if this was this an intentional change? If so, the description in EDDI should be updated. If not, we may want to open a bug report with FDev.

**Comment by Darkcyde13** [comment]
This is something I came across a while ago.  I noticed it when I first started playing with EDDI back in November, and I vaguely remember reading somewhere that it was never available, although my memory could be playing tricks on me.  As far as I know, 'target' has always reported the ship type rather than pilot name in this event.

**Comment by cmdrmcdonald** [comment]
Target generally returns the model of the ship you destroyed, although I believe that it returns the commander if it was a PvP bounty.  I'll update EDDI's documentation to make this clear.
