### ISSUE TITLE
Old reported version

### ISSUE THREAD

**Issue by jpotelle** [cmdrmcdonald/EliteDangerousDataProvider#135]
http://api.eddp.co/eddi/version
still shows 2.1.0

**Comment by cmdrmcdonald** [comment]
That's an old API that shouldn't be used any more; as of EDDI 2.1.0 a new API is in place for version information.

**Comment by jpotelle** [comment]
Please update the docs. re:
{TXT:Ship callsign}: the callsign of the ship as shown in EDDI configuration **(e.g. "GEF-1020")**

**Comment by jpotelle** [comment]
What's the new API? I can't find it in the EDDI docs.

**Comment by cmdrmcdonald** [comment]
The versioning API is internal and information on it isn't published.
