### ISSUE TITLE
Callsign returns manufacturer

### ISSUE THREAD

**Issue by jpotelle** [cmdrmcdonald/EliteDangerousDataProvider#137]
EDDI 2.2.0
FYI, {TXT:Ship callsign} returns the ship manufacturer, not the call sign.

**Comment by cmdrmcdonald** [comment]
EDDI's original callsigns were removed when Frontier introduced their own style.  You should hear something like "Lakon Juliet Papa Oscar", where the words after the manufacturer are the first three letters of your commander's name.  What does this value show if you write it to the VoiceAttack log?

**Comment by jpotelle** [comment]
Yeah, that's it. Please update the docs. re:
{TXT:Ship callsign}: the callsign of the ship as shown in EDDI configuration (e.g. "GEF-1020")

**Comment by cmdrmcdonald** [comment]
The fix for this has been incorporated in to EDDI 2.3 (currently in beta).
