### ISSUE TITLE
report volcanism

### ISSUE THREAD

**Issue by vonpickles** [cmdrmcdonald/EliteDangerousDataProvider#139]
I've never used GitHub so I hope I'm doing this right and this is the correct way to ask. I just start using EDDI with ED and absolutely love it. However, I know nothing about programming or scripting.

In the Body scanned script, there is a section that reads:
{_Atmosphere }
{_Volcanism }
I was looking to have this report both Atmosphere and Volcanism in addition to what it already is doing. Currently, it just skips this and moves to rotation.
I've been trying to duplicate what similar scripts say but am having no luck, and Google doesn't seem to be helping either.

What would go here so that it would report these conditions as well?

Thanks so much in advance.

**Comment by cmdrmcdonald** [comment]
This is on the list to add, but I haven't managed to get around to gathering all of the correct internal names for the different atmosphere and volcanisms.

**Comment by vonpickles** [comment]
Thanks for the reply. Seems I was jumping the gun. You've done an amazing job with this! I'll def be on the lookout for future updates

**Comment by cmdrmcdonald** [comment]
This has been incorporated in to EDDI 2.3 (currently in beta).

**Comment by vonpickles** [comment]
Oh wow! That is great news! Thanks so much for your work on this. I found EDDI a month or so back and incorporated it into VA. Makes this game so much better and immersive.

<handing you an internet virtual beer>
