### ISSUE TITLE
Feature Request: Option to use Coriolis beta at ECDC

### ISSUE THREAD

**Issue by mikelimtw** [cmdrmcdonald/EliteDangerousDataProvider#140]
Hi Cmdr McDonald,

There is a better version of Coriolis on https://beta.coriolis.edcd.io that now takes into account engineered modules, which the standard Coriolis does not. Can you change EDDI it so we can use the beta version; or at least have the ability to choose which one we want to use? Thanks again for all the great work you do on EDDI!

**Comment by cmdrmcdonald** [comment]
EDDI already uses the EDCD version of coriolis.

**Comment by mikelimtw** [comment]
Sorry I used this function once when I first installed EDDI and I didn't notice it was already using the EDCD version. I just looked at your notes and it says coriolis.io. I assumed it was using the standard coriolis version. I only brought this up because I'm starting to do engineering and I like coriolis better than ED Shipyard. Anyway, thanks for the great work and the quick reply!

**Comment by mikelimtw** [comment]
Sorry my bad! I used this function once when I first installed EDDI and I didn't notice it was already using the EDCD version. I just looked at your notes and it says coriolis.io. I assumed it was using the standard coriolis version. I only brought this up because I'm starting to do engineering and I like coriolis better than ED Shipyard. Anyway, thanks for the great work and the quick reply!
