### ISSUE TITLE
Companion App Login Error

### ISSUE THREAD

**Issue by jdwardlaw** [cmdrmcdonald/EliteDangerousDataProvider#141]
Trying to log into Companion App and get the following error:

EddiCompanionAppService.EliteDangerousCompanionAppException: Failed to contact API Server
at EddiCompanionAppService.CompanionAppService.Login()
at EddiMainWindow.companionAppNextClicked(Object sender, RoutedEventArgs e)

Upgraded from version 1 to 2.2.0
Removed EDDI folder prior to installing
When I got the error I removed the credentials.json file but this did not fix the problem.

**Comment by cmdrmcdonald** [comment]
This sounds like you couldn't access the Frontier servers.  This does happen at times, but is usually intermittent.  Does this work now?

**Comment by jdwardlaw** [comment]
Hi,

Thanks for the reply. Sorry for the late response. I checked it out yesterday and you are correctI, it successfully connected.
Thanks. Excellent program.

John

Sent from my iPhone

On Mar 4, 2017, at 10:47 AM, cmdrmcdonald <notifications@github.com<mailto:notifications@github.com>> wrote:


This sounds like you couldn't access the Frontier servers. This does happen at times, but is usually intermittent. Does this work now?
