### ISSUE TITLE
Companion app login error

### ISSUE THREAD

**Issue by folkdeezy** [cmdrmcdonald/EliteDangerousDataProvider#142]
![screenshot - 3_1_2017 3_50_45 am](https://cloud.githubusercontent.com/assets/26109642/23452477/6df379e8-fe32-11e6-95eb-08ac73f61955.png)

**Comment by folkdeezy** [comment]
get this everytime i try to sign in now

**Comment by cmdrmcdonald** [comment]
This is generally an issue with the Frontier companion API, which sometimes stops working.  Is this working for you now?

**Comment by folkdeezy** [comment]
yes, thank you!

**Comment by RoundAbout2Space** [comment]
Same problem today (2017-4-4) 
Recieving code by email is -2h-1h between 6:57pm - 8:30pm 
Tried a few codes but recieved mails sometimes with earlier timestamp... lol

Looking forward to E:D 2.3 and all the updates that will follow... EDDI 3.0?
Thx for brill software! Thumbs up!
