### ISSUE TITLE
Sync with Inara.cz

### ISSUE THREAD

**Issue by sheazle** [cmdrmcdonald/EliteDangerousDataProvider#143]
@jtickle wrote a neat little app that syncs materials with Inara.cz. Problem is you have to run it each time you want it to update. https://github.com/jtickle/Picard

seems like this would be an ideal function for an EDDI module, it could update Inara in real time as materials are collected or used.

**Comment by Floppy** [comment]
Would be great to sync location, cash balance, ship, and so on as well, if possible. I don't know what Inara has in its API.

**Comment by AnthorNet** [comment]
Not to sell my own, but EDSM has all this API available already. No need to reinvent the wheel!

**Comment by Floppy** [comment]
Ah, so if the data is already being sent to EDSM, then it can carry on and sync from there to Inara? That would do the job.

**Comment by cmdrmcdonald** [comment]
As far as I can see Inara doesn't have an API.  Writing HTTP POSTs isn't a sustainable way of doing things.  If Inara provides an API then it shouldn't be hard to write a responder to send data to it.

As @AnthorNet points out, there are other solutions out there such as EDSM that do have APIs and so are easier to maintain.

**Comment by Floppy** [comment]
Ah, I thought Inara did. Sorry, my misunderstanding there.

**Comment by NevanNedall** [comment]
It would seem they do now. Perhaps something to revisit?
