### ISSUE TITLE
Implement Ship/Fleet Info for EDSM

### ISSUE THREAD

**Issue by rclough** [cmdrmcdonald/EliteDangerousDataProvider#144]
Switched from EDMC to EDDI recently, and thought it was updating all my EDSM stuff, but realized my fleet is way out of date, then saw this feature comparison:

https://www.edsm.net/en/faq

I didn't see any issues in the tracker WRT implementing any other EDSM features, so figured I'd open this one for updating the fleet.

Related Documentation: https://www.edsm.net/en/api-commander-v1#endPointUpdateShip

### Example implementation: EDMC (Python)

API Call: https://github.com/Marginal/EDMarketConnector/blob/master/edsm.py#L224-L229

Usage of the above api call (all same file, just different sections:
* [Main codeblock for updating ship info](https://github.com/Marginal/EDMarketConnector/blob/59e8e114a3d70fc0ec61e12007a6f45d3419d2fb/EDMarketConnector.py#L509-L540)
* [Block for startup, and buy/sell](https://github.com/Marginal/EDMarketConnector/blob/59e8e114a3d70fc0ec61e12007a6f45d3419d2fb/EDMarketConnector.py#L624-L636)
* [Paintjob change updates](https://github.com/Marginal/EDMarketConnector/blob/59e8e114a3d70fc0ec61e12007a6f45d3419d2fb/EDMarketConnector.py#L642-L644)

Unfortunately I've never done any windows development, otherwise I'd be happy to work on the PR myself.

**Comment by cmdrmcdonald** [comment]
This has been incorporated in to EDDI 2.3 (currently in beta).
