### ISSUE TITLE
EDDI now imports only 7 days of EDSM flight logs

### ISSUE THREAD

**Issue by adrianpetford** [cmdrmcdonald/EliteDangerousDataProvider#152]
With the EDSM API key entered, pressing Obtain log in EDDI will now only import the previous 7 days of flight logs from EDSM. This is due to a recent change by EDSM.

Info from AnthorNet of EDSM in response to my question about the issue:

"thx

yes i had to change how the get-logs api works to maintain performance across all users.
Now they can be retrieved by batch of one week. Make it easier then always grab more then 60k logs for some users !

You should ask EDDI developer to update. "

Forum posts in the threads for both tools:
https://forums.frontier.co.uk/showthread.php/294579-EDDI-Windows-app-for-immersion-and-more?p=5271095&viewfull=1#post5271095

https://forums.frontier.co.uk/showthread.php/179063-EDSM-Elite-Dangerous-Star-Map?p=5275674&viewfull=1#post5275674

EDDI versions affected: 2.2.0 and 2.2.1

Hope that helps.
Thanks for this brilliant app,
Adrian

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this.  This will be addressed in the next release.

**Comment by cmdrmcdonald** [comment]
The fix for this has been incorporated in to EDDI 2.3 (currently in beta).
