### ISSUE TITLE
Ship name becomes "TestBuggy" after loading game saved while in SRV then boarding the ship

### ISSUE THREAD

**Issue by wstephenson** [cmdrmcdonald/EliteDangerousDataProvider#153]
I think EDDI needs to try to figure out the correct Ship name again after the DockSRV event is seen. Ideally the DockSRV event would include the Ship/ShipID fields, but hey ho, this is what we've got

{ "timestamp":"2017-03-15T13:35:46Z", "event":"LoadGame", "Commander":"WSTEPHENSON", "Ship":"TestBuggy", "ShipID":47, "StartLanded":true, "GameMode":"Open", "Credits":78320046, "Loan":0 }
{ "timestamp":"2017-03-15T13:35:46Z", "event":"Rank", "Combat":4, "Trade":5, "Explore":8, "Empire":2, "Federation":5, "CQC":3 }
{ "timestamp":"2017-03-15T13:35:46Z", "event":"Progress", "Combat":40, "Trade":66, "Explore":100, "Empire":69, "Federation":39, "CQC":17 }
{ "timestamp":"2017-03-15T13:36:04Z", "event":"Location", "Docked":false, "StarSystem":"HIP 17862", "StarPos":[-81.438,-151.906,-359.594], "SystemAllegiance":"", "SystemEconomy":"$economy_None;", "SystemEconomy_Localised":"None", "SystemGovernment":"$government_None;", "SystemGovernment_Localised":"None", "SystemSecurity":"$SYSTEM_SECURITY_low;", "SystemSecurity_Localised":"Low Security", "Body":"HIP 17862 6 c a", "BodyType":"Planet" }
{ "timestamp":"2017-03-15T13:37:19Z", "event":"MaterialCollected", "Category":"Manufactured", "Name":"unknownenergysource", "Count":3 }
{ "timestamp":"2017-03-15T13:37:41Z", "event":"MaterialCollected", "Category":"Manufactured", "Name":"unknownenergysource", "Count":3 }
{ "timestamp":"2017-03-15T13:37:56Z", "event":"MaterialCollected", "Category":"Manufactured", "Name":"unknownenergysource", "Count":3 }
{ "timestamp":"2017-03-15T13:39:11Z", "event":"MaterialCollected", "Category":"Manufactured", "Name":"unknownenergysource", "Count":3 }
{ "timestamp":"2017-03-15T13:39:28Z", "event":"MaterialCollected", "Category":"Manufactured", "Name":"unknownenergysource", "Count":2 }
{ "timestamp":"2017-03-15T13:41:40Z", "event":"DockSRV" }

**Comment by cmdrmcdonald** [comment]
This is an issue due to the information provided in the companion API.  Elite 2.3 provides more information in the journal regarding current vehicle, and EDDI 2.3 will use this information to keep track of the ship more accurately.

**Comment by cmdrmcdonald** [comment]
The fix for this has been incorporated in to EDDI 2.3 (currently in beta).
