### ISSUE TITLE
Pass script variables to VoiceAttack

### ISSUE THREAD

**Issue by mikelimtw** [cmdrmcdonald/EliteDangerousDataProvider#154]
Hi CmdrMcDonald,

This is not an issue per se, but a question of how to do something. Let's say I create a script to check the remaining fuel. How do I transfer the value of a script variable to a variable I can use within VoiceAttack?

**Comment by cmdrmcdonald** [comment]
Cottle template have a SetState() function that will place variables in a shared space with both VoiceAttack and Cottle.  Details on the SetState() function are available in the Speech Responder template help file (available when editing templates) and details on how to use state variables in VoiceAttack are available at https://github.com/cmdrmcdonald/EliteDangerousDataProvider/blob/master/VoiceAttack.md#setstate
