### ISSUE TITLE
Enhancement: FuelScoop

### ISSUE THREAD

**Issue by mikelimtw** [cmdrmcdonald/EliteDangerousDataProvider#155]
Hi CmdrMcDonald,

The player journal has a FuelScoop even which calculates the amount of fuel scooped from a star and the total fuel after the scoop disengages. Can you add this information and associated variables for use in EDDI? This is useful for general traveling around the galaxy. Thanks!

**Comment by Darkcyde13** [comment]
This functionality is already in EDDI.  Here's the event script I use for refuelling:-

```
{_ Context}
{SetState('eddi_context_last_subject', 'refuelling')}
{SetState('eddi_context_last_action', 'complete')}
{SetState('eddi_context_fuel_remaining', event.total)}

{set fueltotal to ship.fueltanktotalcapacity}

{if event.source = "Market":
   {Occasionally(2,"{OneOf('{ShipName()}','Ship')}")}
   {OneOf("re-fuelled","fuel tanks topped up","tanks re-filled")}
   {Occasionally(3,"by {Humanise(event.amount)} tonnes")}
|else:
   {set total to (100/fueltotal)*event.total}
   {set amount to round((100/fueltotal)*event.amount,1)}
   {OneOf("{amount}% refuelled",
          "Refuelled by {OneOf('{amount}%','{Humanise(event.amount)} tonnes')}",
          "{OneOf('{amount}%','{Humanise(event.amount)} tonnes')} taken on board")}.
   {if total = 100:
      {Occasionally(2,"Main")}
      {Occasionally(2,"Fuel")}
      tanks at {OneOf("Maximum","100%")}
      {Occasionally(2,"capacity")}
   |else: {F("JumpFuel")}
   }
   {Occasionally(3,"{F('Honorific')}")}
}
.
```

Note: JumpFuel is a function I use to calculate the number of max range jumps available at the current fuel level.

**Comment by mikelimtw** [comment]
Hi Darkcyde13,

Thank you for your quick response! I understand what your codes does, even though I don't understand the proper format for writing Cottle code. However, I can use this to adapt some VA code to the Ship refulled event which will do essentially the same thing.  Thanks again!
