### ISSUE TITLE
[Feature Request] Galnet News language selection

### ISSUE THREAD

**Issue by Hotohori** [cmdrmcdonald/EliteDangerousDataProvider#156]
As far I know EddiGalnetMonitor.dll use the URL https://community.elitedangerous.com/galnet-rss what directly get redirected to https://community.elitedangerous.com/en/galnet-rss

When you change "en" to "fr" for example you get the france version: https://community.elitedangerous.com/fr/galnet-rss

When you change it to "de" you get the german version:
https://community.elitedangerous.com/de/galnet-rss

Don't know if there are other languages to, tested others but always get 404.

So it would be great if we could change the used language in the "Galnet monitor" Tab in EDDI, for example over radio buttons.

**Comment by Pryss** [comment]
Ooooh yes, it will be great.

By the way, it would be great to get the commodities in other langages than english if its possible. I'm using the franch version of the game and the French TTS, and getting the name of the commodities, materials and others will provide so much immersion.

**Comment by cmdrmcdonald** [comment]
The Galnet monitor has been updated significantly in EDDI 2.3 (currently in beta), including support for obtaining Galnet articles in different languages.

**Comment by Hotohori** [comment]
I can't find anything in the changelog? Many new stuff for GalNet, yes, but nothing about language support.
