### ISSUE TITLE
EDDI causes my voice attack subroutines to hang.

### ISSUE THREAD

**Issue by MagnumDopus** [cmdrmcdonald/EliteDangerousDataProvider#158]
![image](https://cloud.githubusercontent.com/assets/10997753/24133829/59a1c568-0dbd-11e7-85e2-2199164f01bd.png)

![image](https://cloud.githubusercontent.com/assets/10997753/24133840/738f8316-0dbd-11e7-87a2-ebbf1365f3df.png)

Running this command causes voice attack to hang, but only when I am using the EDDI plugin.  Also of note is my normal TTS through voice attack doesn't work (but using EDDI's say function does).

**Comment by cmdrmcdonald** [comment]
As EDDI isn't used in these commands this is most likely a VoiceAttack issue and one that should be raised on their forums.

**Comment by MagnumDopus** [comment]
Are you sure, when I enable EDDI as a plugin is when this fails.  I have narrowed down  the point of failure.  It only happens when a command in progress, in this case the computer subroutine is stopped.

**Comment by cmdrmcdonald** [comment]
I'm not sure, but have no way of looking inside VoiceAttack to see what's going on and if it is in any way interacting with the plugin list, what it might be doing, etc.  But given that EDDI runs in its own thread and doesn't respond to any VoiceAttack actions it is unlikely that EDDI is the root cause of any issue here.

**Comment by MagnumDopus** [comment]
Hmmmm, ok I guess I will raise it on the voice attack forum.

**Comment by MagnumDopus** [comment]
Just so you know, I figured out that checking the option under System/Advanced in voice attack labelled "Single TTS Instance" seems to solve this problem.  However this seems to make the say command only function sometimes... this is such a bizarre problem.

**Comment by cmdrmcdonald** [comment]
Are you using a Cereproc voice?  It's a known issue with VoiceAttack and Cereproc, there will be notes for it somewhere in the VoiceAttack help file.

**Comment by MagnumDopus** [comment]
I'm actually using Ivona.  Is there a gold standard voice?  I am not married to the Ivona voice I am using, and would be willing to use really anything as long as its consistent with EDDI.  The weird thing is, if execute a say plugin command inside a voice attack command, it fires 100% of the time.  But if I execute a say command wrapped within a conditional like so:

Begin Boolean Compare : [computer_spoken_to] Equals True
    Set Text [Script] to '[Still listening; still here; still waiting], [commander;];'
    Execute external plugin, 'EDDI 2.2.1'
Else
    Set Text [Script] to '[What can I do for you; yes; what do you need] [commander;]?;'
    Execute external plugin, 'EDDI 2.2.1'
End Condition

Such that no matter what it will always execute one of the two commands, for whatever reason, occasionally it just completely fails to say anything, even though to traverse that conditional it HAS to hit at least one.

**Comment by MagnumDopus** [comment]
@cmdrmcdonald I will link this voice attack issue thread so you can follow the issues here:  http://voiceattack.com/smf/index.php?topic=1017.0

The creator of VA seems to think this is an issue with EDDI but I suppose I will take the conversation there.
