### ISSUE TITLE
1.2.0 Unable to invoke plugin, also no configuration.exe

### ISSUE THREAD

**Issue by orgymeyer** [cmdrmcdonald/EliteDangerousDataProvider#16]
Hi there, been using EDDI for a few versions now. Updated tonight with the new version of EDDI for elite dangerous 2.1

However, after removing the old EDDI directory and doing a fresh install it's giving me the UNABLE TO INVOKE PLUGIN, PLUGIN NOT AVAILABLE  message as per usual.

So I went to go run configuration.exe, but file not found? It doesn't seem to exist in this release. The instructions on the page are for the old version of 1.1 and Voiceattack beta 1.5.8.16 (we are in beta 1.5.8.20 now)

Is configuration.exe the old way of doing things? New way to configure? Help please!

**Comment by orgymeyer** [comment]
Also reverting to my backup of EDDI and running configuration.exe gives the following message.

You need to re-run the configuration application.

So current version and previous version seem to not work anymore? I did the verbose logging entry in the Appconfig.xml and everything....

**Comment by cmdrmcdonald** [comment]
The issue with EDDI connection to the Elite servers was due to a problem with their API.  They have now fixed this so you should be able to connect.

I'm not sure why you aren't seeing a configuration.exe as it appears to be present in the current ZIP file:

    Archive:  EDDI.zip
      Length     Date   Time    Name
     --------    ----   ----    ----
        39424  05-19-16 12:39   EDDI/configuration.exe

**Comment by orgymeyer** [comment]
Awesome! I was downloading the wrong files apparently, just went to the github and downloaded current release as zip. This works better. Still having trouble when importing the file, I get errors and the profile shows up blank with an unhandled exception error. I'm using voiceattack beta 1.5.8.20. 
Here's the message I get when attempting to import the EDDI-Profile.vap

> Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately. 

> Sequence contains more than one matching element.

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at ..(CommandAction )
   at ..(CommandAction )
   at ..(Boolean )
   at ..()
   at ..(Object , EventArgs )
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at ..OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1076.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
VoiceAttack
    Assembly Version: 0.0.0.1
    Win32 Version: 1.5.8.20
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/VoiceAttack.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1075.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1067.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Speech
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Speech/v4.0_4.0.0.0__31bf3856ad364e35/System.Speech.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1080.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
{62fe19fd-98c8-4ae2-90a1-1e1fb870ef7c}
    Assembly Version: 0.0.0.0
    Win32 Version: 1.5.8.20
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/VoiceAttack.exe
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1067.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1067.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
CSCore
    Assembly Version: 1.1.5860.21642
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/backup%20of%20EDDI%201.0/CSCore.dll
----------------------------------------
EDDIVAPlugin
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/backup%20of%20EDDI%201.0/EDDIVAPlugin.dll
----------------------------------------
EliteDangerousCompanionAppService
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/backup%20of%20EDDI%201.0/EliteDangerousCompanionAppService.dll
----------------------------------------
EliteDangerousDataDefinitions
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/backup%20of%20EDDI%201.0/EliteDangerousDataDefinitions.dll
----------------------------------------
EliteDangerousDataProviderService
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/backup%20of%20EDDI%201.0/EliteDangerousDataProviderService.dll
----------------------------------------
EliteDangerousNetLogMonitor
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/backup%20of%20EDDI%201.0/EliteDangerousNetLogMonitor.dll
----------------------------------------
EliteDangerousSpeechService
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/backup%20of%20EDDI%201.0/EliteDangerousSpeechService.dll
----------------------------------------
EliteDangerousStarMapService
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/backup%20of%20EDDI%201.0/EliteDangerousStarMapService.dll
----------------------------------------
EntityFramework
    Assembly Version: 6.0.0.0
    Win32 Version: 6.1.40302.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/backup%20of%20EDDI%201.0/EntityFramework.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
EntityFramework.SqlServer
    Assembly Version: 6.0.0.0
    Win32 Version: 6.1.40302.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/backup%20of%20EDDI%201.0/EntityFramework.SqlServer.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.2.19309
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/backup%20of%20EDDI%201.0/Newtonsoft.Json.dll
----------------------------------------
RestSharp
    Assembly Version: 105.2.3.0
    Win32 Version: 105.2.3.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/backup%20of%20EDDI%201.0/RestSharp.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.99.0
    Win32 Version: 1.0.99.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/backup%20of%20EDDI%201.0/System.Data.SQLite.dll
----------------------------------------
System.Data.SQLite.EF6
    Assembly Version: 1.0.99.0
    Win32 Version: 1.0.99.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/backup%20of%20EDDI%201.0/System.Data.SQLite.EF6.dll
----------------------------------------
System.Data.SQLite.Linq
    Assembly Version: 1.0.99.0
    Win32 Version: 1.0.99.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/backup%20of%20EDDI%201.0/System.Data.SQLite.Linq.dll
----------------------------------------
System.Data.Entity
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.Entity/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Entity.dll
----------------------------------------
Xceed.Wpf.AvalonDock
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/Xceed.Wpf.AvalonDock.dll
----------------------------------------
Xceed.Wpf.AvalonDock.Themes.Aero
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/Xceed.Wpf.AvalonDock.Themes.Aero.dll
----------------------------------------
Xceed.Wpf.AvalonDock.Themes.Metro
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/Xceed.Wpf.AvalonDock.Themes.Metro.dll
----------------------------------------
Xceed.Wpf.AvalonDock.Themes.VS2010
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/Xceed.Wpf.AvalonDock.Themes.VS2010.dll
----------------------------------------
Xceed.Wpf.DataGrid
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/Xceed.Wpf.DataGrid.dll
----------------------------------------
Xceed.Wpf.Toolkit
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/Xceed.Wpf.Toolkit.DLL
----------------------------------------
UIAutomationProvider
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationProvider/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationProvider.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------
Xceed.Wpf.AvalonDock.resources
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/de/Xceed.Wpf.AvalonDock.resources.dll
----------------------------------------
Xceed.Wpf.AvalonDock.resources
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/es/Xceed.Wpf.AvalonDock.resources.dll
----------------------------------------
Xceed.Wpf.AvalonDock.resources
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/fr/Xceed.Wpf.AvalonDock.resources.dll
----------------------------------------
Xceed.Wpf.AvalonDock.resources
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/hu/Xceed.Wpf.AvalonDock.resources.dll
----------------------------------------
Xceed.Wpf.AvalonDock.resources
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/it/Xceed.Wpf.AvalonDock.resources.dll
----------------------------------------
Xceed.Wpf.AvalonDock.resources
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/pt-BR/Xceed.Wpf.AvalonDock.resources.dll
----------------------------------------
Xceed.Wpf.AvalonDock.resources
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/ro/Xceed.Wpf.AvalonDock.resources.dll
----------------------------------------
Xceed.Wpf.AvalonDock.resources
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/ru/Xceed.Wpf.AvalonDock.resources.dll
----------------------------------------
Xceed.Wpf.AvalonDock.resources
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/sv/Xceed.Wpf.AvalonDock.resources.dll
----------------------------------------
Xceed.Wpf.AvalonDock.resources
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/Apps/EDDI/zh-Hans/Xceed.Wpf.AvalonDock.resources.dll
----------------------------------------
VAJS
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.2
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/VAJS.DLL
----------------------------------------
SharpDX.DirectInput
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/SharpDX.DirectInput.DLL
----------------------------------------
SharpDX
    Assembly Version: 2.6.0.0
    Win32 Version: 2.6.0
    CodeBase: file:///C:/Program%20Files%20(x86)/VoiceAttack/SharpDX.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1055.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.1076.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1067.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.`

**Comment by orgymeyer** [comment]
Tested in Voiceattack beta 1.5.8.16 and 1.5.8.19 with the same issue, although now it's saying this as well on startup. Further investigation reveals there may be a conflict with Dot Net 4.0, which apparently Dot Net 4.5 doesn't have this issue with remote loading of DLL files.

> 9:17:10 PM - An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information. (joysticks disabled)

**Comment by orgymeyer** [comment]
Note that this happens when importing the VAP files for EDDI, but doesn't not occur in my homemade profiles. I tested importing one of my old profiles, no issues. Can't import the commands from EDDI into a new OR existing profile with the errors coming up. May be an issue with the way EDDI profiles are formatted. I tested old EDDI profiles from previous version that used to work fine with the same result.

Thinking there may be an issue with my voiceattack or possibly Dot Net so I'm reinstalling both of those from scratch now.

**Comment by orgymeyer** [comment]
Did the Dot Net fix tool, and then uninstalling and reinstalling voiceattack beta 1.5.8.21 (Just released) seems to have fixed it. Had to manually unblock the DLL files in the voiceattack directory to get it to read my joystick again, but after that it seems to be good to go. Going to test it in game now!
