### ISSUE TITLE
[Feature request]More ship status tokens

### ISSUE THREAD

**Issue by MagnumDopus** [cmdrmcdonald/EliteDangerousDataProvider#160]
I would love for more ship status information, such as tokens in VA for if my landing gear is extended, if my cargo scoop is deployed.

I would also love for a boolean token if the ship I am in contains a docking computer or not for better automated docking.

**Comment by cmdrmcdonald** [comment]
There is no information on status of landing gear, lights, scoop etc. available.

Regarding the docking computer, the ship's module names are available as "Ship compartment <n> module" (you can see these with ctrl-shift-alt-5) so you could scan these to see if one of them is a docking computer and react accordingly.
