### ISSUE TITLE
Cannot get voice attack to trigger speech responder.

### ISSUE THREAD

**Issue by MagnumDopus** [cmdrmcdonald/EliteDangerousDataProvider#161]
I am not super keen on how to get my voice attack to trigger a speech responder.  In fact I am having a hard time figuring out where to read documentation on the speech responder at all.  I understand that when a certain action is noted, the speechresponder will just do the TTS for you based on the script you provide it.  However I cannot for the life of me figure out how to set what triggers a specific speech responder script.  Are these hard coded?  If so how does creating a new script make much sense?  

Anyway, say I wanted according to the voice attack docs:  

```
This function uses EDDI's voice to read a Speech Responder script. The name of the script should be a text variable with the name 'Script'.

If you want to use a different voice to the standard one then you can set the name of the voice you want to use in a text variable with the name 'Voice'. Note that when you set this variable it will continue to be used until you unset it, at which point EDDI will use the voice configured in its text-to-speech settings.

To use this function in your own commands use the 'Execute an external plugin function' command with the plugin context set to 'speech'.
```

So I have tried to get a specific speech responder line to kick off.  For instance, when I scan a star I don't want EDDI to immediately tell me about it, but if I do want more information I want to be able to ask.  So in my voice command where I ask I have: 

```
Set Text [Script] to 'Star scanned'
Execute external plugin, 'EDDI 2.2.1'

```

And I am executing the function 'speech' in teh external plugin call.  However it will not execute the "Star scanned" speech responder script, I hear nothing.  Do I have a fundamental misunderstanding?

**Comment by cmdrmcdonald** [comment]
It sounds like you have things set up properly but hard to tell without looking at the VoiceAttack command itself.  Please could you export the command from VoiceAttack and attach the .vap file here?

**Comment by MagnumDopus** [comment]
[speechresponder-Profile.zip](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/files/861783/speechresponder-Profile.zip)

There is a profile with my one speech responder commander.  My speech responder is just using the default personality so everything is enabled.  

Also can you quickly explain how triggers are established.  I am quite confused by that.  If I click on the "entered signal source" responder command I see the following:

![image](https://cloud.githubusercontent.com/assets/10997753/24203965/541517ea-0ed4-11e7-80a3-7ca451c2c388.png)

Now I understand how it generates the response, I looked up the references you have added on how to construct these responses.  What I am having a hard time grasping is how a particular speech responder script is triggered.  The description for this is that it is triggered when entering a signal source, but I don't know where or how that is set.  Is it merely hard coded?  And if it is how do you go about establishing a new trigger for creating a new script?

**Comment by cmdrmcdonald** [comment]
The VoiceAttack profile provided works okay on my system.  What version of VoiceAttack are you using?

Regarding events, the graphic at https://github.com/cmdrmcdonald/EliteDangerousDataProvider shows the basics of how EDDI works.  Events are triggered by monitors that watch the journal log, galnet feed, etc.  The responders receive the events and act on the information provided.  In the case of the speech responder it looks for a template with the same name as the event, and if found it feeds it to the speech processor.

You can add your own scripts and call them from VoiceAttack.  If you have more complex requirements you'd probably have to build an EDDI plugin to generate events.

**Comment by MagnumDopus** [comment]
I am using the latest version of VA: v1.6.2.  I am scratching my head on this one.  You just loaded the profile I gave you and BAM, it just worked.... hmmmm.  

Also when I open EDDI it says "close this window when VA is running, you can configure it inside by running "configure EEDI".  But I cannot figure out how to access "configure EDDI".  Running it as an external plugin function doesn't seem to open the configuration prompt.

Is there a list of events that all the different responders generate anywhere?  I cannot seem to find it.

**Comment by cmdrmcdonald** [comment]
There is a VoiceAttack profile for EDDI in the installation directory, you can install that for the 'Configure EDDI' command and a few others.

The documentation at https://github.com/cmdrmcdonald/EliteDangerousDataProvider/blob/master/VoiceAttack.md#using-eddi-with-voiceattack provides a list of all current events, or you can look at the speech responder in-game as that will generate an entry for every known event.

**Comment by MagnumDopus** [comment]
Oh ok I didn't realize the name of the speech was a trigger lookup as well, everything is starting to make sense.  I will go home and try the profile ASAP, (ETA ~3 hours).  Hopefully it works but I suspect it won't.  I'll post once I know.  Thank you so much for the help.

**Comment by MagnumDopus** [comment]
I restarted my machine and now running the speech command does appear to be working.  Thank you for the help and further explanations.

**Comment by MagnumDopus** [comment]
One more thing, as I notice there are only a few trigger functions in the voice attack profile, some are missing.  When you say look at the speech responder in-game, do you just mean look at the configuration and all of teh triggers will be listed under the EDDI personality?
