### ISSUE TITLE
EDDI stopped working windows

### ISSUE THREAD

**Issue by ardrethol** [cmdrmcdonald/EliteDangerousDataProvider#162]
Help, program was running fine, until i messed with the netlog monitor, now everytime i start the program i get the default windows program stopped working. close program.
I have uninstalled and reinstalled the program with no effect, i totally beleive this is my doing testing entering the path manually rather than "obtain" (If its not broke, dont fix it). Using the program with EDSM and EDDB the last week and find it very ermersive, lost without it..........

**Comment by cmdrmcdonald** [comment]
Try removing %APPDATA%\EDDI\netlog.json this will remove the netlog configuration and should allow you to restart EDDI.

**Comment by ardrethol** [comment]
Thanks for the speedy reply,  found the files earlier in appdata roaming EDDI deleted them all and reinstalled and it worked.

**Comment by cmdrmcdonald** [comment]
Good ti hear that it's working.

**Comment by Strax15** [comment]
Thank you for the quick response. I was also having the same issue and as Ardrethol noted, it was under user\appdata\roaming\eddi. just deleting the netlog.json was enough and no reinstall required (yet). Thank you again!
