### ISSUE TITLE
export to Coriolis only works on 1 ship

### ISSUE THREAD

**Issue by testuser26** [cmdrmcdonald/EliteDangerousDataProvider#164]
For some reason of my entire fleet, only 1 ship - my Sidewinder does "Export to Coriolis" works.  On other ships a web page gets loaded but it doesn't go to Coriolis.  It just loads the default page for the browser.

**Comment by cmdrmcdonald** [comment]
What is your default browser set to?  There have been issues with Internet Explorer and Edge due to them truncating URLs.

**Comment by testuser26** [comment]
that could definitely be the problem!  I have to have IE as my default browser for something else.

Any chance you can make the link copyable to the clipboard?  maybe with a right-click or something?  or just a list where it can be selected and copied?

**Comment by cmdrmcdonald** [comment]
You can set a boolean variable in VoiceAttack 'EDDI use clipboard' to true (if you are using VoiceAttack that is), but from what I remember you'll have the same problem.  The best solution is to use Chrome/Firefox/general-non-Microsoft browser as they don't put this limitation in place.

**Comment by EireEngr** [comment]
This is happening to me now as well since the last update, the one that fixed the 2.3 Glitches.  I am using Firefox as my primary, and I have 3 ships.  For some reason my Asp X was the only one that would export.
