### ISSUE TITLE
"Explorer" Exploration Ranking

### ISSUE THREAD

**Issue by The1AndMany** [cmdrmcdonald/EliteDangerousDataProvider#165]
At present, the 5th exploration ranking (if Aimless is 1) as called by the `{cmdr.explorationrating.name}` function is titled "Explorer". This is incorrect, as the actual name for this rank should be "Trailblazer". The incorrect naming appears in the source code in `/DataDefinitions/ExplorationRating.cs`, but I don't know if it's mentioned anywhere else, such as the ED API.

I'd fork and correct this myself, but I'm not sure how delicate the code is and I don't trust myself not to break it. (I'm a bit of a greenhorn...)

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this.  It has been fixed and will be available in the next release of EDDI.

**Comment by cmdrmcdonald** [comment]
The fix for this has been incorporated in to EDDI 2.3 (currently in beta).
