### ISSUE TITLE
'earthmass' not populated for the BodyScannedEvent

### ISSUE THREAD

**Issue by andre-arsenault** [cmdrmcdonald/EliteDangerousDataProvider#166]
I am making a voice responder that outputs the approximate value of a scanned body (and star) but discovered that the 'earthmass' property is not set in response to the Body Scanned event.

I made some local code changes to get it to work but I noticed you've made significant changes since the last public release - so I'm not sure my changes would be of much help to you as a pull request since they're pretty trivial.

I am using the scan values from [this wikia page](http://elite-dangerous.wikia.com/wiki/Explorer), which depends on 'earthmass' for identifying tiny/medium/huge bodies.

**Comment by cmdrmcdonald** [comment]
This property isn't listed in the Frontier journal reference.  Do you have a journal entry for a planet that shows this value?

**Comment by andre-arsenault** [comment]
It's called "MassEM" in the journal entry and they provide an example in the Frontier journal reference under section 6.1. EDDI defines the property "earthmass" in DataDefinitions/Body.cs which is exposed to the templating language, but that field is never populated.

I can send you an example and a pull request with my local changes when I'm back at my home PC this evening.

**Comment by andre-arsenault** [comment]
Attached a patch of my changes and a journal log with a few sample scan events.

Cheers!

[earthmass-patch.zip](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/files/873214/earthmass-patch.zip)
[Journal.170325133214.01.log.zip](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/files/873217/Journal.170325133214.01.log.zip)

**Comment by cmdrmcdonald** [comment]
Thank you for the logs.  I've added earthmass (and radius) to BodyScanned; they will be available in the next release.

**Comment by andre-arsenault** [comment]
Perfect, thanks!

**Comment by andre-arsenault** [comment]
These new properties haven't been included in the last two releases. Can you please include these changes into the next release?

**Comment by cmdrmcdonald** [comment]
Sorry should have said next *major* release.  The patch releases in the 2.2 series are just fixes rather than new features.

**Comment by cmdrmcdonald** [comment]
These properties are present in EDDI 2.3 (currently in beta).
