### ISSUE TITLE
Docking Completed/Ship change event not working.

### ISSUE THREAD

**Issue by MarkAusten** [cmdrmcdonald/EliteDangerousDataProvider#17]
The docking completed/ship change events do not seem to be working. Invoking the VA command that posts an event to EDDI runs but the subsequent calling of the VA event handler for each of these events is not called.

As a workaround I've copied the event handler code to new commands and called those instead of the supplied VA command.

**Comment by cmdrmcdonald** [comment]
There is a known issue with VoiceAttack where it shuts down the event loop if you edit the profile.  Does this still happen when you start VoiceAttack fresh?

And just to confirm, you are saying "I have docked" or similar when the docking is complete?  The docking action is not automatic as there is nothing written to the netlog that we can use to know when docking has occurred.

**Comment by MarkAusten** [comment]
I had found the edit/shutdown problem and this was not it. And to confirm, I was triggering the docking VA command with a keypress that I added to the 'I have docked' and 'ship changed' voice commands.

Since I reported this I have upgraded to the latest VA and noticed that docking and ship change events sometimes work. There can be a delay of up to 10 minutes before the expected response from the VA/EDDP combination so I have stopped using these two event command for the time being.

Most odd. It is quite disconcerting to be jumping to the next system and have VA report that there is nothing to be saved by swapping modules here instead of when the command was triggered!

**Comment by cmdrmcdonald** [comment]
I've heard of this problem from a few sources now.  I suspect that it's due to a timeout in one of the network requests, so I've added a 10-second timeout for all HTTP requests.

Does the problem happen at any particular times?  If you want to try the version with the timeouts you can pull it from http://www.mcdee.net/elite/EDDI-1.2.1d2.zip and see if it fixes the problem.

**Comment by MarkAusten** [comment]
I've installed the new version from your link and I'll let you know how it goes this evening after I've had a chance to play Elite for an hour or two.

**Comment by MarkAusten** [comment]
Okay, the update appears to be working in that the reposes to docked and handover now occur as expected however, the first time the docked command is triggered it reports the last station not the current station. Triggering the VA command again reports the correct station.

The handover command reports the last ship name and not the current ship name. Repeated triggering of the VA command does not affect this, it gets it wrong all the time. Shutting VA down and trying again seems to get the correct name.

**Comment by MarkAusten** [comment]
I played Elite for a few hours last night and EDDI behaved perfectly. I had to uninstall and reinstall VA as it was corrupted by a ransomware trojan and after that everything worked as expected with v1.2.1d2.

Many thanks.
