### ISSUE TITLE
Possible enhancement: Add Coriolis shortlinks to the shipyard?

### ISSUE THREAD

**Issue by Tkael** [cmdrmcdonald/EliteDangerousDataProvider#170]
"Send this ship to Coriolis" has not been working for me. (Possibly due to my default browser not being compatible... I'm not sure... I'm using Chrome). I hear the message that the information is being sent but it does not appear in my browser.

Would it be possible to add a shortlink or button in the shipyard to give us a second way to access this feature?

Thanks!

**Comment by Darkcyde13** [comment]
There is a button in EDDI Shipyard already.  It says "Export to Coriolis" at the right hand side, next to the "Hear it" button.

**Comment by Tkael** [comment]
Ah. I guess I spoke too soon.
Also, I think I figured out the issue with the "send to Coriolis" function not working in VoiceAttack... the companion app API dropped my credentials. I had to re-enter them.
