### ISSUE TITLE
Variable System main star stellar class isn't always populated

### ISSUE THREAD

**Issue by mikelimtw** [cmdrmcdonald/EliteDangerousDataProvider#172]
Hi Cmdr McDonald,

I've been playing around with local system info and I found that during a jump when I go to access the variable System main star stellar class about 70% of the time it returns "Not set" and only seems to be populated about 30% of the time.

Is this an issue within EDDI? I don't think it's a problem within Elite updating this information since the stellar class of a star system you are jumping to is already shown in the info box in the upper right when you begin a jump to the next system.

**Comment by cmdrmcdonald** [comment]
The value is not present in the journal in Elite 2.2, but will be present in Elite 2.3.  The next version of EDDI after Elite 2.3 is released will take the value from the journal and so this information will be more easily available.

**Comment by mikelimtw** [comment]
I found a workaround for the moment. If I place a 2 or 3 second pause before the jumping responder fires, that seems to fix the problem.
