### ISSUE TITLE
More details on how to interact with modules?

### ISSUE THREAD

**Issue by Tkael** [cmdrmcdonald/EliteDangerousDataProvider#174]
Would you please expand the documentation on how to query and get information from modules?

For example:
- I'd like to get details about the engine recharge rate and capacity from my power distributor (it's engineered, so getting the class & grade is not sufficient). 
- With that information, I could calculate the time required to recharge my boost and send commands to boost that are timed to the ship that I am flying.

How can I discover the details that are contained within the module object for my power distributor? EDDI is able to pass the information to Coriolis, but I don't know how to drill down and extract that level of detailed information via Cottle.

**Comment by cmdrmcdonald** [comment]
EDDI does not contain the module information that you require.  It is limited to names, values and health of modules.  EDDI does hold the raw information for modified modules but it does not parse it in any way, as the data provided by Elite requires a significant amount of manipulation to provide any useful value.

Although it would be possible to provide this depth of information it would be a large and complex undertaking and isn't something that I'm looking to add to EDDI myself.
