### ISSUE TITLE
Body Report - Retrograde body motion

### ISSUE THREAD

**Issue by Darkcyde13** [cmdrmcdonald/EliteDangerousDataProvider#176]
Hi,

While out exploring, I've found that the Body Report can be incorrect for bodies that have retrograde motion (reverse spin).  For example if a body has a spin of -45 days, the current body report states this as a fast rotational period, when in fact it is a slow rotational period, it's just in reverse.  The section of code that handles this can be fixed with the following :-

```
    {if reportbody.landable:
        It has a
        {if reportbody.rotationalperiod < -20.0:
            slow retrograde
        |elif reportbody.rotationalperiod < -0.5:
            retrograde
        |elif reportbody.rotationalperiod < 0:
            fast retrograde
        |elif reportbody.rotationalperiod <= 0.5:
            fast
        |elif reportbody.rotationalperiod > 20.0:
            slow
        }
        rotational period of {Humanise(reportbody.rotationalperiod)}
        day{if Humanise(reportbody.rotationalperiod) != "1":s}.
```
(The last line also fixes a rotational period of one day being said as "one days").

Hope you find this useful. Keep up the great work Cmdr! :)

Darkcyde.

**Comment by cmdrmcdonald** [comment]
Thank for for supplying this change.  It has been incorporated in to EDDI 2.3 (currently in beta).
