### ISSUE TITLE
API Login 

### ISSUE THREAD

**Issue by bradsr132** [cmdrmcdonald/EliteDangerousDataProvider#177]
I had a few problems with Eddi and I uninstalled, tried to re install and will not login to API I have tried it numerous times and continue to get message Unexpected problem  Please report to github

EddicompanionAppservice.eliteDangerousCompanionappException: Failed to obtain data from frontier server (NEEDS _LOGIN)
	At EddiCompanionAppService.Companion.CompanionAppService,Profile(Boolean forceRefresh)
	At Eddi.MainWindwo.companionAppNextClicked(Object sender, RoutedEventArgs e 

Thank you Commander McDonald

**Comment by Darkcyde13** [comment]
The Elite servers have been offline for a few hours for the 2.3 patch update.  It's possible this is why you have been having trouble logging in the API.  Now that the patch has completed, try again. :)

**Comment by cmdrmcdonald** [comment]
This should now be working with EDDI 2.2.3

**Comment by bradsr132** [comment]
thank you........working once again....
