### ISSUE TITLE
API Login Failure

### ISSUE THREAD

**Issue by KellyRayburn** [cmdrmcdonald/EliteDangerousDataProvider#178]
I get the message described in the screenshot  below when I try to login to the API.

![eddi 4_11_2017 12_32_45 pm](https://cloud.githubusercontent.com/assets/15879930/24922602/87ccb9c2-1eb4-11e7-8eb7-5055d8b79f85.png)

**Comment by shingoku** [comment]
same problem

**Comment by c0dejunKie** [comment]
same here...

**Comment by mikelimtw** [comment]
Yep same problem here too

**Comment by TomasEkeli** [comment]
Until a new release is made you can drop in a replacement-file for the CompanionApp -library as described in the readme in this zip: https://www.dropbox.com/sh/kvevq3u9qbi9mm5/AAAHgcMdqmLh7sR4ZSbJOuQba?dl=0&preview=EDDI_commanders_fix.zip

**Comment by cmdrmcdonald** [comment]
Fixed with 2.2.3
