### ISSUE TITLE
Stored ships and other Shipyard variables not set

### ISSUE THREAD

**Issue by SavageCore** [cmdrmcdonald/EliteDangerousDataProvider#18]
`{INT:Stored ships}` returns 0 when I have 5 ships total, 1 stored at my current station. 

EDDI configuration shipyard tab only detects current ship.

If I use E:D Market Connector and go to File > Status > Ships I see my 5 ships and their locations fine so Companion API seems to be working correctly. Here is a recent EDDI.log:

[EDDI.txt](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/files/301418/EDDI.txt)

Any ideas here?

**Comment by cmdrmcdonald** [comment]
The data seems to parse okay so I suspect that it might be a problem with the local EDDI info.  Please could you send me a copy of your ships.json from %APPDATA%\EDDI so that I can take a look at it?  Thanks.

**Comment by SavageCore** [comment]
Sure!

[ships.json](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/files/301525/ships.txt)

**Comment by cmdrmcdonald** [comment]
Thanks for the files.  I believe that I've found the issue but please could you try the version of EDDI at http://www.mcdee.net/elite/EDDI-1.2.1d1.zip and see if it results in showing your ships?

**Comment by SavageCore** [comment]
That works great. Thank you!

**Comment by MarkAusten** [comment]
SavageCore, would you close the issue if it is resolve, please.

Thanks,
