### ISSUE TITLE
can't log into companion app since Elite 2.3 download

### ISSUE THREAD

**Issue by Smash-Time** [cmdrmcdonald/EliteDangerousDataProvider#183]
I downloaded elite dangerous v2.3 (multicrew) today and and have not been able to get EDDI v2.2.2 to work. Initially EDDI simply would not run either standalone or via Voice Attack. After uninstalling EDDI and reinstalled it, it runs but when I tried logging into Frontier via the companion app tab I received a microsoft runtime error. See attached screenshot.

![screenshot 2017-04-11 22 31 20](https://cloud.githubusercontent.com/assets/26714560/24940510/23cc504a-1f09-11e7-895e-d16e95f89bf1.jpg)

**Comment by xpara** [comment]
Same exact issue for me here as well.

**Comment by DrakeXIIIE** [comment]
Same problem.   I'd previously installed 2.2.2 but had not yet updated to ED 2.3 -- everything worked fine.

After updating to 2.3 I noticed EDDI wasn't working (I use it via VA) and after rebooting I tried launching EDDI which caused a windows error ("EDDI.exe has stopped responding"): deleting credentials.json (from appdata) fixed that, but when I attempted to re-sign in to the Companion App I got the above error.

Don't know if its relevant, but while I was exploring new features in 2.3 I created a holo-me avatar and assigned names and tail numbers to my ships.

**Comment by JaskoMaughann** [comment]
Identical error here following upgrading Elite: Dangerous to 2.3 and EDDI to 2.2.2.
I'm also running Voice Attack, Discord and EDTracker alongside it.

**Comment by Rodasson** [comment]
After the error and closeing the program EDDI can´t even be reopened again ...

**Comment by Darkcyde13** [comment]
Please don't open separate issues for ones that already exist. This is a duplicate issue of #179. This is due to ED Horizons 2.3 App changes.
