### ISSUE TITLE
Failed to log into ED account for ship data

### ISSUE THREAD

**Issue by Killikhivemind** [cmdrmcdonald/EliteDangerousDataProvider#190]
![eddierrorreport](https://cloud.githubusercontent.com/assets/27539902/25061031/6b4f9aec-2172-11e7-8f18-6563eeb1705e.png)

**Comment by mikelimtw** [comment]
Please upgrade to 2.2.3 version of EDDI. FDev changed the Companion App API and older versions of EDDI won't work anymore.

**Comment by cmdrmcdonald** [comment]
Please try removing %APPDATA%\EDDI\credentials.json and see if this fixes your issue.
