### ISSUE TITLE
EDDI New Version issue

### ISSUE THREAD

**Issue by RedBaron1947** [cmdrmcdonald/EliteDangerousDataProvider#191]
Hi, 
Just installed V2.2.3 and for some reason it will not work please advise. My voice attack also stops working but when I uninstall EDDI, voice attack is fine
![new eddi](https://cloud.githubusercontent.com/assets/20424977/25062587/b2ab095e-21c6-11e7-9b81-b707ce3dc3c7.png)

**Comment by cmdrmcdonald** [comment]
Please can you attach or send the contents of %APPDATA%\EDDI\eddi.log

**Comment by RedBaron1947** [comment]
Hi,

I have solved my issue, just before reading your email. The problem was my Eset, my virus scanner, it needed to be paused whilst installing EDDI. Many thanks anyway.

 

Red Baron1947

JM.

**Comment by Darkcyde13** [comment]
That's interesting.  I've got ESET NOD32 antivirus on my machine too, and I've never had it interfere with installing EDDI (or anything else, thinking about it).
