### ISSUE TITLE
New-ish events not working

### ISSUE THREAD

**Issue by Komoluna** [cmdrmcdonald/EliteDangerousDataProvider#194]
Triggering a voiceattack command using the journal files ((EDDI <event name>)) doesn't work with the new-ish event like "JetConeBoost".

**Comment by cmdrmcdonald** [comment]
A number of new events are present in EDDI 2.3 (currently in beta).  If there are any specific messages missing please raise an issue for each of them so that they can be addressed individually.  Thank you.
