### ISSUE TITLE
Shipname() blank if no name assigned

### ISSUE THREAD

**Issue by Darkcyde13** [cmdrmcdonald/EliteDangerousDataProvider#197]
Hi,

I have noticed that when entering supercruise or normal space that my ship name is no longer being spoken.

Specifically, as I'm out of the bubble I have not been able to give my ship a name yet, and the EDDI Ship Monitor has wiped out my given names (understandably, as none have been assigned in-game).  Consequently, as I have no assigned name, Shipname() no longer reports anything at all.  Reading the Help section, I believe this should at least say 'Your Ship' if no name is found.

For the moment, I have edited my event scripts to compensate for the empty Shipname() with the following:-
`{OneOf("{if Shipname(): {Shipname()} |else: Your {ship.model} } has", "")}`

This works well for me, saying "Your Asp Explorer has...".

Kind regards,

Darkcyde.

**Comment by cmdrmcdonald** [comment]
The Cottle function is ShipName() (note the upper-case N).  If you don't have a ship name then it should return 'Your ' plus the model of your ship.  If this is not the case please let me know.

**Comment by Darkcyde13** [comment]
Doh! Me being blind again.  Of course it is ShipName().  I even have it correct in my old 2.2.3 versions, I just re-typed it wrong for 2.3.0.  It was late last night, I guess I was more tired than I thought.

Thank you for pointing out my mistake. :) Corrected and working as expected.  Apologies for reporting something that was my fault.

Darkcyde.
