### ISSUE TITLE
Beta 2.3b1 bug: 'Test script' button only works sometimes

### ISSUE THREAD

**Issue by Tkael** [cmdrmcdonald/EliteDangerousDataProvider#199]
The 'Test script' button does not appear to work on some scripts.

To replicate:
1. Generate a new personality.
2. Generate a new script. Call it anything you'd like.
3. Write anything in the body of the script. For example, "test" or "testing". Something that shouldn't run into any issues being converted to speech.
4. Hit the 'Test script' button. Nothing happens (at least for me). Text copies of the speech are not written to %APPDATA%\EDDI\speechresponder.out when that option is checked.

I've confirmed that TTS is enabled and working. Some scripts seem to work (for example, 'Undocked') while others do not output anything.

**Comment by cmdrmcdonald** [comment]
This should be fixed in 2.3 beta 2.
