### ISSUE TITLE
Enhancement - Read from log when you are docked or landed, or not

### ISSUE THREAD

**Issue by Uriei** [cmdrmcdonald/EliteDangerousDataProvider#20]
I've been reading raw netlogs and saw there are new lines when you dock or land on ground, could someday EDDI read those lines and stop needing to tell the plugin when you docked your ship?

The lines I saw are
`Commander Put Docked`
`Commander Put Undocked`
and
`GetSafeUniversalAddress Station Count ? moved ? Undocked Not Landed`
`GetSafeUniversalAddress Station Count ? moved ? Docked Not Landed`
`GetSafeUniversalAddress Station Count ? moved ? Undocked Landed`
where ? are variable numbers, don't know what they mean.

**Comment by cmdrmcdonald** [comment]
The data in the logs is for all ships in the instance and cannot (as far as I am aware) be reduced to just the player's information.  As such it's not possible to use this info for automating these activities.
