### ISSUE TITLE
Fuel scooping triggers Ship Refuelled multiple times

### ISSUE THREAD

**Issue by Darkcyde13** [cmdrmcdonald/EliteDangerousDataProvider#202]
Hi,

I've found that fuel scooping can trigger the Ship Refuelled event multiple times during a single scooping session.  It seems that the Journal records the scooping in (roughly) 5 tonne intervals, which kicks off the event each time.  Here's an excerpt from my testing last night:-

```
{ "timestamp":"2017-04-19T22:20:02Z", "event":"FuelScoop", "Scooped":5.003216, "Total":22.701246 }
{ "timestamp":"2017-04-19T22:20:15Z", "event":"FuelScoop", "Scooped":5.000847, "Total":27.702089 }
{ "timestamp":"2017-04-19T22:20:29Z", "event":"FuelScoop", "Scooped":4.297902, "Total":32.000000 }
```

As you can see, these are about 13-14 seconds apart, and roughly 5 tonnes each.  This was a single scooping session with a 6C fuel scoop, not maxing out the scoop rate.  I may try to run my tank nearer to empty and go for a longer scoop at max rate and see what the results are.

I'm not sure if you can record these and report the added totals at the end, say if no scooping entries for 20 seconds or something.  However, if it's based on 5 tonne intervals, then it would depend heavily on the rate at which you can scoop; a lower scoop rate would mean a longer time interval.

I can't immediately see an easy way around this, but maybe you can come up with something?  I'll keep thinking about it and maybe I'll get some bright idea to suggest. :)

Darkcyde.

**Comment by cmdrmcdonald** [comment]
This isn't the type of thing that I'm prepared to take on in EDDI.  The change from a single entry to multiple entries for the same event should be raised as a bug with Frontier so that they can fix it at source.
