### ISSUE TITLE
EDSM plugin

### ISSUE THREAD

**Issue by ratcom** [cmdrmcdonald/EliteDangerousDataProvider#203]
Noticed since 2.3 dropped and a clean install of EDDI my EDSM will not work in both directions (importing and exporting to the site) I get no error messages and when I press "obtain log" within a second this reports back "obtained" (it used to take several minutes)

running beta 2.3.0-b3

**Comment by cmdrmcdonald** [comment]
Can you confirm that your EDSM API key and commander name are set correctly?  I just tried this with a clean install of EDDI and it worked.

If it still isn't working then please enable verbose logging in EDDI, hit the "Obtain log" button in the EDSM responder and when it's finished upload the logs.

**Comment by ratcom** [comment]
strange my key is correct (reset it just to make sure) I've sent a log as per requested.

**Comment by AnthorNet** [comment]
Might be our API onky giving by 7 days interval?

**Comment by cmdrmcdonald** [comment]
The error from EDSM is "Commander name/API Key not found" so it suggests that either the key is incorrect or your commander name does not match up with your name in EDSM.  Could you confirm that your name in the EDSM responder panel (or that in Elite itself) matches up with your commander name as set in EDSM?

**Comment by ratcom** [comment]
just uninstalled due to the app being on a different drive to c , reinstalled onto c drive with no change :(

**Comment by ratcom** [comment]
holly crap I'm a fool !!!!! It works when I put my name in the correct field! omg I'm so sorry

**Comment by ratcom** [comment]
got them mixed up for some reason

**Comment by ratcom** [comment]
confirmed working, really sorry and honestly thank you for providing THE best tool for elite
