### ISSUE TITLE
Beta bug - 'Compare to default' causes EDDI to crash

### ISSUE THREAD

**Issue by Tkael** [cmdrmcdonald/EliteDangerousDataProvider#209]
When I've modified the script and then hit 'compare to default'.
Frustratingly, it doesn't happen every time and I'm been unable to identify a pattern as to when it occurs.

**Comment by Darkcyde13** [comment]
Yeah, I've had this happen too.  And like you, I've not been able to make it happen with any certainty.  It just seems random.  Sometimes it's happened without any modifications to a default script (I accidentally clicked it).  Thankfully I don't use this feature very often, and I've taken to saving before I do now.

**Comment by cmdrmcdonald** [comment]
This should be fixed in 2.3.0-b7.
