### ISSUE TITLE
Unable to invoke plugin loop

### ISSUE THREAD

**Issue by BarbsLDSR** [cmdrmcdonald/EliteDangerousDataProvider#21]
When I import the profile VoiceAttack runs a loop of the event *Not Set UNABLE TO INVOKE PLUGIN. PLUGIN NOT AVAILABLE.

I have installed per the instructions.
Have VoiceAttack 1.5.8.27
Have enabled plugin support.
Profile is set to run EDDI: startup.

**Comment by cmdrmcdonald** [comment]
Please check your configuration against the [troubleshooting guide](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/blob/master/TROUBLESHOOTING.md) and if there is still a problem then please open a new issue with your eddi.log so that I can provide you with more assistance.
