### ISSUE TITLE
Test data for Mission Accepted missing?

### ISSUE THREAD

**Issue by Darkcyde13** [cmdrmcdonald/EliteDangerousDataProvider#210]
Hi,

I've just upgraded to beta 6, and when clicking the Test button for Mission Accepted. it just says "Mission for accepted."  This used to say "Mission for Mafia of Cavins accepted."  Is this change intended, or is this a bug?  I've also tried Mission Completed and that seems to missing it's test data too.  Not sure if other events are missing anything, but I've tried a couple of others like Body Scanned and Bond Redeemed, and they are working fine with their test data.  This is with the default EDDI personality.

Kind regards,

Darkcyde.

**Comment by Darkcyde13** [comment]
Having just accepted a couple of missions, the Mission Accepted event isn't being triggered at all. I'm guessing this has something to do with the missing test data also.

**Comment by cmdrmcdonald** [comment]
This should be fixed in 2.3.0-b7.
