### ISSUE TITLE
Error accessing sound file. [Path error]!

### ISSUE THREAD

**Issue by incryptx** [cmdrmcdonald/EliteDangerousDataProvider#215]
Hello

In testing my three voice profiles, all worked until I called Vega and asked "what is your name?" for which there was no reply, but instead, a path error to CLEO, which I do not own.

Thanks 
------------------------------------------------------------------------------------------------------------
17:44:01 - Recognized : 'vega'
17:43:57 - Error accessing sound file - C:/Program%20Files%20(x86)/VoiceAttack/Sounds/hcspack-CLEO/Role/I%20am%20known%20as.wav
17:43:57 - Recognized : 'what is your name'
17:43:52 - Error accessing sound file - C:/Program%20Files%20(x86)/VoiceAttack/Sounds/hcspack-CLEO/Role/My%20name%20is.wav
17:43:52 - Recognized : 'what is your name'
17:43:49 - Recognized : 'vega'
17:43:23 - Recognized : 'what is a black hole' (derived command)
17:43:19 - Recognized : 'vega'
17:42:53 - Recognized : 'what is a black hole' (derived command)
17:42:43 - Recognized : 'midnight'
17:42:39 - Recognized : 'hello vega'
17:42:36 - Recognized : 'vega'
17:42:33 - Recognized : 'vega'
17:42:05 - Recognized : 'astra'
17:42:00 - Recognized : 'midnight'
17:41:56 - Recognized : 'vega'
17:39:14 - Welcome to HCS Voicepacks Multi-Crew Profile for Elite:Dangerous by CMDR TheThingIs (v2.2b)
17:39:14 - (c)2017 HCS Voice Packs Ltd
17:39:14 - You currently have 1 crew members aboard 
17:39:13 - Comms:Astra Flight:Astra Tactical:Astra Interaction Mode:Astra Education:Astra
17:39:13 - Say "Rolecall" to find out who is currently onboard
17:39:13 - Say "Mute" / "Unmute" + "the crew" for no responses/responses
17:39:13 - Say "Assign a new crew" for a random selection of crew members to all 4 roles
17:39:13 - Say "Assign someone random to" +"Comms" or +"Flight" or +"Tactical" or +"Interaction Mode"
17:39:13 - Say VOICEPACK NAME +"do everything" or + "to the bridge" to assign all 4 roles to 1 crew member
17:39:13 - Say VOICEPACK NAME +"to comms" to select a crew member for comms
17:39:13 - Say VOICEPACK NAME +"to flight" to select a crew member for flight
17:39:13 - Say VOICEPACK NAME +"to tactical" to assign a crew member to tactical
17:39:13 - Say VOICEPACK NAME +"to interaction mode" to select a crew member for interaction mode
17:39:13 - Say VOICEPACK NAME +"to education" to select a crew member for education
17:39:13 - Your keybinds imported correctly
17:39:13 - Profile startup : '((Profile Initialisation))'
17:39:09 - Profile changed to Multi-Crew

**Comment by cmdrmcdonald** [comment]
This is an issue with the HCS voicepack and not EDDI so I cannot help.
