### ISSUE TITLE
two voices

### ISSUE THREAD

**Issue by kahm007** [cmdrmcdonald/EliteDangerousDataProvider#22]
I have changed my default voice to the ivona voice pack and everything is set to make it the default voice, however some times the voice will switch back to one of the other microsoft ones.

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this.

Which specific voice are you using?  And do you know your locale settings?

If you could provide a copy of the end of your %APPDATA%\EDDI\speech.log when you hear the microsoft voice kick in and let me know which item it is saying it will help to track this down.

**Comment by Nizm0** [comment]
I have similar problem
I hear speech in 2 different languages, one in english (has set in setup) and the second one (in my local Language (it sound very annoying when it trying read english text using polish tts) i can't find location where it is configured) it is the second information about the jump in system
More information i can send when I will back in home

**Comment by Nizm0** [comment]
[speech.zip](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/files/344203/speech.zip)
Problematic line from speech.lang (last line):

31: Turned script  This is a Federation Democracy [of;with a population of;home to;supporting] nearly 17 million [people;souls], [aligned to <phoneme alphabet="ipa" ph="fəˈlɪʃɪə">Felicia</phoneme> <phoneme alphabet="ipa" ph="ˈwɪntəs">Winters</phoneme>;allied with <phoneme alphabet="ipa" ph="fəˈlɪʃɪə">Felicia</phoneme> <phoneme alphabet="ipa" ph="ˈwɪntəs">Winters</phoneme>;controlled by <phoneme alphabet="ipa" ph="fəˈlɪʃɪə">Felicia</phoneme> <phoneme alphabet="ipa" ph="ˈwɪntəs">Winters</phoneme>].  [People's Jaradharre for Equality is the controlling faction.;The controlling faction is People's Jaradharre for Equality.] There are 3 orbital stations and 2 planetary stations. in to speech <?xml version="1.0" encoding="UTF-8"?><speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="pl-PL"><s> This is a Federation Democracy of nearly 17 million people, allied with <phoneme alphabet="ipa" ph="fəˈlɪʃɪə">Felicia</phoneme> <phoneme alphabet="ipa" ph="ˈwɪntəs">Winters</phoneme>.  People's Jaradharre for Equality is the controlling faction. There are 3 orbital stations and 2 planetary stations.</s></speak>

**Comment by cmdrmcdonald** [comment]
The issue here is that the speech sets the locale to your computer's locale (in this case pl-PL) but the voice does not support that locale so the computer's default voice takes over.

To avoid this I've altered the code so that it always uses the voice's preferred locale.  I've put up a beta build that has this fix at http://www.mcdee.net/elite/EDDI-1.4.0b2.zip - please could you try this and see if it fixes your issue?  Thank you.

**Comment by Nizm0** [comment]
ok I check it out tonight, thanks

**Comment by Nizm0** [comment]
Now is ok, there are no problems with a different language: D thanks

**Comment by kahm007** [comment]
Hello.

Here is the information you requested.  :)
I am using Ivona's Amy voice and my locale settings are English (United
States)  Attached is the speech.log file you requested.  Hope it helps. :D

Love the program.



On Fri, Jul 1, 2016 at 2:43 AM, cmdrmcdonald <notifications@github.com>
wrote:

> Thank you for reporting this.
>
> Which specific voice are you using? And do you know your locale settings?
>
> If you could provide a copy of the end of your %APPDATA%\EDDI\speech.log
> when you hear the microsoft voice kick in and let me know which item it is
> saying it will help to track this down.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cmdrmcdonald/EliteDangerousDataProvider/issues/22#issuecomment-229867169>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATTFCSCvq69C44ASIap5jsI1MByyuIq_ks5qRLcfgaJpZM4JCyJt>
> .
>



-- 
Regards


Brian R

**Comment by cmdrmcdonald** [comment]
@kahm007 please can you try the version linked above to see if it fixes your issue?

**Comment by kahm007** [comment]
I would also like to point out that, after looking at the log, I remember
it happening this particular statement set.

Turned script  This is a Federation system  [aligned to <phoneme
alphabet="ipa" ph="ˈzækərɪ">Zachary</phoneme> <phoneme alphabet="ipa"
ph="ˈhʌdsən">Hudson</phoneme>;allied with <phoneme alphabet="ipa"
ph="ˈzækərɪ">Zachary</phoneme> <phoneme alphabet="ipa"
ph="ˈhʌdsən">Hudson</phoneme>;controlled by <phoneme alphabet="ipa"
ph="ˈzækərɪ">Zachary</phoneme> <phoneme alphabet="ipa"
ph="ˈhʌdsən">Hudson</phoneme>]. in to speech <?xml version="1.0"
encoding="UTF-8"?><speak version="1.0" xmlns="
http://www.w3.org/2001/10/synthesis" xml:lang="en-US"><s> This is a
Federation system  aligned to <phoneme alphabet="ipa"
ph="ˈzækərɪ">Zachary</phoneme> <phoneme alphabet="ipa"
ph="ˈhʌdsən">Hudson</phoneme>.</s></speak>

On Fri, Jul 1, 2016 at 2:43 AM, cmdrmcdonald <notifications@github.com>
wrote:

> Thank you for reporting this.
>
> Which specific voice are you using? And do you know your locale settings?
>
> If you could provide a copy of the end of your %APPDATA%\EDDI\speech.log
> when you hear the microsoft voice kick in and let me know which item it is
> saying it will help to track this down.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cmdrmcdonald/EliteDangerousDataProvider/issues/22#issuecomment-229867169>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATTFCSCvq69C44ASIap5jsI1MByyuIq_ks5qRLcfgaJpZM4JCyJt>
> .
>



-- 
Regards


Brian R
