### ISSUE TITLE
EDDI + VA with admin rights / Developer help needed

### ISSUE THREAD

**Issue by nepomuk16321** [cmdrmcdonald/EliteDangerousDataProvider#226]
Hello,
sorry for my bad English, but I hope you understand my problem.
ED and VA (with EDDI as a Plug-in) is installed as an normal user (Win10 64 bit).
It is recommended according to VA forum VA with admin rights to start.
In this case, EDDI no longer finds the required paths. How can I solve this ?

Thx for your help and greetings from nepomuk

**Comment by Darkcyde13** [comment]
You will probably need to install/start EDDI with Admin rights too.  Try that and see if it works. :)

**Comment by nepomuk16321** [comment]
I think this does not work, but I will try it later. I'm still at work.
If I start VA with admin right, EDDI as plug-in has then also automatically admin right, but the game has none. EDDI does not find the paths to the journal an the netlog. But thank you for now.

**Comment by Darkcyde13** [comment]
Ohh, I understand now.  It was not clear that you meant EDDI could not find the Elite paths.  I thought you meant the VA paths.  My apologies.

**Comment by nepomuk16321** [comment]
Hey Darkcyde13, no problem :-) , but you know my problem now. I start VA as user, I have no problem
(Eventual delays in key press). I start VA with admin right, EDDI has no connection to ED, no response from ED. By the way, thank you for the scrips in http://snafets.de/elite/eddi_scripts/ !
Background admin rights - http://voiceattack.com/smf/index.php?topic=654.msg3249#msg3249

**Comment by Darkcyde13** [comment]
@nepomuk16321  Having looked at the VA link you sent, I think you may need to run Elite as Administrator also.  I'm only guessing, because my Windows account has full Admin rights, so I don't need to do this, and mine works OK.

**Comment by nepomuk16321** [comment]
Thank you Darkcyde13.Yes, with admin rights for windows there should be no problems for VA + EDDI + ED. If you, however, two users have set up and an admin, then it does not work anymore. The philosophy of Windows is nevertheless normal work as user perform and only installations, etc. as admin. How does that fit with EDDI ? I believe that to fix I need the developer. Maybe he has an answer.

Thx Darkcyde13, have a nice Weekend !

**Comment by nepomuk16321** [comment]
If someone has a similar problem, here is perhaps the solution http://www.robotronic.de/runasroben.html

Greetings nepomuk
