### ISSUE TITLE
Eddi only works when it's the default profile

### ISSUE THREAD

**Issue by shaunpond** [cmdrmcdonald/EliteDangerousDataProvider#23]
Unless I've missed some step, only if "Elite Dangerous" is the current profile do I get the responses. I see it loads, and the plugin and if I issue an eddi command I get a response. However, when I switch to one of my other profiles, none of the eddi commands work, even if I have the option set in that profile to include commands from the "elite dangerous" profile. Do you think that's eddi or Voice Attack?

**Comment by cmdrmcdonald** [comment]
EDDI is based on an event loop, so you need to ensure that when you start whichever profile you want to use EDDI's event loop is started.  You can find details on how to do this in [the troubleshooting guide](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/blob/master/TROUBLESHOOTING.md#ensure-that-the-eddi-startup-command-runs-when-the-profile-is-loaded)
