### ISSUE TITLE
Incorrect determination of Empire/Federation/Independent space

### ISSUE THREAD

**Issue by MarkAusten** [cmdrmcdonald/EliteDangerousDataProvider#233]
I've been out to Colonia and back and once out of the bubble every jump resulted in 'You are entering space'. This implies that something in the following code block is not working as expected:

    {if lastsystem.allegiance && lastsystem.allegiance != "None" && lastsystem.allegiance != "Independent" && (!system.allegiance || system.allegiance = "None" || system.allegiance = "Independent"):
      You {OneOf("are leaving", "have left", "are no longer in")} {lastsystem.allegiance} space.
    |elif lastsystem.allegiance && lastsystem.allegiance != system.allegiance && system.allegiance != "None":
        You {OneOf("are now in", "have entered", "are entering")} {system.allegiance} space.
        {if cmdr.title != "Commander":
            Welcome back {F("Honorific")}
        }
    }.

Possible a case issue? 'None' and  'none' or 'NONE'?

**Comment by Tkael** [comment]
I don't see the same behavior. If you're not already on the beta, I recommend enabling updates to the latest beta version (via the EDDI App). It may resolve the issue.

**Comment by Tkael** [comment]
If this issue is resolved, would you please mark it as "closed"? Thanks!

**Comment by MarkAusten** [comment]
After much testing this issue appears to have been dealt with. Closing.
