### ISSUE TITLE
Flight Log not auto uploading on EDSM

### ISSUE THREAD

**Issue by PEACETOL** [cmdrmcdonald/EliteDangerousDataProvider#238]
Hi CMDR McDonald, first of all thanks for your work.
I've been using EDDI just fine until the 18 of April, when I stopped playing ED for a while for exams.
Now I've been playing again since yesterday, on 8 July, and I noticed that my flight log on EDSM stopped auto updating, and that I have to manually upload the journal file on the site.
EDDI app is working just fine with all other options, it advices me when I leave/enter a new sector, monitors markets, transactions and Galnet news.
EDSM responder tab is correctly configured with my CMDR name and API key from EDSM, and plugin enabled is ticked, but it still doesn't auto update my flight logs.
Thank you for your time :)

**Comment by PEACETOL** [comment]
P.S. I'm currently using EDDI v2.2.3, it should be updated to last released version :)

**Comment by Tkael** [comment]
There was an issue with the server after the E:D version 2.3.1 update, but that's now been fixed and EDDI is once again reporting correctly to EDSM for me. 

If you're still having problems with EDSM...
1. Make sure the EDSM responder is enabled and properly configured.
2. Consider updating to the latest beta version (you can enable updates to beta versions via the EDDI app)

**Comment by PEACETOL** [comment]
I'll try the beta and let you know

**Comment by PEACETOL** [comment]
Update: nope, even with beta version checked it won't auto update flight logs. What can I do? I already created a firewall exception for EDDI.
Btw it is configured correctly since it succesfully tells me system info when I jump to another system, it even tells me how many times I've been there. Not sure if this is because I pulled the flight logs I manually put on EDSM though.

**Comment by PEACETOL** [comment]
I tried a clean reinstall, uninstalling EDDI and then deleting EDDI %APPDATA% folder, rebooting, installing it again.
Now, I don't know why, it won't log in with companion app, same error as the ones already reported in the two issues reports before mine: 
![issue eddi](https://user-images.githubusercontent.com/30029043/28063399-4b71e064-6631-11e7-8a88-9da75e437106.png)

**Comment by PEACETOL** [comment]
UPDATE: I put EDDI on compatibility mode for Win8, and this time it succesfully upgraded to beta 2.3.0-8b.
Companion app problem is still there, and at the bottom of the first page there is: "EDDI status: Frontier API connection not operational" which I don't know if it refers to the fact that my EDDI isn't connected or that API connection aren't operational at all for everyone.
![eddiissue2](https://user-images.githubusercontent.com/30029043/28064727-0b5c68be-6636-11e7-96a7-1f47843f99b2.png)

**Comment by PEACETOL** [comment]
UPDATE: It seems all problems were due to today's update; After that, EDDI functions are back to normal, working perfectly already. I'll try unchecking beta version to see if the released version functions normally.
If it is, I'll close this issue ticket.

**Comment by PEACETOL** [comment]
Working. Well I'm glad that the problem is solved :)
