### ISSUE TITLE
Weird txt to speech

### ISSUE THREAD

**Issue by sithlordaj** [cmdrmcdonald/EliteDangerousDataProvider#24]
I was just at swoiwns ny-b a95-0, the text to speech said I was in swoiwns "new york"-b a95-0
I'm not sure if that's a bug in eddi or the txt to speech

**Comment by cmdrmcdonald** [comment]
Your text-to-speech engine is seeing NY and assuming that it means "New York".  I'll take a look at separating the letters in sector names to see if that will fix the issue.

**Comment by sithlordaj** [comment]
Shouldn't it see the dash afterwards and change it to letters?Great work on the mod btw. Looking forward to the upgrade potential.
-------- Original message --------From: cmdrmcdonald <notifications@github.com> Date: 8/1/16  2:15 AM  (GMT-06:00) To: cmdrmcdonald/EliteDangerousDataProvider <EliteDangerousDataProvider@noreply.github.com> Cc: sithlordaj <sithlordaj@prodigy.net>, Author <author@noreply.github.com> Subject: Re: [cmdrmcdonald/EliteDangerousDataProvider] Weird txt to speech
  (#24) 
Your text-to-speech engine is seeing NY and assuming that it means "New York".  I'll take a look at separating the letters in sector names to see if that will fix the issue.

**Comment by cmdrmcdonald** [comment]
This was fixed in EDDI 1.4
