### ISSUE TITLE
EDDI not updating ranks or credits on EDSM

### ISSUE THREAD

**Issue by TalShaf** [cmdrmcdonald/EliteDangerousDataProvider#241]
Running EDDI doesn't update my credits or ranks on EDSM.net. Is this intended?

**Comment by Tkael** [comment]
Does other data sync? 
I'm away from home at the moment and can't compare what you're seeing to my own EDSM connection at the moment, but did it stop at some point or have these things never worked for you?

**Comment by TalShaf** [comment]
Yes, the flight logs are synced just fine. Only credits and ranks are not synced. I've only been using EDDI since yesterday. To be honest, I'm experiencing a similar problem with EDDiscovery (all data syncs except ranks and credits), but ED Market Connector syncs ranks and credits just fine, so I don't think it's an API or settings issue on my end.

**Comment by AnthorNet** [comment]
I will take a look tomorrow, I checked today our database and credits are still being registered for other commanders.

**Comment by Tkael** [comment]
Just, checked, this is working for me now.

**Comment by TalShaf** [comment]
At which times does EDDI sync these? At docked events? What I meant to say was that my in game credits and EDSM.net credits never seem to match. AS if it syncs them while I play, but not every dock event or not every purchase/sale.

**Comment by Tkael** [comment]
Not sure, but it doesn't seem to be all that far behind for me. 
If this issue is resolved, please mark it as 'closed'?
