### ISSUE TITLE
No Sound From EDDI

### ISSUE THREAD

**Issue by TJCourey** [cmdrmcdonald/EliteDangerousDataProvider#244]
I'm probably doing something extra noobish but.... I can't hear anything from EDDI. I've gone through all the tabs and set up, I've tried running as administrator, I've uninstalled and reinstalled, and still I can not hear anything from the EDDI program including the test buttons.

**Comment by popoqc** [comment]
Are you using it as a VoiceAttack plugin? If yes, run EDDI manually outside VA. And check if you get some sound. Other thoughts, check your Windows default speech voice and playback device.

**Comment by Tkael** [comment]
If this issue is resolved, would you please mark it as "closed"? Thanks!

**Comment by TJCourey** [comment]
Thanks! Was a Windows issue.
