### ISSUE TITLE
Planet radius variable incorrectly described in documentation

### ISSUE THREAD

**Issue by Tkael** [cmdrmcdonald/EliteDangerousDataProvider#247]
Planetary radius is reported in meters. The documentation for EDDI (variables.md) incorrectly indicates that the radius is reported in kilometers.

**Comment by Tkael** [comment]
Relevant journal entry:
`{ "timestamp":"2017-07-15T02:16:44Z", "event":"Scan", "BodyName":"59 Arietis 1", "DistanceFromArrivalLS":291.981720, "TidalLock":true, "TerraformState":"", "PlanetClass":"High metal content body", "Atmosphere":"", "AtmosphereType":"None", "Volcanism":"", "MassEM":1.081989, "Radius":6234260.500000, "SurfaceGravity":11.095899, "SurfaceTemperature":629.901367, "SurfacePressure":0.000000, "Landable":true, "Materials":[ { "Name":"iron", "Percent":21.747345 }, { "Name":"nickel", "Percent":16.448780 }, { "Name":"sulphur", "Percent":15.598898 }, { "Name":"carbon", "Percent":13.117059 }, { "Name":"chromium", "Percent":9.780503 }, { "Name":"manganese", "Percent":8.981431 }, { "Name":"phosphorus", "Percent":8.397765 }, { "Name":"selenium", "Percent":2.441360 }, { "Name":"ruthenium", "Percent":1.343037 }, { "Name":"tungsten", "Percent":1.194148 }, { "Name":"mercury", "Percent":0.949671 } ], "SemiMajorAxis":87533461504.000000, "Eccentricity":0.000009, "OrbitalInclination":-0.013004, "Periapsis":306.780884, "OrbitalPeriod":15782457.000000, "RotationPeriod":15782763.000000, "AxialTilt":0.253417 }`

The system map records the radius of the same body as "6,234 KM"

**Comment by Darkcyde13** [comment]
The journal reports the radius in metres, but EDDI converts it to kilometres by default.

I just added this line into EDDI and set reportbody to 59 Arietis 1.

**_It has a radius of {reportbody.radius} kilometers._**

EDDI spoke this line as "It has a radius of 6234 kilometers."

**Comment by Tkael** [comment]
I thought that I'd proved it to be meters rather than kilometers, but with further testing I can confirm that you're right. Closed.
