### ISSUE TITLE
Some Speech Responders, while under new personality, cannot be unchecked in recent update.

### ISSUE THREAD

**Issue by LigerXT5** [cmdrmcdonald/EliteDangerousDataProvider#248]
I noticed after the recent update, EDDI will speak out details of systems I'm jumping to, and details about them, along with more "chatter" in chat that isn't from players.

I attempt to uncheck these in the custom personality profile I have, however some, such as System State Report" I cannot uncheck. Not greyed out, just no change when I click the check box. Others, such as System State Changed, I can disable with no issues. Surprisingly, I can delete the ones I can't uncheck to disable.

**Comment by Bahnzo** [comment]
I came here to look for this same problem. Expect mine is that I cannot uncheck *any* of the boxes. The "Enabled" check box is lightly greyed out. Any ideas?

**Comment by LigerXT5** [comment]
@Bahnzo 
Is your checkbox issue, under the default/original EDDI personality dropdown option (above the checkbox of items area), or under a custom one you have made?

On the default EDDI dropdown option, you can't make changes, that I'm aware of. I've copied the profile as EDDI2 in the past to disable the ones I didn't want/need. Though in my case, both the custom, and original obviously, I can't disable certain listings.

I just want to disable the jabber talk while jumping from system to system, and all the NPC chatter in chat. Just the player chatter like it used to be. I stream while I play, so all the other chatter is rather annoying, lol.

**Comment by Bahnzo** [comment]
Hi. I've just installed the program, so I've not made any changes besides entering credentials for API's. 

Like you, I want to disable some of the talk that I don't find useful. I'll look into how to make the changes and copy the profiles and see how that works. Thanks.

**Comment by Tkael** [comment]
@Bahnzo, @LigerXT5 has the right idea. If you want to disable some scripts, create a copy of the default EDDI personality and then disable the scripts in the copy.

I believe that only scripts directly linked to journal events can be disabled. I believe that scripts like "System State Report" cannot be disabled because they are not linked to the player journal - you need to remove or comment out the code calling "System State Report".
Supporting comment from the author, from the thread: https://forums.frontier.co.uk/showthread.php/294579-EDDI-Windows-app-for-immersion-and-more?p=5226166&viewfull=1#post5226166

**Comment by LigerXT5** [comment]
I figured that would be the case.

I've gone in and uninstalled EDDI and reinstalled it. Surprising, after I uninstalled it, assuming all information would be deleted, inlcuding the logins and profiles, some settings stayed, including the custom profile I had up.

Removed my custom profile, made a new one, disabled the ones I don't want that is disable-able, and the changes took affect.

**Comment by Tkael** [comment]
Glad to hear it. Mind closing this issue if it is fully resolved? :-)

**Comment by LigerXT5** [comment]
But... Lol, I don't see why not. At least if someone has a similar issue, this ticket can be referenced. :)
