### ISSUE TITLE
Swapout?

### ISSUE THREAD

**Issue by TalShaf** [cmdrmcdonald/EliteDangerousDataProvider#249]
After landing at a LYR station, EDDI informed I could save X credits by swapping out certain modules. But when I try to sell my equipped module, the sell price is the same as the buy price, so I'm not actually saving anything. Should I store my equipped module and sell it later? Won't the transport costs offset the savings? I feel like I'm missing something basic, any help would be appreciated.

**Comment by Tkael** [comment]
The LYR station won't buy it from you at the higher price, but another station might... and yes if you transfer modules then your profit will be diminished by the transfer costs.

**Comment by Tkael** [comment]
If this issue is resolved, please mark it as "closed"? Thanks!
