### ISSUE TITLE
Limpet check issue

### ISSUE THREAD

**Issue by Bahnzo** [cmdrmcdonald/EliteDangerousDataProvider#251]
I initially installed a limpet controller on my Python. After completing mining, I removed all controllers. But I'm still getting the "You have a limpet controller but have no limpets" warning. 

Edit: And annoyingly I can't seem to get rid of it. I've copied the personality so it can be edited, but I'm unable to uncheck the "Limpet Check" script. And if I delete it, when I shutdown the program and restart it, the script is still there.

**Comment by Tkael** [comment]
This is already a known issue. See https://forums.frontier.co.uk/showthread.php/294579-EDDI-Windows-app-for-immersion-and-more?p=5726100&viewfull=1#post5726100. Unfortunately, it seems like the fix depends on Frontier.

You can only uncheck scripts that are triggered directly from a journal event. You can get rid of it, however, by either deleting the contents of the "Limpet check" script or by removing the following function call from the relevant scripts: {F("Limpet check")}.

**Comment by Bahnzo** [comment]
Ok, good enough, thanks.
