### ISSUE TITLE
Is the data of api.eddp.co incomplete?

### ISSUE THREAD

**Issue by qubeGH** [cmdrmcdonald/EliteDangerousDataProvider#255]
This sentence uses a google translation. It may be difficult to read, I'm sorry.

In the data obtained from api.eddp.co, the station data existing around the colonia system is not described, which is why the landing pad related event is not executed correctly?

**Comment by Tkael** [comment]
Landing pads are only spoken for orbiting stations - planetary settlements are exempted so you wouldn't expect EDDI to say anything at Colonia Hub.

If this occurred at Jaque's Station, EDDB should have enough information to describe this correctly.
Would you please share an example journal entry from the 'Docking granted' event in the player journal where this should have triggered? You can find your player journal files at C:\Users\[YOUR WINDOWS NAME]\Saved Games\Frontier Developments\Elite Dangerous\.

**Comment by qubeGH** [comment]
The Jaque's station of the colonia system speaks without problems, but the orbit station present in the nearby system does not speak.
For example
TolaGarf's Junkyard station of Kojeara system

**Comment by Tkael** [comment]
Then I think I know the problem... the default script doesn't include the new asteroid bases and that station is classified as an asteroid base. You'll need to edit your 'Docking requested' script as follows to include them:

Replace:
`{if station.model = "Coriolis Starport" || station.model = "Orbis Starport" || station.model = "Ocellus Starport" || station.model = "Unknown Starport":`

With:
`{if station.model = "Coriolis Starport" || station.model = "Orbis Starport" || station.model = "Ocellus Starport" || station.model = "Asteroid Base" || station.model = "Unknown Starport":`

**Comment by Tkael** [comment]
I've created a pull request to correct this on the default script in the next update (https://github.com/cmdrmcdonald/EliteDangerousDataProvider/pull/265). If you were also able to update your local script, let's mark this issue as "closed". Thanks!
