### ISSUE TITLE
Ship Name (Spoken)

### ISSUE THREAD

**Issue by HolyGoat** [cmdrmcdonald/EliteDangerousDataProvider#259]
Perhaps I am missing something, but I cannot seem to get EDDI to save the spoken ship name category on the Ship Monitor tab. I have figured it all out in IPA and entered it into the field, but the field is highlighted in red, has a red ! in front of the row, and doesn't save when I exit, nor does the TTS voice say the proper name when I click "Hear It".

Is there a special way the IPA text must appear in the field, i.e. /ðə'gret'ʃakra'kiki/ or 'ðə'gret'ʃakra'kiki'

**Comment by AndySpawn** [comment]
Mine have saved ok, but EDDI can't pronounce them correctly unless Phonetic Speech is left on.

I have entered:

ˈmjœlːnir
&
hʌɪnɪə

Those both work for Mjolnir & Hoenir, respectively.

**Comment by HolyGoat** [comment]
I figured it out shortly after I posted this. Turns out one of the IPA characters is indistinguishable from the English character, but ED SO wouldn't recognize it. I ended up just copying each letter from the IPA website and pasting it in the field.
