### ISSUE TITLE
VA variable {INT:Ship cargo carried} has not worked for a long time (EDDI 2.3.0)

### ISSUE THREAD

**Issue by FireSammy** [cmdrmcdonald/EliteDangerousDataProvider#263]
Main issues for VA variables: 
{INT:Ship cargo carried}
Is there any possibility to check/update this variable? It would help alot.

For comparison, {INT:Ship limpets carried} has been working most of the time quite well. Fortunately :)

Additional related questions:
{INT:Ship cargo capacity}
This has been reported as an issue in other thread, and obviously it has some restrictions "when" it can give results, which is again understandable > Frontier

Anyways, it would also help alot if this could be changed,- and/or updated to work all the time if/when triggered via any VA command, cheers? :)

Is there any way to have a VA variable checking both main cargo types carried in the ship >>> Is the cargo carried a commodity,-or a passenger (boolean illegal/legal true/false)? Even a VA variable which cargo rack this type of cargo is carried?

Commodity Purchase and collection commands + variables etc. are already working great, but these additions would be super cool to have.

-------------------
Daydreaming:
The absolute best thing would be similar to the currently working and fabulous -material monitor, which includes also data lists in the EDDI app. Meaning the possibility to also check directly from the EDDI app how much cargo space is available in the current ship, how much cargo is the maximum (cargo capacity), how much is currently carried (cargo carried), and which type cargo is carried (commodity or passenger) -even a VA variable to check if it is "illegal/legal" -similar VA variable than {INT:Ship limpets carried} is working,- to have the number/count + type

For example:
{BOOLEAN:EDDI Ship passenger cargo carried legal} True/False [illegal] and [Not set] no passengers, zero. {INT:Ship passenger cargo carried} = How many passengers currently in cargo?

{BOOLEAN:EDDI Ship commodity cargo carried legal} True/False (illegal) and [Not set] no commodities, zero. {INT:Ship commodity cargo carried} = How many commodities currently in cargo

These would be perfect additions into the VA ((Mission accepted)) command. I don't have any idea what/how it should look like, for the commodity types to get variable listed? Also no idea what/how it could look like for the commodities/passenger variable to get the cargo rack number (EDDI ship variables -module occupied... etc.. maybe???)

Idea (don't know if these have been suggested before?) Additionally the exact way we now have to monitor material/data, would be the ability to monitor all commodities available in game and especially for "efficient fast" mining operations with collector limpet setups, would be absolutely killer thing to have this type of monitor automatically informing when you have the desired amount of needed commodities on board. Also telling if/when you have commodities that you do not need/want with having a workin VA variables/commands to trigger commands with VA

For example, ((material refined)) -is already working really well, but again, the main problem is the {INT:Ship cargo carried} not working, and the other just partially working {INT:Ship cargo capacity} not being able to tell you when these basic info can be triggered correctly and automatically independently,-and/or inside/with another VA command such as the mentioned ((Material refined)) command, etc. considering commodities.

It would also be even greater to have additional and exact VA Material and data -variables to trigger commands when the EDDI Material monitor is giving a speech info about it's status.

For example:
((Material maximum exceeded)) + similar variable to have the number/count + type
((Material desired amount reached)) + similar variable to have the number/count + type
((Data maximum exceeded)) + similar variable to have the number/count + type
((Data desired amount reached)) + similar variable to have the number/count + type

+ if possible to do the commodity monitor:
((Commodity maximum exceeded)) + similar variable to have the number/count + type
((Commodity desired exceeded)) + similar variable to have the number/count + type

For the different commodities variable list, would pay real money to get them variable listed for example into the EDDI Information category, -similar way we have the Station variables, Ship variables, etc. :)

I hope you guys understand what i mean, as hard to get it all short and understandable form... huh

-------------------------
PS: I have read in some e-mails that cmdrmcdonald has quit developing this thing. I hope this is just a well deserved break and we'll see the master back on the saddle asap. 

Standing in attention and saluting o7

**Comment by Tkael** [comment]
Unfortunately cargo (and specifically cargo flags) are a little borked at the moment for both EDDI and VoiceAttack. 

This is something of a duplicate issue. See here: https://github.com/cmdrmcdonald/EliteDangerousDataProvider/issues/258 and https://github.com/cmdrmcdonald/EliteDangerousDataProvider/issues/62

The latest comments from the developer on the status of the cargo bug are here:
https://forums.frontier.co.uk/showthread.php/294579-EDDI-Windows-app-for-immersion-and-more?p=5726100&viewfull=1#post5726100

Hopefully either the master returns or someone else is able to pick up the mantle of supporting this wonderful program.

**Comment by FireSammy** [comment]
Thx for the fast reply.

I can easily agree keeping it only "issues" -related here. Just shooting "blanks" with daydreaming lol

Anyways, would hope we could have a somekinda suggestions tab here too. Many of us find the forums really annoying and heavy to read in general... Adding to that i scrolled around the "event" lists and actually many of my "ideas" have already implemented so i can do a lot wit existing variables already. Still i would hope for some simple words -are my suggestind "daydreams" absolutely impossible bad, or good enough for a separate thread, thx ;)

And addistionally, i sincerely hope the master is ok, and possibly even considering to do a mind blowing comeback,- or even if just one update a week, schedule....  Less is just fine too. Completely quitting is a terrible thought :/ I can only imagine the workload.

I would pay real money if only accepted, and if it would help, -without any demands for any new updates. This thing is already worth of a serious donation for the work done, meaning at least the money for the game account for sure. Without EDDI, i would've quit long time ago.

It really makes the game worth playing and not even mentioning about VA. Virtual Reality gaming is exactly what this is all about. Both Oculus and Frontier should hire the master!!!! And pay a cool million for a licence at least!

Some arrsholes have been demending stuff here quite offensively and too often, so first thing we could do is to set some serious rules for this kind of messaging. Just like everywhere else. One warning. Second offence >>> out of EDDI!! Period!

FireSammy o7

**Comment by FireSammy** [comment]
OMG moment with this issue!!!! ???? HOW and what LOLOL OMG!!! WOHOO!!!

![omg moment with cargo variable](https://user-images.githubusercontent.com/21980416/28984789-4d7d83be-7968-11e7-9785-db244c8abd97.JPG)

I hope this works. Never uploaded a screenpic before ... Oki it seems to be visible. Cargo variables are actually giving a number now. All of them, and not just "Not set". What ever it is, and who ever made this happen this fast, faaaaabuuulous! Cheers for that!
