### ISSUE TITLE
EDDN migrated to new server on 8/9/17. EDDI no longer communicating with EDDN.

### ISSUE THREAD

**Issue by Hoodathunk** [cmdrmcdonald/EliteDangerousDataProvider#268]
EDDI's 'EDDN Responder' needs a patch to communicate with new EDDN server.

**Comment by Hoodathunk** [comment]
Looks like this WAS patched in the 2.3.0 'tidy ups' but will leave open briefly to verify EDDN is continuing to take hits from EDDI.

h.t. to Cmdr J. Calvert

**Comment by Tkael** [comment]
Has this been verified as resolved?

**Comment by Hoodathunk** [comment]
EDDN is showing on-going contributions from EDDI. I think it's reasonable to say that jgm did implement the changes for the new server location in 2.3.0
