### ISSUE TITLE
Coriolis called with bad URL

### ISSUE THREAD

**Issue by treyharris** [cmdrmcdonald/EliteDangerousDataProvider#27]
When I say, "Display ship in Coriolis", I do not get a valid URL.

The URL generated is:
 `https://coriolis.io/outfit/type-7_transporter/04A5D5A4D3D3D4C--2222040406050505040403452f24.Iw18aQAA.CwBgjCnlPm8Qkm==?bn=Type-7%20Heavy%20(ITS-4155)`

which, [when visited](https://coriolis.io/outfit/type-7_transporter/04A5D5A4D3D3D4C--2222040406050505040403452f24.Iw18aQAA.CwBgjCnlPm8Qkm==?bn=Type-7%20Heavy%20%28ITS-4155%29), returns the result:

```
Jameson, we have a problem..
Ship not found: type-7_transporter
```

Other integrations (with EDDB and EDSM) are working perfectly. I am using EDDI version 1.4.0, which was installed cleanly without a prior EDDI version.

**Comment by cmdrmcdonald** [comment]
There are a couple of issues here.  I've fixed the major one (in Coriolis the ship name for the type-7 is actually type_7_transport) but there's an odd one around incorrect power priorities.  Is there any chance that you could build your ship manually in Coriolis, including the power priorities, and send me the link to it?  Thanks.

**Comment by treyharris** [comment]
I can't, unfortunately, as I just got exploded and had to sell my Type-7 for something more affordable. :-( The Asp Explorer is showing up okay. I believe my build was this, though: https://coriolis.io/outfit/type_7_transport/0patiFfliddsdf4--2222040406050505040403452f24.Iw18aQ==.Aw18aQ==?bn=Type%207%202016-08-26

**Comment by sutex** [comment]
Cant get URL "string" to be captured by clipboard while preventing the browser from opening in the first place

**Comment by cmdrmcdonald** [comment]
Coriolis URL generation has been reworked for coriolis 2.2.1.
