### ISSUE TITLE
Help for using the EDDI voice effect plugin

### ISSUE THREAD

**Issue by FireSammy** [cmdrmcdonald/EliteDangerousDataProvider#28]
First i want inform you that you have one serious fan here cmdrmcdonald! Absolutely fantastic work m8! I'm so happy i found EDDI and it's so great my hands are shaking, when i can see the potential how many ways it can be useful! I have A LOT of questions and ideas and been working on my own VA profile mod for 2+ months now, but currently the main problem is: 

I can't get my "say something in text-to-speech" lines to use the EDDI voice effect plugin, following your advise using the "script" token thing for text variables... Yeah my terrible "noob stupidity" has been brought before you, and i humbly request and i would really appreciate, if you could provide a solid example how exactly it is done? I just don't get this :P

Here is what is my best try so far:

From "normal" way using the Microsoft Anna (or default speech engine voice): 
Say, 'Testing the voice effect'

to

Say Text [Instructor script] to 'Testing the voice effect"
Execute external plugin, 'EDDI 1.4.0' and wait for return
Set Text [Instructor script] to [Not Set]

Best regards,
FireSammy

**Comment by cmdrmcdonald** [comment]
It looks like you are nearly there.  The final step is to tell the plugin that you want it to say something, and what exactly to say.  To do so you need to edit the 'execute external plugin' command and ensure that the following are configured:

- set the context to 'say'
- pass the script variable 'Instructor script' as a text variable

It should look like this:

![say](https://cloud.githubusercontent.com/assets/16817420/18230373/4a33f470-7290-11e6-8dce-f6ad96663b5b.PNG)

**Comment by FireSammy** [comment]
What can a "blind noob" say? LOL? That works 100% and i somehow managed to miss that "Plugin Context" -thing from your EDDI text script commands... I hope this will help others too having the same problem. I'm very happy now, and thanks master cmdrmcdonald for the fast reply, cheers!

Like i already mentioned above, i have a lot of questions and ideas regarding EDDI. Is there any possibility to send you my other inquiries via any private channels, as they are not exactly issues, but more like questions, development ideas and possible co-op -type of things i would like to share with you. Just to inform you my current VA profile for Elite Dangerous has about 1900 commands (and counting), which the majority (at least the important ones) have some conditional values and multichecks involved, so i really think EDDI is the best possible approach to do some stuff and currently has by far, the most potential to actually make things happen, never thought even being possible!

Here is my e-mail:
sami.lifeline@gmail.com

**Comment by cmdrmcdonald** [comment]
The best place to discuss EDDI is on the Frontier forums thread at https://forums.frontier.co.uk/showthread.php/226649-EDDI-A(nother)-Voice-Attack-Plugin as this allows others to join in the discussion.

**Comment by FireSammy** [comment]
Very good sir and i understand.

Already reading all the 55 pages, and trying to compile my stuff 
together for joining in :)

Cheers!
