### ISSUE TITLE
Echo when testing scripts / ingame

### ISSUE THREAD

**Issue by TalShaf** [cmdrmcdonald/EliteDangerousDataProvider#282]
When I test scripts in the Speech responder tab, the voice comes through with an echo effect that is not present when I test the voice under the Text-to-speech tab.

In game, the echo is produced on game load, but then doesn't occur again, AFAIK. **Edit: I was wrong, the echo is produced all the time, in game and out, except in the Text-to-speech tab.**

Am I forgetting a setting somewhere?

**Comment by Tkael** [comment]
are you using VoiceAttack? When you say echo, does it sound like 2 overlapping voices? Do you have EDDI & VoiceAttack open at the same time?

**Comment by TalShaf** [comment]
Not using VA. Not two overlapping voices, but an echo, or perhaps it's called reverb? There is an effect on it that isn't there when testing in the text to speech tab.

**Comment by TalShaf** [comment]
I missed the part about EDDI changing the voice depending on the size of the cockpit. I just changed to a Type 7, and I guess EDDI is trying to emulate the size of the cockpit. Excellent, now that I get it. This issue can be closed.
