### ISSUE TITLE
Landing event not getting body name and sometimes gets correct coords.

### ISSUE THREAD

**Issue by JCBurnside** [cmdrmcdonald/EliteDangerousDataProvider#284]
When landing (ATM I have only tested it on COL 285 SECTOR ZP-G A40-0 9 A,  A land-able moon) and about 40-50% of the time it gives the right coords. the other times it says I am at 0,0.  It never says the body name.  I will dig into the issue. 
CURRENT EDDI VERSION : 2.3.1

**Comment by JCBurnside** [comment]
Update: found similar issue with the touchdown event.
the coords are not always retrieving.

**Comment by Tkael** [comment]
The original developer has stepped away from maintaining EDDI after version 2.3.0. For EDDI versions 2.3.1 & later, please report issues at https://github.com/EDCD/EDDI/issues. We've taken over maintenance of this project and maintain 2.3.1 & later on a different branch (at the address noted above). Please open a new issue at that location and if possible please include answers to the questions below:
- In the cases that you are describing, are you describing touchdown events where you are flying the ship as well as ship-controlled touchdowns while you are in an SRV? Per the journal manual, longitude & latitude are given only of the player is flying the ship.
- Are you using the default touchdown script from 2.3.1 or has it been modified in some way?

Thanks!

**Comment by JCBurnside** [comment]
No problem. I didn't know about the transfer.  why didn't he just transfer the existing repo to you?

**Comment by Tkael** [comment]
He'd stepped away and we were unable to reach him, so we forked the project and began working on our own fork.
