### ISSUE TITLE
Ship function toggle states

### ISSUE THREAD

**Issue by CmdrGaiseric** [cmdrmcdonald/EliteDangerousDataProvider#288]
Is it possible to pass to VoiceAttack the toggle state of, for instance, "Silent Running" or "Supercruise"?  I can set up VoiceAttack to turn on headlights, for instance, but if they were already on (let's say the object I am looking at is too far away to tell) then the command will actually turn them off.  It would be nice if I could put this inside an IF statement with the toggle state as input.

**Comment by Tkael** [comment]
Silent running isn't possible, as that information isn't included in the journal.

**Comment by Tkael** [comment]
you can determine whether the ship is in supercruise, normal space, etc. By using the environment variable described here: https://github.com/cmdrmcdonald/EliteDangerousDataProvider/wiki/VoiceAttack-Integration

**Comment by CmdrGaiseric** [comment]
Thanks for that. I guess the answer is going to be the same for all the toggling functions (landing gear, cargo scoop, etc.) It's simply not possible to read the current state.

**Comment by Tkael** [comment]
I'm afraid so.
