### ISSUE TITLE
Crashing issues with EDDI version 1.4.0 

### ISSUE THREAD

**Issue by korci** [cmdrmcdonald/EliteDangerousDataProvider#29]
Hi!

I've started using EDDI plugin yesterday (great potential btw) and had struggled quite a lot to get it to work. The main issue was that the configuration.exe crashed without running at some point, and the EDDI plugin refused to work as well. I've tried quite a lot of things, but the only way to solve this was to delete the credentials.json file which made the configuration.exe stop crashing, and recreate the connection. After a while the plugin stopped working, and configuration.exe started crashing again. 

I've tried to move the program to another windows profile but after copying the credentials.json file the issue reappeared. I've tried this with the other json files, but they made no difference.

The event viewer logged the following errors, I hope it might give You some clue:

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2016-09-17T17:12:51.997345400Z" /> 
  <EventRecordID>4406</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-RV37PE4</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>configuration.exe</Data> 
  <Data>1.0.0.0</Data> 
  <Data>577cdc30</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.14393.187</Data> 
  <Data>57cf98b1</Data> 
  <Data>e0434352</Data> 
  <Data>000d96c2</Data> 
  <Data>1834</Data> 
  <Data>01d21106b8e693a9</Data> 
  <Data>C:\Program Files (x86)\VoiceAttack\Apps\EDDI\configuration.exe</Data> 
  <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data> 
  <Data>0fc66db9-38e3-4d52-b3e5-2441036be2eb</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
 
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2016-09-17T17:12:51.960318100Z" /> 
  <EventRecordID>4405</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-RV37PE4</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Application: configuration.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.FormatException at System.Number.StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean) at System.Number.ParseInt64(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo) at System.Convert.ToInt64(System.String) at EliteDangerousCompanionAppService.CompanionAppService.AddMachineTokenCookie(System.Net.CookieContainer, EliteDangerousCompanionAppService.CompanionAppCredentials) at EliteDangerousCompanionAppService.CompanionAppService.GetRequest(System.String) at EliteDangerousCompanionAppService.CompanionAppService.Profile() at EliteDangerousCompanionAppService.CompanionAppService..ctor() at configuration.MainWindow..ctor() Exception Info: System.Windows.Markup.XamlParseException at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri) at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri) at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean) at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext) at System.Windows.Application.LoadComponent(System.Uri, Boolean) at System.Windows.Application.DoStartup() at System.Windows.Application.<.ctor>b__1_0(System.Object) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at System.Windows.Threading.DispatcherOperation.InvokeImpl() at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object) at System.Windows.Threading.DispatcherOperation.Invoke() at System.Windows.Threading.Dispatcher.ProcessQueue() at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32) at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr) at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef) at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame) at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame) at System.Windows.Application.RunDispatcher(System.Object) at System.Windows.Application.RunInternal(System.Windows.Window) at System.Windows.Application.Run(System.Windows.Window) at System.Windows.Application.Run() at configuration.App.Main()</Data> 
  </EventData>
  </Event>

**Comment by cmdrmcdonald** [comment]
Thanks for reporting this.  What locale are you running your copy of windows in?

**Comment by korci** [comment]
The locale is Hungarian.

**Comment by cmdrmcdonald** [comment]
This issue was due to not handling locales correctly when transferring data to and from the filesystem.  This should be addressed in EDDI 2, for which a beta is now available.
