### ISSUE TITLE
'Jumped' event not responding

### ISSUE THREAD

**Issue by naperken** [cmdrmcdonald/EliteDangerousDataProvider#32]
Following a successful FSD jump, neither the EDDI speech responder script (was blank, inserted "Exited Witch Space") nor the VoiceAttack event command ((EDDI Jumped)) in the active profile is being executed.

Running E:D 2.2 beta 5,  EDDI 2.0.0b3 and VoiceAttack 1.5.12.24

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this.  It has been fixed in the latest beta version of EDDI.
