### ISSUE TITLE
EDDI 2 cant download EDDI 3

### ISSUE THREAD

**Issue by Ailta** [cmdrmcdonald/EliteDangerousDataProvider#322]
if i try in EDDI 2 download EDDI 3 she/he say download failure

**Comment by digitalZYN** [comment]
I have this same issue

**Comment by Tkael** [comment]
There's a new download location for the new repository. You can find it [here.](https://github.com/EDCD/EDDI/releases)

**Comment by Ailta** [comment]
> There's a new download location for the new repository. You can find it [here.](https://github.com/EDCD/EDDI/releases)

Thanks
