### ISSUE TITLE
TTS bug after installing new voices for Windows

### ISSUE THREAD

**Issue by Mr-Beta** [cmdrmcdonald/EliteDangerousDataProvider#36]
Hi, I tested the software and everything seemed to work fine.
After a while I decided to install new voices for Windows. After a little research I came across [this guide](http://superuser.com/questions/590779/how-to-install-more-voices-to-windows-speech), and did as instructed there.

The new voices work fine from the Windows TTS configuration screen, but when trying to test it from EDDI, the whole process freezes. Even the original default voice (Anna) doesn't work.

I'm running Windows 7 64-bit. The Speech Platform selected is 64-bit, and the voices don't have a 64/32-bit selection.

Thank you very much for this awesome (and free!) software.

**Comment by sunbart** [comment]
Hi,
I did exactly the same thing, the same guide and the same voices and I have (surprisingly :)) the same problem.

In fact, when I launch EDDI (even without having one of the new voices selected for EDDI), the program says nothing and is not even in the volume mixer. Also, EDDI proceeds to use 100% of my CPU, which is not normal (I have a fairly high-end CPU).

I also have Windows 7 x64.

EDDI was great while it worked (and I'm blaming the TTS problems on Microsoft), so thanks for the program anyway :)

**Comment by Mr-Beta** [comment]
Uninstall the voices and delete their registry files (be sure to keep Anna). A crappy robot voice is better than nothing.

**Comment by cmdrmcdonald** [comment]
Some of the Microsoft voices appear to have bugs which results in SSML speech putting them in to a loop.  There is an option on the 'Text-to-speech' tab that allows you to turn of SSML speech, or you could use purchase a voice form a commercial company (e.g. Ivona) that is better-behaved.
