### ISSUE TITLE
Unexpected Problem Connecting Companion App

### ISSUE THREAD

**Issue by tententacles** [cmdrmcdonald/EliteDangerousDataProvider#37]
I put in my login, then entered the code I received from Frontier, and received the following error:
![eddiunexpectedproblem](https://cloud.githubusercontent.com/assets/15621600/19733821/32beb0b2-9b73-11e6-8181-c560f36d7527.png)

**Comment by SurelyExploding** [comment]
I'm having the same issue, but after attempting to connect, EDDI will refuse to launch until I delete my user preferences (if anyone else is having this same problem, you can find them in "%APPDATA%/Roaming/EDDI", if you delete this folder, EDDI should launch normally again.)

**Comment by cmdrmcdonald** [comment]
This is an issue with 2.0.3, and has been fixed in 2.0.4.  If you upgrade then this problem should go away.
