### ISSUE TITLE
EDDI crashes when saying certain words.

### ISSUE THREAD

**Issue by CMDRDeMonkey** [cmdrmcdonald/EliteDangerousDataProvider#39]
I'm new to all this, only made an account here to post this because I have no idea what to do.

Most of the time it works fine, I love using the program, but it crashes everytime I go to Wohler Terminal.

After searching for a reason I believe it's crashing on certain words, for example when using 'Microsoft Anna' and testing her voice 'Adder' and 'Anaconda' both work perfectly, but for the 'Cobras' and the 'Vulture' there's a delay before she says the word, and then she stutters it out.

When using the default 'Windows TTS' or an Ivona voice it crashes EDDI on those words. No error report, just 'EDDI has stopped working'.

Did I install wrong?

**Comment by CMDRDeMonkey** [comment]
Well, now it just seems to crash everytime I jump...

**Comment by CMDRDeMonkey** [comment]
Can't seem to upload the text file here, just told that the file type is unsupported and I'm not sure how to change it to a file type that is supported, sorry. :/

Anyway, I've copied the bit that I'm hoping is relevant. 

''2016-10-28T00:09:09 SpeechService:Speak [D] SSML speech: <?xml version="1.0" encoding="UTF-8"?><speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="en-US"><s>This is how I will sound in your <phoneme alphabet="ipa" ph="ˈvʌltʃə">vulture</phoneme> .</s></speak>
2016-10-28T00:09:09 SpeechService:synth_StateChanged [D] Current state of the synthesizer: Speaking''

Those are the final two lines, the program fails upon pressing the button before uttering a word.

**Comment by cmdrmcdonald** [comment]
Looking at this it's possible that the voice you are using doesn't support phonetic speech.  That said, EDDI should be able to handle this and fall back to normal speech in this situation.

Please could you try the package at http://www.mcdee.net/elite/EDDI-2.0.6.exe and see if this fixes your issue?  If not then please send along the last few lines of the log again, as they will have more information about what's going on (I added some more debug lines).

**Comment by CMDRDeMonkey** [comment]
http://imgur.com/D6OLLsY

I played the Adder one first, and then the Vulture one afterwards. I added a line break to the vulture line to stop it continuing off screen.
I guess it is a phonetic issue. Slightly surprised that the default Windows TTS also causes the crash though.
(away for the weekend so any further changes I will have to make when I get back)

**Comment by CMDRDeMonkey** [comment]
Update. It can't be a phonetic issue with the voice, if I enter the line EDDI gives the TTS into the Windows TTS preview it works perfectly. Cobra, Viper, Vulture. They all come out fine.

**Comment by cmdrmcdonald** [comment]
Please could you try http://www.mcdee.net/elite/EDD-test.exe ?  It probably won't fix the issue but will give a lot more debug information.  If you do have a crash please provide your %APPDATA%\EDDI\eddi.log for me to take a look at.  Thanks.

**Comment by CMDRDeMonkey** [comment]
http://imgur.com/05wjoVH
That's a print screen from loading EDDI, selecting the TTS tab, selecting Vulture and testing. It again resulted in a crash.

However disabling phonetic speech means that it works just fine, Vulture/Viper etc come out with no difficulties at all.

I'm unsure why phonetic speech is causing an issue, as I said earlier copying the line that appears in the log when it tries to say Vulture, and pasting that into Windows' own text to speech preview works fine.

**Comment by Kaltern** [comment]
If I might interrupt :P  I have the Ivona voices, and Some are definitely causing issues - Kendra, Kimberly, Ivona, Joey, Jennifer, Ivy and Eric all crash when attempting to speak the Vulture testing sentence.  (Amy, Brian, Emma, Geraint, Gwenyth, Nicole and Russell all work fine).  

Disabling phonetic speech does work fine.  Hope this is of some use.

**Comment by cmdrmcdonald** [comment]
Just tried this with Kimberly and it worked:

https://i.imgur.com/iPscayN.png

Does your setup look any different?

**Comment by Kaltern** [comment]
A few minor slider settings.  I adjusted mine to be identical to the image, and it still crashed with Kimberly - disabling phonetics worked fine.

In-game it plays fine without using phonetics.  I can only assume regional settings have some bearing on it (I'm using UK settings).

**Comment by CMDRDeMonkey** [comment]
I'm also using UK settings.

**Comment by cmdrmcdonald** [comment]
Version 2.0.9 has been released that has a lot more bug checking and error catching so if you had the crashing problem please give it a go with phonetics enabled again to see if it works any better.

I also have access to a Windows 10 system I can play around with so will continue to attempt to recreate the issue.

**Comment by cmdrmcdonald** [comment]
I believe that this issue has been resolved.  If anyone finds another crash with TTS please raise a new issue.  Thank you.
