### ISSUE TITLE
Error in importing to voice attack

### ISSUE THREAD

**Issue by TheNorwegianBeck** [cmdrmcdonald/EliteDangerousDataProvider#4]
When importing the profile to voice attack it gives me this error message:

Error loading profile data.
[There is an error in XML document (398, 12).]
Instance validation error: 'ConditionElseIf' is nto a valid value for
ActionTypeEnum.

Any way to fix?
Seems like a nice thing to have for Elite.

**Comment by cmdrmcdonald** [comment]
You need to use the latest beta version of VoiceAttack as the previous versions had various issues that prevented this from working.  The current beta version is 1.5.8.14

**Comment by TheNorwegianBeck** [comment]
Thanks for the quick response, this worked!

**Comment by cmdrmcdonald** [comment]
Good to hear.
