### ISSUE TITLE
Can't accsess the plug in due to the enclosed jpg

### ISSUE THREAD

**Issue by CmdrDeMae** [cmdrmcdonald/EliteDangerousDataProvider#40]
Hi there Cmdr,

I'm attempting to get the voice attack plug in working...when I input the required information, I get the following error message...please advise

Kind Regards

Cmdr De Mae

![eddi config](https://cloud.githubusercontent.com/assets/23119400/19805456/78452284-9d0c-11e6-8acc-0199e7122c34.jpg)

**Comment by cmdrmcdonald** [comment]
Sorry to hear that you're having problems.  Please could you explain a bit more around this issue.  The usual process is:

  - enter your email address and password
  - hit 'next'
  - enter the confirmation code
  - hit 'next'

Which of these steps did you undertake, and at which point did this error occur?

**Comment by CmdrDeMae** [comment]
Confirmation code methinks…From where do I find this code,…I’ve received nothing via email

 

Cheers Cmdr.

**Comment by CmdrDeMae** [comment]
36a67c34e561a1bf477622352dd654e442d9a069 is the code I typed in…this is from EDSM…as said I’ve seen no other…hope it clarifies it for you.

 

Thanks

**Comment by cmdrmcdonald** [comment]
You should receive a 5-letter code in an email from Frontier after entering your frontier email and password, this is the code that needs to be applied.

**Comment by CmdrDeMae** [comment]
Thanks for that Cmdr…it accepted the 5 digit code…thanks for that….I’ll be trying it out

 

Cheers
