### ISSUE TITLE
VA plugin never launched

### ISSUE THREAD

**Issue by Gunichou** [cmdrmcdonald/EliteDangerousDataProvider#47]
Hi.
VA is installed in my G:/ drive
I've installed your plugin into G:/Voiceattacks/apps/eddi/eddi.exe
When i luanch VA, i can see plugins are activated but in reality EDDI plugin is not loaded.
I can't execute an external plugin command.

**Comment by cmdrmcdonald** [comment]
What version of VoiceAttack are you using?  It needs to be at least 1.5.12.22.

What happens when you start up the EDDI.exe binary?  Are all of the configuration options in it set up?

If so, then upload your logs with the 'Send EDDI logs to developers' button on the initial EDDI.exe page'

**Comment by Gunichou** [comment]
That's ok with the latest Prerelease
