### ISSUE TITLE
[Enhancement] Spoken text "Subtitles"

### ISSUE THREAD

**Issue by theFisher86** [cmdrmcdonald/EliteDangerousDataProvider#49]
This could be accomplished many ways but it would be nice to have all the text that is spoken either written to a file that could then be used by a separate tool to display on screen or actually have an option for an on-screen console box that just simply shows the spoken text.  Ultimately, for my own purposes, I would like TCE to have an optional window that just shows the EDDI spoke text output.  This would allow for a lot of extend ability whether it's a small script that monitors the file and shows the text on a separate screen/computer or a way that allows other apps to interact with the data coming out of EDDI.  Many people use multiple computers/monitors with ED and it would be cool to have the audio and actual spoken text accessible for other uses.

**Comment by cmdrmcdonald** [comment]
This should be available in EDDI 2.1.  There is an option under the 'Speech responder' tab to allow all speech responder output to be written to a file.

A beta of this is available at https://www.mcdee.net/elite/EDDI-2.1.0-b1.exe - if you have a chance to try this out and let me know if it is now working as expected it would be appreciated.

**Comment by theFisher86** [comment]
Wow, that's fantastic!  Seems to work like a charm for me!

Do you have a relationship with the dev developing TCE at all?  This visual
text output would be really cool if it could be integrated into his app
somehow.  However, if you don't know him or anything I may try my hand at
writing a little python script to just give an overlay with the text output.

It may be worthwhile to add an option in EDDI to "mute voice" when the text
output is enabled.

Thanks for this great app!

**Comment by cmdrmcdonald** [comment]
Available in EDDI 2.1
