### ISSUE TITLE
Voice is too robotic

### ISSUE THREAD

**Issue by Uriei** [cmdrmcdonald/EliteDangerousDataProvider#5]
There is anyway to use the real TTS engine voice instead the modified one this plugin does? Is so distorted I can't understand a thing.

**Comment by cmdrmcdonald** [comment]
At current the voice distorts with the level of hull damage, so if your ship is significantly damaged the voice will be harder to understand.  If your hull is undamaged then there should be no distortion: can you understand the voice in the youtube samples, and does your voice sound similar to that?

In the next release I want to provide the ability to configure the voice, which will allow you to tweak the settings more to your personal preference and audio setup.

**Comment by Uriei** [comment]
In fact, I'm docked with a ship, fully repaired and the voice is horrible, on the youtube videos, the voice is a bit more clear, personally, I prefer no modulation at all.

**Comment by cmdrmcdonald** [comment]
Yes it's possible that the API hadn't been updated with the latest info there is sometimes a bit of lag.

I'll make sure that there is a "no modulation" option for those that prefer the default TTS voice.

**Comment by cmdrjack** [comment]
Even with the modulation effect the voice is very easy to understand. No idea what this guy is even talking about. English isn't even my first language and I have no problem understanding the voice. It's certainly no where near "horrible" either. Please don't change it and keep up the good work, man!

**Comment by cmdrmcdonald** [comment]
Release 1.1 will provide the ability to configure the voice modulation.
