### ISSUE TITLE
EDDI confing not opening after install in windows 10

### ISSUE THREAD

**Issue by orcnet** [cmdrmcdonald/EliteDangerousDataProvider#50]
[Report.txt](https://github.com/cmdrmcdonald/EliteDangerousDataProvider/files/578837/Report.txt)

(This is for EDDI 2, downloaded 8/111/16) After the install the configuration app does not open and I have tried to open manually but it crashes out

**Comment by cmdrmcdonald** [comment]
Please could you send me the contents of your %APPDATA%\EDDI\eddi.log file so that I can take a closer look at this?  Thank you.

**Comment by Helsdottir** [comment]
Now it's not opening for me, but it's writing log file before it dies. Do you want me to paste it here since I can't open the app to use the button inside? I have one with a single run attempt's log in it for brevity

**Comment by cmdrmcdonald** [comment]
Yes please.

**Comment by orcnet** [comment]
Hi managed to get EDDI to fire up after install (forgot to delete the app data previously) but now not getting the email from Frontier to gain access. attached is the zipped log file
Andy Orchiston
Andrew Orchiston
Registered Learning Disability Nurse. 
CQC Clinical Advisor.
Mobile 07792484875
Tel 01636 893880
Home Email andy@orcnet.co.ukAlumni email andrew.orchiston@alumni.nottingham.ac.uk
----Original message----
From : notifications@github.com
Date : 09/11/2016 - 13:43 (GMTST)
To : EliteDangerousDataProvider@noreply.github.com
Cc : andy@orcnet.co.uk, author@noreply.github.com
Subject : Re: [cmdrmcdonald/EliteDangerousDataProvider] EDDI confing not opening after install in windows 10 (#50)
Please could you send me the contents of your %APPDATA%\EDDI\eddi.log file so that I can take a closer look at this?  Thank you.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
  
  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cmdrmcdonald/EliteDangerousDataProvider","title":"cmdrmcdonald/EliteDangerousDataProvider","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cmdrmcdonald/EliteDangerousDataProvider"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cmdrmcdonald in #50: Please could you send me the contents of your %APPDATA%\\EDDI\\eddi.log file so that I can take a closer look at this?  Thank you."}],"action":{"name":"View Issue","url":"https://github.com/cmdrmcdonald/EliteDangerousDataProvider/issues/50#issuecomment-259417346"}}}

**Comment by cmdrmcdonald** [comment]
The file did not come through, please could you try again?

**Comment by orcnet** [comment]
All sorted now
