### ISSUE TITLE
Companion json error 2.0.7

### ISSUE THREAD

**Issue by Helsdottir** [cmdrmcdonald/EliteDangerousDataProvider#51]
Updated from 2.0.6, now companion throws a json error too long to type manually here when I try to connect companion .

Basically says an unexpected character encountered while parsing value P line 0 pos 0

**Comment by cmdrmcdonald** [comment]
This is due to Frontier's JSON API returning non-JSON in some situations.  This should be handled in EDDI 2.0.8 (now available) but if the problem persists you can remove your %APPDATA%\EDDI\credentials.json file and log in again through the EDDI UI to clear this.

**Comment by Helsdottir** [comment]
FYI .8 worked great. I did have to delete my credentials.json file too

Thanks for the great program!
