### ISSUE TITLE
Another spoken language

### ISSUE THREAD

**Issue by Gunichou** [cmdrmcdonald/EliteDangerousDataProvider#53]
Hi there.
I love Eddi and I would like to contribute.
I looked quickly  the source code and i and I would like to have the opportunity to hear the TTS in French.
On visual studio I saw that we had a named party "EddiSpeechService".
I imagine that the vocal part is played in this part of the code but i'm not sure...
If anyone could help me figure out what to change it would be cool and would make EDDI even more popular for French users.

**Comment by cmdrmcdonald** [comment]
EDDI has the concept of personalities.  If you start up EDDI, go to the 'Speech responder' tab and hit the 'Copy personality' button you can create a new personality.  Here you can customise the responses, including translating them in to another language.

Others are also working on translation to different langauges, so you might want to look at the EDDI thread on the Elite forums to see who is already doing what.
