### ISSUE TITLE
Constant upgrade reminders and 'not set' issues

### ISSUE THREAD

**Issue by GalacticZero** [cmdrmcdonald/EliteDangerousDataProvider#54]
I've been using EDDI for a while now. Since well before 2.0.4 and it was always working fine. When 2.0.6 came out, it started reminding me of it every time I started up VoiceAttack. For a while I wasn't going to upgrade it because it was working for me. I finally gave in to do it. Even after upgrading it, it kept telling me that 2.0.6 was out. Also after telling me that, it would constantly scroll 'not set' through my VA window. I had to hit the stop command button to get it to quit. 

Today I fired up VA again and it told me about 2.0.9. I thought that might fix it. Download, install, restart VA, same thing. Keeps telling me each time I launch VA that 2.0.9 is available and scrolls that 'not set' thing constantly across the screen. I let it go for a while one time and it never stopped. I can't get it to do things like "damage report" or other EDDI commands, either. It's just like it isn't working right. On 2.0.6 it would at least run EDDI in the background and tell me the usual stuff that it is supposed to, but it just will not work with VoiceAttack any more.

I have always installed it to the same directory. I have not changed anything at all in VA. I don't know what is going on with it. I've gone and double checked that all the settings are find and haven't changed. It is just getting super annoying. Can anyone help me fix this so it will go back to normal?

**Comment by cmdrmcdonald** [comment]
It sounds like you haven't removed the relevant EDDI commands from VoiceAttack when upgrading.  Please ensure that you carry out all of the steps listed at https://github.com/cmdrmcdonald/EliteDangerousDataProvider/blob/master/VoiceAttack.md#upgrading-from-eddi-1x and this should fix the issue.

**Comment by GalacticZero** [comment]
I am fairly certain I had tried all of the before when it first came up even though I was pretty sure I hadn't used the 1.x version of EDDI. I suppose I will try again. *sigh*
