### ISSUE TITLE
System Distance From home doesn't work 2.0.9

### ISSUE THREAD

**Issue by qasz** [cmdrmcdonald/EliteDangerousDataProvider#55]
`    {if system.distancefromhome:
        {Occasionally(7, "{OneOf(\"You are\", \"Current location is\", \"You are now\")} {Humanise(system.distancefromhome)} lightyears from {OneOf(\"home\", \"{P(homesystem.name)}\")}.")}
    }`

Distancefromhome variable is always zero, it was working correctly in the previous version 2.0.8

**Comment by cmdrmcdonald** [comment]
This does appear to work correctly.  Are you in known space or exploring outside the bubble?  Also, can you confirm that your home system and station are set correctly.

**Comment by qasz** [comment]
It works, I added home station, but it worked for me before without home station. I'm about 22k ly from the bubble.
