### ISSUE TITLE
Random "<ship_name> refuelled" chat after fuel scooping - 2.0.10

### ISSUE THREAD

**Issue by PurpleGranite** [cmdrmcdonald/EliteDangerousDataProvider#56]
After upgrading to VA 1.6 and EDDI 2.0.10, after fuel scooping, EDDI occasionally announces "<ship_name> refuelled", generally 5-10 seconds after ED announces "fuel scooping complete".

**Comment by cmdrmcdonald** [comment]
This is expected behaviour, as fuel scooping is a form of refuelling.  If you want to change this behaviour you can copy the default EDDI personality and alter the 'Ship refuelled' script.

**Comment by PurpleGranite** [comment]
OK - accept that - don't understand why this didn't happen in previous versions however.
