### ISSUE TITLE
Feature:  Use ICAO Phonetic Alphabet for appropriate body names

### ISSUE THREAD

**Issue by PurpleGranite** [cmdrmcdonald/EliteDangerousDataProvider#57]
It would be nice to have a toggleable option to speak some body names using the ICAO Phonetic Alphabet to increase the clarity of those spoken names - best as a toggle as it may be annoying to some.

For example, when speaking "COL 359 SECTOR IE-G B15-1 A", read as "Charlie Oscar Lima Three Five Nine-er SECTOR India Echo dash Golf, Bravo One Five dash One, Alpha".  It's a little longer, but much clearer to hear.

This might need a whitelist of star names to avoid reading in this way - if for example any part of the name containing a number or three or less letters is converted this way, stars such as "Sol" would need to be excluded to prevent them being incorrectly converted.

**Comment by cmdrmcdonald** [comment]
Although EDDI does have a phonetic alphabet (NATO, in fact), it's not immediately obvious what should be spoken as what.  The example that you gave should probably be 'col 3 5 9 sector india echo dash golf bravo 15 dash 1 alpha, as 'col' is commonly known as the name even though it is an abbreviation.

The code that currently works out what to say phonetically and what not could do with a tidy-up, at which point I'll see if I can put enough in place rules-wise to make this viable.

**Comment by cmdrmcdonald** [comment]
EDDI 2.3 (currently in beta) comes with an option to enable ICAO for star system and body names.
