### ISSUE TITLE
2.2.02 update docking issue

### ISSUE THREAD

**Issue by sheazle** [cmdrmcdonald/EliteDangerousDataProvider#58]
The 2.2.02 update today seems to have broken the parsing of the Docked event from the player journal. After docking there is no speech and the ((EDDI docked)) VA command is not triggered.

From patch notes:
- The player journal entry for when docking at a station now reports the station faction economy, government, etc: (and the info on entering a starsystem names the properties as SystemEconomy, SystemGovernment etc to be explicit about what the values refer to)

**Comment by cmdrmcdonald** [comment]
This should be fully fixed in 2.0.11
