### ISSUE TITLE
Unable to get companion verification code by EDDI

### ISSUE THREAD

**Issue by CmdrSakz** [cmdrmcdonald/EliteDangerousDataProvider#59]
Good Evening Sir.

I just downloaded your EDDI and as I get at the configuration for the Companion App, I do not get any email reply with the code.
\
As I send data to companion app from Frontier from inside your EDDI, I get this message, that is been asked to me, by the program itself, to report to you:

Unexpected problem
EddiCompanionAppService.EliteDangerousCompanionAppIllegalStateException: Service in incorrect state to provide profile (NEEDS_CONFIRMATION)
  in EddiCompanionAppService.Com.CompanionAppService.Profile()
  in Eddi.MainWindow.companionAppNextClicked(Object sender, RoutedEventArgs e)

I sent correctly my Email and pw of registration of the game but no email of confermation code.

Any help or hint?

Thanks in advance and keep going with your work, you are doing a really great job.

Cheers

Cmdr Sakz

**Comment by CmdrSakz** [comment]
Ok...now no more message of Unexpected error.......it tells me "Username or Password incorrect"

O M G

Still waiting for help as u have some spare time 

Cheers

Cmdr Sakz

**Comment by cmdrmcdonald** [comment]
Have you definitely entered the correct confirmation information, including in the correct case?

If so then please try removing the %APPDATA%\EDDI\credentials.json file and trying again.

**Comment by CmdrSakz** [comment]
All ok now thanx, I made a big mistake with mail I was logging...guys at frontier fixed that mess and now I can normally log into Companion App....it is fantastic!!!!!!!!!
Thank you a lot and keep going with EDDI ..... is a very nice app!!!!!!!!!!!
Cheers ( and a couple of beer for you)
Cmdr. Sakz
