### ISSUE TITLE
Feature - Power Play support

### ISSUE THREAD

**Issue by TROG111** [cmdrmcdonald/EliteDangerousDataProvider#60]
Just a thought.  Is there any way to add features to support Power Play.  We have a group of commanders and would like to be able to track data in various systems, e.g. faction influence, faction state, fortification, undermining levels, bounties claimed, crime reports, traffic reports.

I was wondering if this tool could be used to capture this data as our cmdr travel between systems?

Any thoughts?

**Comment by cmdrmcdonald** [comment]
Unfortunately none of the data you have mentioned is available in the journal, and hence not available to EDDI.  If you raised an enhancement request to Frontier to add this information to the journal and it was actioned I would be able to add this information to EDDI.

**Comment by TROG111** [comment]
Actually this is not quite true.  The journal files does contain records of PowerPlay loading and delivering of fortification, preparation and expansion commodities by the individual commanders.  However you do not appear to be supporting these.

Example of current journal file entry for PowerPlay:

{ "timestamp":"2016-11-21T03:58:20Z", "event":"PowerplayCollect", "Power":"Felicia Winters", "Type":"$federaltradecontracts_name;", "Type_Localised":"Liberal Federal Packages", "Count":50 }

These events also do not appear to be picked up by your commodity load and commodity purchase event handlers, even though they consume cargo space as per other salable commodities.

So without recoursing to Frontier, which we both know would be a waste of time and energy, it should be possible for EDDI to extract the PowerPlay commander events from the journal and generate a periodic dump.  Obviously I could also write a standalone module/application to do this to meet our specific needs if you do now wish to extend EDDI further.

**Comment by cmdrmcdonald** [comment]
I haven't looked at these events, but from what I can tell they are commander-specific information rather than system-wide.  That said, I will take a look at adding these.  Please could you explain what information you want from these events?  Thank you.

**Comment by cmdrmcdonald** [comment]
There should be a number of Powerplay-related events available in EDDI 2.1.  Note that at current the journal event created when voting for system preparation is bugged, in that it doesn't provide the system for which the vote is being cast.  This has been raised with Frontier and when it has been fixed I will update EDDI's information accordingly.

A beta of this is available at https://www.mcdee.net/elite/EDDI-2.1.0-b1.exe - if you have a chance to try this out and let me know if it is now working as expected it would be appreciated.

**Comment by cmdrmcdonald** [comment]
Powerplay events available in 2.1
