### ISSUE TITLE
StationDetails function not populating station commodities

### ISSUE THREAD

**Issue by TROG111** [cmdrmcdonald/EliteDangerousDataProvider#64]
If I call the StationDetails function it does not populate the stations commodity list.

**Comment by cmdrmcdonald** [comment]
The only commodity information available inside EDDI is for the current station as obtained from the companion API.  Market data is both large and dynamic, and EDDI wasn't build with this in mind.  I'll take a look to see if it would be possible to add this information in some way.

**Comment by TROG111** [comment]
Even if it only held the HomeStation/HomeSysem market data this would be a great improvement.

**Comment by cmdrmcdonald** [comment]
EDDI is limited in the realtime data it can obtain.  Perhaps if you could explain specifically what data you are after, when you want it, and what you want to do with it, I can find a way to help.

**Comment by TROG111** [comment]
Im sorry i was a bit tired last night when I replied to you.  Honestly I do very much like the concept of EDDI and am very keen for it to succeed.  I run a two screen desktop and while my graphics card appears to no longer be able to support ED2.2 (it worked fine before) I now use the second screen for companion apps and Power Play communications windows that help to augment the ED experience.

I have a number of 'wishes' and will try to explain them:

1) During weekly PP fortification nights (every wednesday night) we tend to spend hours hauling PP fortification packages from the powers home system to 60+ control systems. I would very much like EDDI to provide a back haul commodity that I can buy from each of the control system stations I visit (up to 5-6 visits each station).  I could use EDDB, but EDDI seems a far more elegant solution.  Therefore, what I need is the ability to create a reference commodity list (that is where I was hoping using StationDetails would work) against which when I dock at each station EDDI will do an automatic lookup for profitability against my reference commidity list and not just galactic average.  Seems simple enough.

I can think of a number of solutions you might consider:
1a) fix the StationDetails function so that (as per the reference documentation) it does indeed return an array of commodities for the station.
1b) extend the HomeSystem capability in EDDI to enable a HomeStation to be defined which will have a loaded commodity list.
1c) provide the ability for the EDDI scripts to maintain some persistent data (user defined data that persists across EDDI scripts) and thus we can define our own arrays of data which can be referenced across multiple scripts - and through this we can create the equivalent of a HomeStation functionality.
1d) use EDDB (or is it EDDN) as your source of data for StationDetail as this may be more reliable than the FDEV calls?  

1c solution would also enable users to maintain/track their own data (for example, track bounties awarded or missions completed - currently there is a bug in ED whereby if you complete a skimmer mission on planet, when you return to ship the mission list disappears from the left panel and is not available until you next jump, we could work around this with EDDI if it had persistent data and thus we could track each mission, or even just know if there are any active missions remaining).  

I guess 1c may be difficult to implement within the Cottel environment?  But Im sure with a bit of thought it can be done - and yes I know all of the arguments from language purist about 'side effects' and data encapsulation.

I appreciate the difficulties of interfacing in an asynchronous environment in terms of data not being returned in a timely manner from the external services.  Im happy to work around this ('I am sorry commander the data you have requested in not available at the moment'), but it would be helpful to have some form of status that can be checked by the script to know if the data that is being access is up to date or if it is old and has not been updated due to the external system not responding.

I can give you another example of where this is happening.  I have amended the Docking granted script so that it informs me of the condition of my ship before I commence the docking process.  Things like if the docking computer is damaged and off-line etc....  However, on a number of occasions EDDI has reported the incorrect ship status (once saying ship is undamaged when actually I had 7% hull remaining and most internal modules were damaged or off-line - and then to rub salt into this, after I had repaired the next time I went to dock it told me I had 7% hull!)

I do understand the problems inherent in EDDI actually trying to track data on behalf of the user and outside of ED.  There is a high probability that this would become out of step.  However,  I also use ED Engineers and this app simply allows the user to update the data it stores and therefore leaves it to the user to ensure consistency with the materials actually in the ship on ED.

2) EDDI needs to support Power Play.  There are 3 basic power play commodities which you do not recognise - Preparation Packages, Expansion Packages and Fortification Packages.  Each of these takes up cargo space in exactly the same way as basic commodities.  They also appear in exactly the same way on the right hand inventory panel in the cockpit.  As a minimum (even if you dont support Power Play events - such as Load PP Commodity and deliver PP commodity - both of which are reported as events in the journal file) this needs to be considered when reporting on cargo space, jettisoning cargo (as PP commodities can be jettisoned) etc....

Personally, I think the easiest thing for you to do would be to simply support the 3/4 PP journal events and include the PP commodities as cargo (I dont know what cargo/commodity ID is assigned to them in the journal).

3) Maybe (and this is much lower priority) provide a command window capability in EDDI so that while flying we can speak (by which I mean press a button) directly to EDDI. Currently I have implemented a script inside Message send event which reads the message I have typed in the Local communication channel and if it matches a specific command, then EDDI executes the appropriate sub script.  This enables me to request information from EDDI directly instead of only when a specific ED event occurs.  I have three scripts inside there:
- Stations report - whereby EDDI reports on all stations in the current systems with details of Fueling/Repairing/Restocking/PadSize - this is very helpful when entering a new system for the first time in a ship that is damaged or out of fuel
- Damage report - whereby EDDI reports on the current health of the ship - again this is very useful when escaping from a bad situation and you dont really want to be looking at the righthand module panel.
- Cargo report - you have seen this script, EDDI reports on the current content of the cargo racks

I could also envisage an Ammunition report also being of use.

A more elegant solution would be for EDDI to provide a small dashboard with user definable buttons against which scripts such as these could be assigned.  Or maybe this would be a companion application to EDDI if you wish to keep EDDI as a backend/data interchange and voice service.

Anyway, I would be very happy to work with you further on these ideas if you are interested.  I havent done any coding for 10-15 years and although I can read your code relatively easily, I dont have a clue how to actually build/compile something like EDDI, I am from the generation of Makefile and cc.

Many thanks for your patience, I am a grumpy old man.

**Comment by cmdrmcdonald** [comment]
There's a lot here, we'll need to tackle them one at a time.  I'll start with market information.

First, it's going to be useful to understand how the flow of market information works.  All market information comes initially from the Frontier companion app API.  When a third-party tool obtains this information it sends it to EDDN, which distributes it out to whomever is listening.  One of these listeners is EDDB, which updates its local database with the market information it sees.  EDDB does not have an API, but it does generate nightly dumps of information.  These dumps are picked up by various tools, including a backend server for EDDI, that makes this data available for EDDI to use when it wants to know about a system.

Traditionally it didn't much matter if the data was a day or so out of date; EDDI was built originally to provide information to explorers and stars and planets don't change very often.  Market data is a different matter: it is possible to obtain it, but it will generally be out-of-date by at least 24 hours and quite possible a lot more (as it depends on someone visiting the market with a suitable tool running, and that tool sending the updated information to EDDN) and obviously this can lead to the information being presented being inaccurate.

It's also worth understanding that EDDI was originally built as a system to provide spoken responses to in-game events.  It is designed to work in the face of missing data, as the companion app API is hardly the most reliable piece of software.  Sometimes information is out-of-date, as you have seen, and sometimes it just returns a flat 'Profile unavailable'.  EDDI works on a best-efforts basis but if, for example, the player is docked at station A and the API returns data for station B there isn't a lot that EDDI can do about it without going down the rabbit hole of conditional retrying (and even then bear in mind that FD has a fair use policy on their API, so having hundreds of clients retrying data fetches every few seconds in the hope that the data has refreshed isn't going to make them very happy).  And when the data does show up the chances are that the user has moved on (bought/sold cargo, fixed their ship up, purchased fuel etc.) so that even though the data might be more up-to-date it won't be accurate in all cases.

So, realistically there are a couple of options.  The first is to use the historical information, and assume that it won't be too far out-of-date.  This will result in information that is usually relatively accurate, but not always so.  The second is to separate out the physical act of docking from the obtaining of data about the station at which the player is docked, and carry out the latter in some sort of server-friendly polling.  The first part is relatively easy, the second less so.  For a first pass I'm inclined to have system details include whatever commodity information EDDB knows about, then let the companion app data overwrite it if it's valid.  That will ensure that you will have some data (for stations for which there is any data at all) and the latest data if it's available, but won't handle the degraded situations (e.g. companion API running slow).  I've started some work on this, mainly on the server side to incorporate the market information for stations, and will see how that works out.

**Comment by TROG111** [comment]
Wow, I wasnt expecting you to get onto it as quickly as that! Many thanks.

A few thoughts

1) while it would be fantastic to have up to the minute market data (obviously this is wanted by those that are looking to maximise trading profit), I think there could be scope for just providing 'reasonably recent'.  The key here probably relates to the supply/demand, if these are sufficiently high, then you can rely on data that is much older than when the suplly/demand is quite small. So perhaps the following would be reasonable:
a) use the EDDN data and provide the datestamp and supply/demand information
b) the script then can decide if the data is good enough
c) f the script/user wants better data, then have a secondary parameter which tells EDDI to try to pull from API.

In this way the commodities can be pulled fromEDDN as soon as the ship enters the appropriate system (simply pull all stations and commodities) which should permit enough time to let things settle before the ship get anywhere near a station.  Then and only if the script has asked for it, use the API to pull commodity data only when the docking request event occurs so that it is available when the docked event occurs.

For me the key thing would be for EDDI to provide an indication to the script on the status, i.e. where the information came from and if there was an unsuccessful attempt to retrieve the more up to date copy, so that the script can tell me.  

BTW, I am still getting significant discrepency in the ship status information, so I guess the same sort of issue is at play in retrieving the ship damage information.  I will check the damage routine and calculation (I'm still using your base script) because 80-90% of the time EDDI is reporting the incorrect hull damage information (compared to what is displayed in the cockpit).  Unlike the commodity information though, ship damage needs to be accurate or not provided, so again if EDDI provided a status indicator for ship data so that the script could decide whether to provide it or just keep quiet.

**Comment by cmdrmcdonald** [comment]
This has been significantly reworked for EDDI 2.1.

Station details will now include the commodity information from EDDB by default.  As and when the user visits a given station, if updated market information is available then the local EDDI database will be updated with this information along with the internal copy of the data.  Thus, station.commodities should always have the most up-to-date version of the information that can be obtained.

To ascertain the age of the data, station details also carries a commoditiesupdatedat value, which is a timestamp relating to either when the data was last updated in EDDB or when the data was last obtained from the Frontier companion API server.  You can use this, in conjunction with the SecondsSince() call, to check the freshness of the data.  For example:

    {set hoursold to SecondsSince(station.commoditiesupdatedat) / 3600}
    {if hoursold > 1:
        Warning: market data is {Humanise(hoursold)} hours out of date.
    }

In future there is a plan to have a separate event trigger whenever market data for the current station is obtained and found to be newer than EDDI's current information.  This is MarketInformationUpdated, but it is not yet wired in.  I need to work through the permutations to see where it makes sense to add this, and if there is some way of having asynchronous updates.

A beta of this is available at https://www.mcdee.net/elite/EDDI-2.1.0-b1.exe - if you have a chance to try this out and let me know if it is now working as expected it would be appreciated.

**Comment by TROG111** [comment]
I had a go at a script to run when I dock to compare and find the most profitable commodities compared to my home station (script below).  Although it appears to work, that is I am getting a list of commodities for both local station and my home station, the sell prices for my home system are clearly wrong (below is also transcript of the EDDI output).  

EDDI is correctly populating the names of the commodities on demand at my home station (as the names are matching to those on sale at the local station).  But for some reason the sellprice that is available is incorrect (usually in the 10s or 100s of credits inflated - actually the sell price is closer to the demand value).

Anway, here is the script and output:

-----------------------------------
Downloading station commodities..... standby....
{set thisstation to station}
{set homestation to StationDetails(homestation.name,homesystem.name)}
{Pause(5)}
{set best to 0}
{set secondbest to 0}
{set thirdbest to 0}
{for localcommodity in thisstation.commodities:

    {if localcommodity.stock > 100:
    {if localcommodity.buyprice > 100:

        {for homecommodity in homestation.commodities:
            {if homecommodity.demand > 100:
            {if localcommodity.name = homecommodity.name:
            {if homecommodity.sellprice > localcommodity.buyprice:
                {set potentialprofit to 0}
                {set potentialprofit to homecommodity.sellprice - localcommodity.buyprice}
Match {homecommodity.name} with {potentialprofit} profit per ton (buy price equals {localcommodity.buyprice}. sell price equals {homecommodity.sellprice}).

                {if potentialprofit > best:
                    {set thirdbest to secondbest}
                    {set thirdbestcommodity to secondbestcommodity}
                    {set secondbest to best}
                    {set secondbestcommodity to bestcommodity}
                    {set best to potentialprofit}
                    {set bestcommodity to localcommodity}
               |elif potentialprofit > secondbest:
                    {set thirdbest to secondbest}
                    {set thirdbestcommodity to secondbestcommodity}
                    {set secondbest to potentialprofit}
                    {set secondbestcommodity to localcommodity}
               |elif potentialprofit > thirdbest:
                    {set thirdbest to potentialprofit}
                    {set thirdbestcommodity to localcommodity}
               }
            }}}
        }
    }}
}

{if best:
    The top profitable commodities for trade with Rhea is {bestcommodity.name} with a projected profit of {best} per ton.
    {if secondbest
       Additionaly, {secondbestcommodity.name} with a profit of {secondbest} per ton,
       {if thirdbest:
           and, {thirdbestcommodity.name} for {thirdbest} per ton.
         }
    }
|else:
    No potentially profitable commodity trades with {homestation.name} have been identified.
}
-------------------------------------------------------------------

Downloading station commodities..... standby....  Match Consumer Technology with 113439 profit per ton (buy price equals 6696. sell price equals 120135). Match Synthetic Meat with 13212 profit per ton (buy price equals 132. sell price equals 13344). Match Progenitor Cells with 54073 profit per ton (buy price equals 6679. sell price equals 60752). Match Advanced Medicines with 264239 profit per ton (buy price equals 1093. sell price equals 265332). Match Basic Medicines with 256337 profit per ton (buy price equals 249. sell price equals 256586). The top profitable commodities for trade with Rhea is Advanced Medicines with a projected profit of 264239 per ton., Basic Medicines with a profit of 256337 per ton, and, Consumer Technology for 113439 per ton.

**Comment by TROG111** [comment]
I'm sorry, I couldn't work out how to stop github from formatting the code, I hope that you can read it.

**Comment by TROG111** [comment]
OK, now this script seems to be working?

**Comment by TROG111** [comment]
OK, its working occasionally.  Te next station I visit I got silly numbers again.

**Comment by cmdrmcdonald** [comment]
EDDI won't work properly with the 2.1 beta (or indeed any beta of Elite) because there is no companion API for the beta servers.  This means that the data that you are obtaining will be for whatever port you are docked at in live.

The reason that you're seeing 'Rhea' is that it's hard-coded in the script.

The sell prices do look inflated.  It's quite possible that I have mixed up the variables on import from CSV; I'll take a look at this.

**Comment by TROG111** [comment]
When I said Beta 2.1, I mean Beta 2.1 of EDDI (I think thats what you called it?)

Yep, I found the hard coding and fixed

**Comment by cmdrmcdonald** [comment]
Sorry, yes.  Too many betas going on.

There was an issue with the CSV import that mixed up the sell price and demand.  This has been fixed now, but you might want to remove %APPDATA%\EDDI\EDDI.sqlite before you test because it will contain cached data.

**Comment by cmdrmcdonald** [comment]
Available in EDDI 2.1
