### ISSUE TITLE
EDDI 2.0.10 did not report "new update available"

### ISSUE THREAD

**Issue by FireSammy** [cmdrmcdonald/EliteDangerousDataProvider#65]
As the headline says, i found the latest update by checking the forums. 2.0.10 only gave the "initialized" -blue text into VA logbox. Haven't seen others reporting this issue.

Anyways 2.0.11 seems to be working fine and the ((Docked)) -command seems to be fixed. EXCELLENT!

**Comment by cmdrmcdonald** [comment]
Did EDDI not say that there was a new upgrade available?  It should be independent of VoiceAttack.

Did you receive a spoken notification for 2.0.13?

**Comment by FireSammy** [comment]
Yes EDDI 2.0.12 gave spoken notification for new update 2.0.13, but did not type/notify it into the VA log box. I do not recall did i open the EDDI -standalone shortcut from my desktop,- or as usual, only the VA? Sorry, my bad.

Anyways, i still think it is important/good to have updates notified also in the VA logbox (with the red text -as it used to do), as some of us are only using headset for audio, and will miss the notification if one does not have the headset on, when opening the apps,-or the OS. For me the VA is scheduled to open with the Windows and i use EDDI with the VA. Normally i just wait for the VA's EDDI initialized -text notification and go from there without opening the standalone EDDI as advised.

Fex, i usually put the headset only when i'm planning to open stuff (anything) with audio, and not have it on when i do other things with the machine, you know

I don't think this is a critical problem, but i would humbly request if you could look into this -if nothing else but preventing any possible inconvenience/problems with EDDI -just because missing the latest update, not to even mention people reporting problems here because of this, etc. and you spending your valuable time responding to these things m8 ;)

Best and humble regards to you sir and thank you again for doing EDDI! Latest updates are truly fantastic, and i'm back on tweaking my VA profile again, after basically quitting it completely :)

**Comment by cmdrmcdonald** [comment]
With EDDI 2 many notifications have moved to voice because there is no longer a requirement for VoiceAttack to be present.  I will see what can be done for the VoiceAttack responder to pick up on version information and provide a suitable report in the VoiceAttack window.

**Comment by cmdrmcdonald** [comment]
Reworked for 2.1.  This will now provide appropriate information in the VoiceAttack log if available.
