### ISSUE TITLE
coriolis.edcd.io issues

### ISSUE THREAD

**Issue by denali1** [cmdrmcdonald/EliteDangerousDataProvider#66]
There are a couple of issues with shipyard export that I've found.

`https://coriolis.edcd.io/outfit/type-7_transporter/0patfFflidasdf52j2j--000203010505044c03030124.Iw18aQAA.CwBj4RnaQvfkAv==.H4sIAAAAAAAEAPsPAAAAAP8BAAAA?bn=Rolling%20Thunder%202`

The above is an incorrect URL.  It should read as:

`https://coriolis.edcd.io/outfit/type_7_transport/0patfFflidasdf52j2j--000203010505044c03030124.Iw18aQAA.CwBj4RnaQvfkAv==.H4sIAAAAAAAEAPsPAAAAAP8BAAAA?bn=Rolling%20Thunder%202`

The next one, I can't figure out what's wrong with it.  It generates a blank page on Coriolis.

`https://coriolis.edcd.io/outfit/asp/0pftfFflidfsnf5272718182e2e02060f0k05B2v6582t242f.Iw18WQAA.CwBj4RnbJiA=.H4sIAAAAAAAEABWOsRLBQBiENyIkMSYREUmhkKDgCTRGa1ReQMcLKFQpdGjNUJnR67RaPe+hUWgY-Pau2LnZ73Zv4S0AFM8aULoLjxYcdMCZf0XM2Y9GprIhdHzek8dbxJ-SDCf0RPcuJtGTbrjNAv7OAso9oiTNkBv1JbssJc2BAcR9lthKWkrENFYM5JwOUGtwhjugJIHLqGUcGch9YqI1C92xQu0S4I3UnCE7xY6sPHnI-5OTR5TykdNV0wrRXqHbiygoA9WrcuUPaIe6au8AAAA=?bn=Wayfairing%20Stranger`

If I can provide any other information, please let me know.

**Comment by cmdrmcdonald** [comment]
These should all be fixed in 2.0.13.
