### ISSUE TITLE
Companion app connection needs reset every reboot.

### ISSUE THREAD

**Issue by GobleSt** [cmdrmcdonald/EliteDangerousDataProvider#7]
As the title says...every boot up I need to run the config and reconnect...

**Comment by cmdrmcdonald** [comment]
Thanks for reporting this.  Changes have been made for the 1.1 release that should alleviate this issue.

**Comment by GobleSt** [comment]
Awesome.  Let me know and I will test.

On Tue, Mar 15, 2016 at 12:01 PM, cmdrmcdonald <notifications@github.com>
wrote:

> Thanks for reporting this. Changes have been made for the 1.1 release that
> should alleviate this issue.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
>
> https://github.com/cmdrmcdonald/EliteDangerousDataProvider/issues/7#issuecomment-196896468
>



-- 
Steve Goble
