### ISSUE TITLE
2.0.13 EDDI Companion APP

### ISSUE THREAD

**Issue by CMDRNotJoe** [cmdrmcdonald/EliteDangerousDataProvider#70]
[This is the error](http://i.imgur.com/oye77ec.jpg)

**Comment by sabreqld** [comment]
I get a similar one that reads [NEEDS_LOGIN]
![eddi](https://cloud.githubusercontent.com/assets/16849278/20997808/95cc3028-bd54-11e6-9e7b-406a8b465e3e.JPG)

**Comment by cmdrmcdonald** [comment]
Please shut down EDDI, remove your %APPDATA%\EDDI\credentials.json file and try again.

**Comment by Azaun** [comment]
cmdrmcdonald's solution has resolved this issue for me.

**Comment by sabreqld** [comment]
Aye, same for me.  Thank you!

**Comment by sabreqld** [comment]
Additional: 
The Companion App keeps disconnecting itself and I have to reenter my login every 48 hours or so.
This may be server side, any changes that you are aware of?

**Comment by cmdrmcdonald** [comment]
I haven't heard of this as a general issue, although Frontier's serves do go through phases of mass disconnections.  EDDI does try to reconnect, so if there is no luck then it's a more persistent problem on Frontier's side.
