### ISSUE TITLE
Cant get voiceattack to work with EDDI to script journal events

### ISSUE THREAD

**Issue by arelusmaximus** [cmdrmcdonald/EliteDangerousDataProvider#71]
First of all THANK YOU EDDI is FANTASTIC !!! with VR it adds so much more ot the immersion in the game.

I currently have a script in voiceattack which changes my vlc playlist to "docking music" when I request docking.  What I want to do is to trigger a script to do this when EDDI reports that the docking request has been accepted.

I also want to use this kind of functionality for things like shields down and shields back up etc.

When I attempt to do this with voiceattack it doesn't seem to be getting the information.  However the EDDI scripts are working.  So for example when I get a docking request granted EDDI informs me of station information etc.

I'm using the latest Beta of voiceattack and the plugin shows as initialized.  What am I doing wrong?

I appreciate your help

Arelus

**Comment by cmdrmcdonald** [comment]
Please could you take a look at https://www.youtube.com/watch?v=VQbR8SfCTRk ? This shows how to set up a command in VoiceAttack that responds to an EDDI event.  If you have any further issues after following this please re-open this issue.  Thanks.
