### ISSUE TITLE
Rounding function

### ISSUE THREAD

**Issue by omega9380** [cmdrmcdonald/EliteDangerousDataProvider#73]
Could you add a function that rounds to X decimal points?  I created a script that reports the fuel level as a percentage.  The Humanise function seems to just knock off all decimals.  Thats fine if my level is, say, 54.2%.  But if my fuel level is at 73.9934%, Humanise reports 73%.  I would like to round it to 2 decimals, so EDDI reports "73.99"% fuel.  Just a thought, thanks!!!

**Comment by sabreqld** [comment]
My script works

![image](https://cloud.githubusercontent.com/assets/16849278/21076502/b2179d5a-bf78-11e6-8fee-b853cb54837e.png)

**Comment by omega9380** [comment]
Yes, that works when using VAs rounding function.  However, for those who don't use VA or don't want to have to recreate every action from EDDI in VA just to get EDDI to round some values, something as simple as {round(event.fuelused, 2)} would be very helpful.

**Comment by cmdrmcdonald** [comment]
Cottle has a built-in rounding function.  Documentation is at http://r3c.github.io/cottle/
