### ISSUE TITLE
EDDI 2.1.0-b1 - Some VA variables not being set

### ISSUE THREAD

**Issue by omega9380** [cmdrmcdonald/EliteDangerousDataProvider#74]
I posted this in the EDDI thread of the Frontier forums, but wanted to put it here as well, seeing as how it looks to be a bug.

There seems to be a problem with the ((EDDI commodity purchased)) and ((EDDI commodity sold)) actions. Before updating to the 2.1 beta of EDDI, the following variables were working fine. Now, they are all being "Not set". VA reports that the decimal token could not be converted when I send them into VA variables for rounding or math functions:

{DEC:EDDI commodity purchased price}
{DEC:EDDI commodity sold profit}
{DEC:EDDI commodity sold price}

Also, on the ((EDDI ship refueled)), ((EDDI ship rearmed)), and ((EDDI ship repaired)) actions, the "price" variable is not being set on any of these.

I tried logging out and reconnecting the companion app, but that didnt work. I did not expect it to, all of those variables should be scraped from the Journal.

I am also having trouble finding "setJsonValues" in the log. Im looking for the new VA variables you were talking about, but the only setJsonValues entries in eddi.log seem to be setting null values.

Let me know if you need my verbose logs.  Thanks!!!

**Comment by omega9380** [comment]
OK.  Upon enabling verbose logging in EDDI and parusing the new log file, I have discovered that it appears you changed all variables that return any credit values from decimals to integers and that is why they are not set in my VA actions.  Sneaky of you!  You can go ahead and close out this issue, and I am REALLY looking forward to the new VA documentation!

**Comment by cmdrmcdonald** [comment]
EDDI shouldn't be changing values from decimals to integers, so this is a bug.  I'll take a look and see what's going on.

**Comment by omega9380** [comment]
Ah.  It kinda made sense to me to have credit values as INTs anyway, you cant have .48 of a credit.  Although I could be wrong!

**Comment by cmdrmcdonald** [comment]
The problem with ints is that they are limited to a relatively small maximum size, so when people have credit balances in the billions ints are not large enough to hold them.

**Comment by cmdrmcdonald** [comment]
Fixed for next release.
