### ISSUE TITLE
Feature - RedeemVoucher event

### ISSUE THREAD

**Issue by omega9380** [cmdrmcdonald/EliteDangerousDataProvider#75]
Just curious if you are working on an action for the RedeemVoucher event from the journal.  I see that EDDI recognizes the event from the EDDI.log file, there's just no associated event.  I'm working on a kind of "checkbook register" CSV file using VA's "Write text to file" and EDDI events.  There is an event when you receive bounty vouchers and combat bonds, but that event is not when you get the actual credits.  That happens when you redeem the actual voucher.  Also, wing trade dividends only fire with RedeemVoucher events in the journal.

**Comment by cmdrmcdonald** [comment]
It is on the list, but I'm not planning to add this until FD add the information about where the voucher comes from.

**Comment by omega9380** [comment]
Not sure what u mean by where it comes from.  There is a "type" entry for all of my RedeemVoucher events, is that what you mean?  For example: 
`{ "timestamp":"2016-12-10T14:34:39Z", "event":"RedeemVoucher", "Type":"trade", "Amount":4463 }`
is for a trade voucher and 
`{ "timestamp":"2016-12-08T22:37:01Z", "event":"RedeemVoucher", "Type":"bounty", "Amount":93720 }`
is for a bounty voucher.  Or do you mean the faction the money comes from?

**Comment by cmdrmcdonald** [comment]
Yes, waiting on information on the faction against which the voucher is redeemed.

**Comment by omega9380** [comment]
Any word from FD as to if they are updating the RedeemVoucher log event?

**Comment by cmdrmcdonald** [comment]
The relevant data is now available in the journal and a fix for this has been incorporated in to EDDI 2.3 (currently in beta).
