### ISSUE TITLE
Speechresponder.out - Not working when called from inside VA

### ISSUE THREAD

**Issue by omega9380** [cmdrmcdonald/EliteDangerousDataProvider#76]
When you execute the EDDI plugin from inside VA with the context "say", the speech is working fine, but the text version of the output in that instance is not being written to speechresponder.out.

When a regular EDDI event is triggered without VA, the text is written without issue.

**Comment by cmdrmcdonald** [comment]
"say" doesn't have anything to do with the speech responder, so no output would be written to the file.  If you want this to happen you'd need to add a new script in the speech responder and call it from VA with the "speech" context.
