### ISSUE TITLE
Voice clarity

### ISSUE THREAD

**Issue by BzDan** [cmdrmcdonald/EliteDangerousDataProvider#77]
I am running ED on a PC Win 7 machine using Voice Attack with ASTRA plus EDDI plugin and the EDDI's voice sounds "fuzzy" to me. My understanding is that the objective was to simulate the reverberation effect of the ship cockpit room. Myself, (and maybe others) I prefer a clear voice. 

Is it possible to have an option to choose using the "standard, as is" clear TTS voice without passing it through any filters that would give it this reverberation effect? 
Dan

**Comment by cmdrmcdonald** [comment]
In EDDI's 'Text-top-speech' tab there is an option for 'Level of voice processing'.  Turn this down to 0 and no effects will be applied.

**Comment by BzDan** [comment]
Yes, it works, Thank you !
 
Have a great Holiday, with good health and joy !
Dan
