### ISSUE TITLE
Feature request - Monospace font in script edit box

### ISSUE THREAD

**Issue by omega9380** [cmdrmcdonald/EliteDangerousDataProvider#79]
I tend to find myself copying the scripts to Notepad++ to edit them due to using a monospace font.  Could you change the font in the script edit box from (I assume) Segoe to something like Consolas or Lucidia Console?  Thanks!!!

**Comment by cmdrmcdonald** [comment]
Added in 591146074657f62b1e11623010024a0022a6a08e
