### ISSUE TITLE
Issue: Wrong data scraped from MissionAccepted journal entry

### ISSUE THREAD

**Issue by omega9380** [cmdrmcdonald/EliteDangerousDataProvider#80]
I do believe that you are scraping the incorrect entry for the commodity name on the Mission Accepted and Mission Completed events (possibly others too!)

For example, I accepted a delivery mission.  When I used "EDDI mission accepted commodity" in a VA script, the returned value was "$ReactiveArmour_Name".

As you can see from the log entry: 
`{ "timestamp":"2016-12-28T00:24:00Z", "event":"MissionAccepted", "Faction":"Revolutionary Sisii Alliance", "Name":"Mission_Delivery_Boom", "Commodity":"$ReactiveArmour_Name;", "Commodity_Localised":"Reactive Armour", "Count":6, "DestinationSystem":"LFT 300", "DestinationStation":"Petaja Vision", "Expiry":"2016-12-29T00:22:28Z", "MissionID":63341509 }`

I believe all you need to do is scrape "Commodity_Localised" instead of "Commodity".  I've noticed similar issues on a couple of other events I can't think of off the top of my head, but they are probably the same issue, needing to get the "_Localised" entry instead of the regular entry.  Thanks!!

**Comment by cmdrmcdonald** [comment]
It is not possible to use localised information as keys for internal lookups as they could be in any language.  The issue as to why the commodity was not parsed correctly has been fixed and will be available in the next release.
