### ISSUE TITLE
Mission Completed event does not set donation correctly for donation missions

### ISSUE THREAD

**Issue by omega9380** [cmdrmcdonald/EliteDangerousDataProvider#81]
I just completed a donation mission.  The variable {DEC:EDDI mission completed donation} was set to 0, even though the donation amount was 750,000.  Here is the VoiceAttackResponder:Handle event from the log:

`2016-12-28T01:46:43 VoiceAttackResponder:Handle [D] Received event {"missionid":63366390,"name":"Mission_AltruismCredits_name","faction":"Confederacy of Yamahun","commodity":null,"amount":null,"communal":false,"reward":0,"commodityrewards":[],"donation":0,"raw":"{ \"timestamp\":\"2016-12-28T01:46:43Z\", \"event\":\"MissionCompleted\", \"Faction\":\"Confederacy of Yamahun\", \"Name\":\"Mission_AltruismCredits_name\", \"MissionID\":63366390, \"Donation\":750000 }","timestamp":"2016-12-28T01:46:43Z","type":"Mission completed"}`

Let me know if you need more of the log.  Not sure why the donation variable is not being set, but here you are!

**Comment by Darkcyde13** [comment]
I get the same problem in the Mission Complete EDDI script with {event.donation}, it just says zero. This is on version 2.0.13.

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this.  It has been fixed and will be available in the next release.
