### ISSUE TITLE
ShipDetails() alway uses first ship

### ISSUE THREAD

**Issue by Darkcyde13** [cmdrmcdonald/EliteDangerousDataProvider#82]
The function ShipDetails() always uses my first ship as the reference, even if I provide a different ship to reference, like ShipDetails("Vulture") or ShipDetails(event,ship).

I started my game with a Cobra Mk3, and now that is always used for ShipDetails() even if I'm in another ship. Version is 2.0.13.

**Comment by cmdrmcdonald** [comment]
This is fixed in EDDI 2.1.
