### ISSUE TITLE
{event.target} in Bounty Awarded may be wrong?

### ISSUE THREAD

**Issue by Darkcyde13** [cmdrmcdonald/EliteDangerousDataProvider#83]
In scripts such as Ship Purchased, {event.ship} gives the real name of the ship in question.  However, in Bounty Awarded, {event.target} gives the game variable version of a ships name. For example, the Diamonback Explorer is called 'diamondbackxl' in {event.target}, or the Federal Assault Ship is called 'federation_dropship_mkii'.

When purchasing a ship, the journal entry uses the game variable name, but the script uses the real ship model name for {event.ship}.  Is it possible to make Bounty Awarded {event.target} do the same?

Would it also be possible to add the targets pilot name (for NPC or CMDR) as a variable for Bounty Awarded too?

**Comment by cmdrmcdonald** [comment]
I'm unable to reproduce the issue.  Elite 2.2.02 does not provide any target information, and when testing 2.2.03 it gives the correctly parsed ship name.

There is no information about target names provided in the bounty journal entries.

**Comment by Darkcyde13** [comment]
My apologies, you are quite correct.  Something must have changed since I last played in the Beta, which was some time before the Christmas Community Goal.  I had been writing a function to return the correct ship names from the given game variable, and had tested it extensively before Christmas.  Now it seems that it is no longer needed. Oh well! :) Thanks anyway.
