### ISSUE TITLE
Suggestion - New default personality scripts

### ISSUE THREAD

**Issue by Darkcyde13** [cmdrmcdonald/EliteDangerousDataProvider#84]
I was wondering if there was any way to submit possible updates to the default personality scripts?

I've expanded several of the default scripts with more varied responses and extra information, and I've added some new scripts where there were none.  I've also made a couple of my own functions for various code repeats and to convert game variables in to more humanised versions.

A couple of my friends have tried them out and love the extra immersion they provide.  Is there any way I can submit these for consideration as the default personality?

**Comment by cmdrmcdonald** [comment]
The default personality is a balance between those who want more information and those who want less, and although tweaked from time to time I'm not looking to significantly increase or decrease the information at current.

EDDI has been designed to allow multiple personalities, though, so if you have built your own personality you will be able to provide a way for other users to download it.  The personality you have created will be available at %APPDATA%\EDDI\personalities and if a user puts your file in to this location it will be available for them when they next start EDDI.
