### ISSUE TITLE
EDDI spelling the word "dash" in system names

### ISSUE THREAD

**Issue by omega9380** [cmdrmcdonald/EliteDangerousDataProvider#86]
I've been noticing this since EDDI 2.0 was released and keep forgetting to post an issue about it.  When EDDI reads out system names with dashed numbers, eg "LP 470-65", it is acually spelling out the word "dash" instead of saying "dash".  Looking at the log I think I see why: 

`2016-12-29T22:41:38 SpeechService:speak [D] Feeding normal text to synthesizer: Telemetry obtained. Daedalus is heading to the L P 4 7 0dash 65 system.. This is your first visit to this system. This system is a Federation Corporate with a population of just over 1 and a half million people. L P 4 7 0dash 65 Jet Public Services is the immediate power. There are 2 orbital stations in this system. `

It looks like when the speech responder converts the system name, it is not putting a space between the last number before the dash and the word dash.  It seems to only happen with dashed numbers, not dashed letters.  For example, Crucis Sector CW-V b2-5 is read correctly, because the converted name is passed as "Crucis Sector C W dash V b2 dash 5".

Let me know if I am getting annoying with all these posts :) I'm just loving EDDI and want it to work as you intended!

**Comment by cmdrmcdonald** [comment]
Fixed in 442e8edfd882e43ef25948b3204e941ce42709c4
