### ISSUE TITLE
Game data pushed to speech engine is always in English

### ISSUE THREAD

**Issue by Uriei** [cmdrmcdonald/EliteDangerousDataProvider#89]
I'm trying to translate each script EDDI has to Spanish for my own use, but I have a problem with some data, per example the default script for "System Report" after I translated it, `{system.government}` is in English, specifically this one is not really a problem, I can probably make a conditional with each possibility, but the real problem comes with `{Humanise(system.population)}` in Spanish it says "20 thousand", where 20 is in Spanish, but obviously it will still say "thousand", and I can't make a conditional for each possibility, it's almost infinite.

My question is whether this is an EDDI issue or that "20 thousand" string is as it is from the external pulled data?, the latest will be a pain to fix.

**Comment by cmdrmcdonald** [comment]
Humanise() is an internal EDDI function that takes a number and is hard-coded to return English.  Others who have created EDDI personalities in non-English languages have written their own version of humanise() as a cottle function to provide similar functionality, so I suggest that you do similar.

The default EDDI personality has a few functions such as 'Commodity purchase check' that you could look at to see how they work.
