### ISSUE TITLE
Not working in latest VA beta

### ISSUE THREAD

**Issue by nfxus** [cmdrmcdonald/EliteDangerousDataProvider#9]
I have tried to get his working in the latest beta of voice attack however it just reply's with this message
UNABLE TO INVOKE PLUGIN. PLUGIN NOT VALID FOR THIS VERSION OF VOICEATTACK.
The version of VA I have is 1.5.16
Are there any work arounds to regain functions or will there be an update soon for the latest beta?

**Comment by cmdrmcdonald** [comment]
Have you tried re-running shutting down VoiceAttack, rerunning the configuration exe and ensuring that you are logged in, and restarting VoiceAttack?

**Comment by nfxus** [comment]
Yes I did do all you had suggested. After a bit of searching, it seems VA was somehow blocked in my firewall. Once I unblocked it everything worked. Sorry for the hassle. Future note to anyone having same issues. Check firewall!
