### ISSUE TITLE
Reboot/Repair Sequence Module Names

### ISSUE THREAD

**Issue by Darkcyde13** [cmdrmcdonald/EliteDangerousDataProvider#90]
Hi,

I've just run a reboot/repair after combat, and the one module that was repaired from 0% to 1% was my 'Planetary Vehicle Hangar' size 4G.  I have the script list all that is repaired once this is complete, and it reported "Slot06_Size4".  Is this supposed to be the case? Or is it supposed to get the actual module name from somewhere?

The E:D journal entry is :- { "timestamp":"2017-01-02T17:16:42Z", "event":"RebootRepair", "Modules":[ "Slot06_Size4" ] } so I can see why it said "Slot06_Size4".

I was just curious as I can get around it with {ship.compartments[mod].module.name}, where [mod] is converted from the "Slot06" to the numerical value.

Also, in the Ship Repaired event, event.item is similar in that it returns the long game variable version of the module rather than the module name.  Is it possible to have the real module name returned instead?

**Comment by cmdrmcdonald** [comment]
FYI using the '06' as an index won't always work, as some ships don't have sequentially labelled slots.  I've raised a bug with FD to see if they can put the module names in place.

I'll fix the ship repaired item so that it provides a module name.
