### ISSUE TITLE
"Ship" object variables not being reset after using SRV

### ISSUE THREAD

**Issue by omega9380** [cmdrmcdonald/EliteDangerousDataProvider#91]
After running around on a planet in my SRV, I docked my SRV with my ship, lifted off, and jumped to a new system.  I have the Jumped script telling me my fuel level using the `ship.fueltanktotalcapacity` variable.  Now what is happening is it looks like the "ship" object variables are still set for the SRV even after docking into your ship.  Further evidence of this is after I jump, part of the "jumping" script says the name of the ship, and in this scenario, EDDI thinks my ship name is "TestBuggy" and the total tank capacity is 0.  It seems to right itself after docking at a station.  Let me know if u need any log info, I run with the debug log on all the time.  Thanks!!!

**Comment by cmdrmcdonald** [comment]
This is an issue with the FD API providing incorrect information when the user starts the game in an SRV (or fighter).  I'll have to see what I can do to work around it.

**Comment by FireSammy** [comment]
Additionally, i would hope to see EDDI triggered when logging into the game in SRV with "SRV launched", similar to "Touchdown", and "Location true/false". 

Ohh, and what happened to the VA ((Location)) as it seems to missing completely from the b3 beta version??? :O

**Comment by PurpleGranite** [comment]
Possibly related - sometimes the name stored against my ship in the EDDI 'Shipyard' tab is not spoken; instead saying "Your ASP Explorer Refuelled" instead of "MRS Corfarff Refuelled" for example.

**Comment by cmdrmcdonald** [comment]
The fix for this has been incorporated in to EDDI 2.3 (currently in beta).
