### ISSUE TITLE
Feature: Total count for variable count values

### ISSUE THREAD

**Issue by omega9380** [cmdrmcdonald/EliteDangerousDataProvider#94]
For variable count values, eg "Stored ship _n_ system" or "EDDI bounty awarded rewards _n_ faction", is it possible to have EDDI iterate a count of the total for _n_ and add it as a VA variable?  Eg, "Stored ship system totalcount".

I am using VA and EDDI to do a text log for my ship computer output and I am having problems using VA loops to iterate all of the _n_ variables.  A total count to check the loop against would make things much easier.  Thanks!!!

**Comment by cmdrmcdonald** [comment]
Any arrays that come as part of events will have an 'entries' value providing the number of items in the array, for example '{INT:EDDI bounty awarded rewards entries}'.

Stored ships are a custom item, and this doesn't have an entries value at the moment.  I'll look to add this.

**Comment by omega9380** [comment]
Odd, i didn't see that in the log.  I'll give it a try.  Thanks!

**Comment by omega9380** [comment]
That worked for EDDI bounty awarded!  You may want to add that to the VA doc, if you ever get time to update it :)
