### ISSUE TITLE
Companion app stopped working

### ISSUE THREAD

**Issue by futurekilled** [cmdrmcdonald/EliteDangerousDataProvider#95]
ok this morning i start everything like i normaly do and it says that the companion app api data is lost please update the companion app data. I have no idea what is going on so i put in my information plus the verification code and it says the same thing . here is a screenshot.

http://imgur.com/7BcaaYh

**Comment by cmdrmcdonald** [comment]
Frontier took their servers down this morning for an upgrade, and the companion app is part of that upgrade so it would not have been available.  Please check again when the Frontier servers are running again.

**Comment by futurekilled** [comment]
ok you can close it sorry for the nubness

**Comment by SeanLatimer** [comment]
I get a different error with the Companion App.

1. Enter username & password.
2. Confirm code sent to email.

 After that it throws back to the login form with this error:
![Error Screen](http://i.imgur.com/vSq8hpM.png)
