### ISSUE TITLE
Companion App Login Error

### ISSUE THREAD

**Issue by SeanLatimer** [cmdrmcdonald/EliteDangerousDataProvider#96]
1. Enter username & password.
2. Confirm code sent to email.

 After that it throws back to the login form with this error:
![Error Screen](http://i.imgur.com/vSq8hpM.png)

**Comment by omega9380** [comment]
jgm will probably recommend the same procedure, but I'll beat him to it.  Close EDDI.  Go to c:\users\{your username}\appdata\roaming\EDDI and delete the "credentials.json" file.  Reopen EDDI, go to the Companion App tab, and log in again.  Hope this helps!!
