### ISSUE TITLE
Give me a link when there's an upgrade

### ISSUE THREAD

**Issue by freiheit** [cmdrmcdonald/EliteDangerousDataProvider#98]
The voice thing is kinda fun, but sometimes I'm firing up EDDI with headset plugged in and not yet on my head, so I don't always hear that there's an upgrade.

Also, I keep having trouble remembering the right link to download an upgrade, since "EDDI" doesn't google well.

Giving me some kind of "hey, there's an upgrade" thing with a link to this git repo would make life much easier.

**Comment by Darkcyde13** [comment]
I'm not sure if CMDR McDonald is already preparing a future release with upgradeability built in.  It would be nice to have a button that lets you upgrade right in the program (and greyed out when no upgrade available).  Maybe even a toggle to switch between beta versions or full releases.

**Comment by MrLancerRalliart** [comment]
Yeah, it would be really nice to have an in-program button that updates the program for you, or a button that leads to the download page

**Comment by cmdrmcdonald** [comment]
This is fixed in release 2.2.0.
